### ISSUE TITLE
Encode atac seq commandline details

### ISSUE THREAD

**Issue by amirshams84** [ENCODE-DCC/atac-seq-pipeline#106]
is it possible to check the details of the command that the pipeline using?
the old one has a nice comprehensive log

**Comment by leepc12** [comment]
@amirshams84 : For each step (task) of the pipeline, actual shell command lines are wrapped in a python script in `/src/encode_TASKNAME.py`. You can also refer to this [document](https://docs.google.com/document/d/1f0Cm4vRyDQDu0bMehHD7P7KOMxTOP-HiNoIvL1VcBt8/edit).

**Comment by leepc12** [comment]
Closing this due to long inactivity
