### ISSUE TITLE
Error in CollectGcBiasMetrics during ATAQC module

### ISSUE THREAD

**Issue by ravipatel4** [ENCODE-DCC/atac-seq-pipeline#108]
Hello,

I am running the pipeline starting with nodup.bam files. The pipeline seemed to run successfully with previous version of the pipeline. However, when I downloaded the latest version of the pipeline couple of days ago, the pipeline breaks at picard's CollectGcBiasMetrics command during ATAQC module with `Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 130695116 out of bounds for length 130694994` error. After some investigation, I found where the out of bounds numbers are coming from. The length of chr10 is 130694993 and there is a read that maps to chr2 at 130695116. What is not clear is why picard tries to use length of chr10 for read mapping to chr2. I did little more investigation to find out the scripts that are calling picard's CollectGcBiasMetrics. It looks like before the get_gc function, which runs CollectGcBiasMetrics, is called by encode_ataqc.py, the input bam file is processed to remove read groups. However, this feature seem to be missing in older version of encode_ataqc.py. I am not sure if this is the culprit or I am doing something wrong. Please advice.

Thank you for your time.

[debug_bfadbaaa-2396-4275-b11f-0b1e5294afab.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3010269/debug_bfadbaaa-2396-4275-b11f-0b1e5294afab.tar.gz)

**Comment by leepc12** [comment]
No, removing read group will not help for your case. It's for those who get the following error:
```
Exception in thread "main" htsjdk.samtools.SAMFormatException: Error parsing SAM header. @RG line missing SM tag. Line:
```
How did you get your nodup.bam files? What kind of aligner did you use to map your FASTQs and how did you build indices for your reference genome? Do you have a chromosome sizes file for your reference genome? If so please post it here. You can use your own chrom sizes file in your input JSON.
`
{
    ....
    "atac.chrsz" : "/your/own/chr.sz"
    ....
}
```

**Comment by ravipatel4** [comment]
Thanks for a quick response Jin. Please find my answers below.
> 
> How did you get your nodup.bam files?

I trimmed adapters using cutadapt, aligned reads to the reference using bowtie2, removed duplicates using picard and removed low-quality alignments using `samtools view -bf 0x2 -q 30`.
> What kind of aligner did you use to map your FASTQs and how did you build indices for your reference genome? 

I use bowtie2 using `-p 16 -X 2000` parameters. I generated bowtie2 index using bowtie2-build.
> Do you have a chromosome sizes file for your reference genome? If so please post it here. You can use your own chrom sizes file in your input JSON.

The chr sizes of the fasta file used for generating bowtie2 index (as shown below) are same as the fasta file used by atac-seq-pipeline:
chr1    195471971
chr2    182113224
chr3    160039680
chr4    156508116
chr5    151834684
chr6    149736546
chr7    145441459
chr8    129401213
chr9    124595110
chr10   130694993
chr11   122082543
chr12   120129022
chr13   120421639
chr14   124902244
chr15   104043685
chr16   98207768
chr17   94987271
chr18   90702639
chr19   61431566
chrX    171031299
chrY    91744698
chrM    16299
>

**Comment by leepc12** [comment]
@vervacity Could you take a look at this problem?

**Comment by vervacity** [comment]
Hi, I'm thinking that the ordering in your fasta file and the ENCODE fasta file (used in ATAQC) must be different. I'm thinking this because (1) the reference fasta is the only reference file going into the picard call (2) it needs to be the same one that generated your bowtie indices for alignment. Can you perhaps do a `diff` or otherwise somehow compare the two fasta files?

**Comment by ravipatel4** [comment]
Hi @vervacity,

Yes, the order of chromosomes is different in the fasta file used to generate bowtie2 index and the ENCODE fasta file. Additionally, there are extra chromosomes in the ENCODE fasta, such as chrUn..., ...._random, which I removed from my fasta file before generating bowtie2 index. Do you think changing mm10.tsv by adding a path of my fasta file would be sufficient (other files in mm10.tsv would still be from ENCODE) or do you think I need to restart from the beginning, starting from mapping reads to the ENCODE fasta?

Thanks.

**Comment by leepc12** [comment]
Yes, you can keep using your TSV file. In your input JSON file, define the following to override reference FASTA defined in the TSV file.
```
{
    "atac.ref_fa" : "PATH_FOR_YOUR_OWN_FASTA"
}
```

**Comment by ravipatel4** [comment]
That worked! Thanks @leepc12 and @vervacity.
