### ISSUE TITLE
`*narrowPeak.hammock.gz` files are empty for non-standard chromosome names

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#110]
This issue is related to #47. If the reference genome doesn't have standard chromosome names (i.e. they don't start with `chr`), the `*narrowPeak.hammock.gz` files are empty because of the following command in `src/encode_common_genomic.py`:
```
zcat -f {} | sed '/^\(chr\)/!d' | LC_COLLATE=C sort -k1,1V -k2,2n > {}
```

**Comment by leepc12** [comment]
Thanks for reporting, this will be fixed in the next hotfix.
