### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/atac-seq-pipeline#115]
In the [Output Specification docs](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/output.md): 

> For more details, refer to the file table section in an HTML report generated by the pipeline. Files marked as (E) are outputs to be uploaded during ENCODE accession.

Which file is that comment referring to? I see 5 html files in the output of the pipeline: 

```
call-ataqc/shard-0/execution/ALS-29-ISO_diMN18_rep1_1.fastq.trim.merged_qc.html
call-ataqc/shard-0/execution/glob-47eccad02a94d57a391dcc7587d65007/ALS-29-ISO_diMN18_rep1_1.fastq.trim.merged_qc.html
call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b/qc.html
call-qc_report/execution/qc.html
call-qc_report/inputs/-305557727/ALS-29-ISO_diMN18_rep1_1.fastq.trim.merged_qc.html
```

I would anticipate that the comment referred to 
```
call-qc_report/execution/qc.html
```
but when I open that HTML in my browser, there's no section for output files. `qc.json` also has no output files listed. 

--- 

My real issue is I'm trying to capture the outputs of this pipeline. Is it safe to assume the output files are always under `/execution` but not under `/glob-*`? 

Thanks,

**Comment by leepc12** [comment]
Final HTML report is `call-qc_report/execution/qc.html`.
`/execution/glob-*/FILE` is a symlink of a file on `/execution/FILE`.\
However on Google Cloud Storage bucket,  `glob-*/FILE` is a physical file.

**Comment by zfrenchee** [comment]
@leepc12 thanks for getting back. 

In that case, I might recommend removing the line from the [docs](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/output.md): 

> For more details, refer to the file table section in an HTML report generated by the pipeline. Files marked as (E) are outputs to be uploaded during ENCODE accession.

or adding a section to `call-qc_report/execution/qc.html` listing the output files. 

---

What's the difference between 

```
call-reproducibility_overlap/execution/conservative_peak.narrowPeak.bb
```
and
```
call-reproducibility_idr/execution/conservative_peak.narrowPeak.bb
```

Which one can more appropriately be described as the "output" or "final" version?

**Comment by leepc12** [comment]
There are two post-peak-calling analyses (idr and overlap). Pipeline does reproducibility checks for each method. For ATAC-Seq, IDR is optional. Optimal_peak on overlap directory is recommended.

**Comment by zfrenchee** [comment]
@leepc12 So if I only look at one peak file, as the output of the entire pipeline, which file should it be?

**Comment by leepc12** [comment]
`call-reproducibility_overlap/execution/optimal_peak.narrowPeak.bb`
