### ISSUE TITLE
Fly Reference Genome

### ISSUE THREAD

**Issue by tAndreani** [ENCODE-DCC/atac-seq-pipeline#116]
Hello,  

I am planning to use the ENCODE ATAC-seq pipeline to analyze the
Drosophila melanogaster dataset from this work: https://shendurelab.github.io/fly-atac/   

I was wondering if you are planning to provide the .tsv file also for this genome annotation.

Thanks in advance

**Comment by leepc12** [comment]
[This](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/build_genome_database.md#how-to-build-genome-database-for-your-own-genome) should be helpful.

**Comment by tAndreani** [comment]
worked perfectly thanks!


--
Tommaso Andreani - PhD student

Computational Biology, DNA Demethylation and Reprogramming (Andrade and Niehrs Labs)

Institute of Molecular Biology gGmbH (IMB)

Ackermannweg 4, 55128 Mainz, Germany

Web: https://www.imb-mainz.de/

Phone: +49 6131 39 21584

Email: T.Andreani@imb-mainz.de


________________________________
Da: Jin Lee <notifications@github.com>
Inviato: venerdì 19 aprile 2019 19:30:25
A: ENCODE-DCC/atac-seq-pipeline
Cc: Andreani, Tommaso; Author
Oggetto: Re: [ENCODE-DCC/atac-seq-pipeline] Fly Reference Genome (#116)


This<https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/build_genome_database.md#how-to-build-genome-database-for-your-own-genome> should be helpful.
