### ISSUE TITLE
call-bowtie2 fails due to non-gzipped .gz intermediate merged fastq files

### ISSUE THREAD

**Issue by sorrywm** [ENCODE-DCC/atac-seq-pipeline#129]
**Describe the bug**
The pipeline fails at the bowtie2 step because the intermediate files created as input to bowtie are fastq rather than gzipped fastq, despite being named fastq.gz. These are the intermediate files located here:
atac-seq-pipeline/cromwell-executions/atac/<some number>/call-bowtie2/shard-n/inputs/<other number>/mysample_1.fastq.merged.fastq.gz

This is the command I use to run the pipeline:
java -jar \
-Dbackend.providers.Local.config.concurrent-job-limit=3 \
../cromwell-38.jar run atac.wdl -i resume.d7eec6a2-69a1-48ab-9acb-2b5349c41b15.json -m canFam3.metadata.json

This is the error I ultimately get:
[2019-06-04 16:30:22,16] [^[[38;5;1merror^[[0m] WorkflowManagerActor Workflow 29fa61ed-086d-445c-bca2-3d8ac29e336a failed (during ExecutingWorkflowState): Job atac.bowtie2:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
...(python output)...
File "/net/mahler/home/clark/wmeyer/.conda/envs/encode-atac-seq-pipeline/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

**OS/Platform and dependencies**
- OS or Platform: Ubuntu 16.04.5
- Cromwell/dxWDL version: cromwell-38.jar
- Conda version: conda 4.6.14

**Attach error logs**
Attached are:
-my cromwell stderr logs (these include those from test runs using the example data)
-my .o file from running the most recent job on the cluster
-both the starting and metadata .json files
I will attach a tarball once I post so I can generate an issue ID.

[canFam3_atac_pipeline.o.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3254491/canFam3_atac_pipeline.o.txt)
[canFam3.metadata.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3254492/canFam3.metadata.json.txt)
[cromwell_error_logs.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3254493/cromwell_error_logs.txt)
[resume.d7eec6a2-69a1-48ab-9acb-2b5349c41b15.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3254494/resume.d7eec6a2-69a1-48ab-9acb-2b5349c41b15.json.txt)

**Comment by sorrywm** [comment]
Here is the tarball with further cromwell files.

[debug_Issue129.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3254505/debug_Issue129.tar.gz)

**Comment by leepc12** [comment]
==> ./atac/b5fe830c-f329-4d4b-9fc3-a451c0176611/call-trim_adapter/shard-0/execution/stderr <==
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/net/mahler/home/clark/wmeyer/bin/atac-seq-pipeline/src/encode_trim_adapter.py", line 123, in trim_adapter_pe
    run_shell_cmd(cmd)
  File "/net/mahler/home/clark/wmeyer/bin/atac-seq-pipeline/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=3081, PGID=3081, RC=127
STDERR=/bin/bash: line 1: cutadapt: command not found
STDOUT=
"""

Pipeline couldn't find `cutadapt`. Please activate Conda environment before running a pipeline or use singularity/docker to resolve software dependencies.

**Comment by sorrywm** [comment]
Thank you, but this is unrelated to my current issue. As I mentioned, the steps you recommend to collate the Cromwell logs have captured some data from previous runs. Now I am on to the call-bowtie2 step, which I would not have reached without activating conda. I believe the .o file may be a more accurate log of my most recent run; if you know a way to get just the most recent cromwell logs, please let me know.

**Comment by leepc12** [comment]
Please check if those gz files are empty or not.

**Comment by sorrywm** [comment]
They are not empty. They appear to be standard, non-zipped fastq format files, just with filenames ending in .gz.

**Comment by leepc12** [comment]
I am sure that this is just a dependency issue. Please start over with [caper](https://github.com/ENCODE-DCC/caper). I think that will fix your problem.

**Comment by leepc12** [comment]
Closing this due to long inactivity
