### ISSUE TITLE
Failure to Find Path to Scripts in src with Latest Changes to Repository

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#131]
**Describe the bug**
I pulled the latest version of the repository this morning without changing anything else about my path or environment, and the pipeline now crashes on the first step.  It seems like the pipeline can no longer find the scripts in the src directory.  I tried re-building the genome and uninstalling and reinstalling the dependencies.  Neither of these solved the problem.

**OS/Platform and dependencies**
- OS or Platform: Cluster with Linux with Centos 6
- Cromwell/dxWDL version: cromwell-34.jar
- Conda version: conda 4.6.14
- singularity version: N/A

**Attach error logs**
For Cromwell users only.
1) Move to your working directory where you ran a pipeline. You should be able to find a directory named `cromwell-executions/` which includes all outputs and logs for debugging.

2) Run the following command line to print all non-empty STDERR outputs. This will be greatly helpful for developers to figure out the problem. Copy-paste its output to the issue page.
```
$ find -name stderr -not -empty | xargs tail -n +1
```
==> ./call-trim_adapter/shard-0/execution/stderr <==
which: no encode_trim_adapter.py in ([home directory]/anaconda2/envs/encode-atac-seq-pipeline/bin:[home directory]/anaconda2/condabin:[rest of path])
  File "[directory where pipeline was launched]/cromwell-executions/atac/13206475-7f89-4f17-a450-e98d6585024b/call-trim_adapter/shard-0/execution/write_tsv_b011739c8925326e13e7ff56b4e5256b.tmp", line 1
    [directory where pipeline was launched]/cromwell-executions/atac/13206475-7f89-4f17-a450-e98d6585024b/call-trim_adapter/shard-0/inputs/1982711240/[rep. 1 read 1 fastq file name].fastq.gz [directory where pipeline was launched]/cromwell-executions/atac/13206475-7f89-4f17-a450-e98d6585024b/call-trim_adapter/shard-0/inputs/1982711240/[rep. 2 read 2 fastq file name].fastq.gz
    ^
SyntaxError: invalid syntax

A similar error message appears in the directories of the 4 other biological replicates.

**Comment by leepc12** [comment]
`which: no encode_trim_adapter.py in` means that pipeline couldn't find `encode_trim_adapter.py` in your $PATH.

Something is wrong with your conda activation.

Please try
```
find [home directory]/anaconda2/envs/encode-atac-seq-pipeline/bin -name encode_trim_adapter.py
```

BTW we recommend to use [Caper](`pip3 install caper`), which is a python wrapper for Cromwell, instead of directly calling cromwell.jar in the command line.

**Comment by imk1** [comment]
That did not return anything.

Where should the scripts within the src directory be within my conda activation?  What part of the installation pipeline do I need to re-run to get them there?  Thanks!

**Comment by leepc12** [comment]
That should look like this
```
(base) leepc12@kadru:/users/leepc12/code/test_wdl$ ls /users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_*
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_ataqc.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bam2ta.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_blacklist_filter.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_blacklist_filter.pyc
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bowtie2.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_genomic.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_genomic.pyc
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_html.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_html.pyc
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_log_parser.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_log_parser.pyc
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.pyc
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_count_signal_track.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_filter.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_frip.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_frip.pyc
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_signal_track_atac.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_naive_overlap.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_pool_ta.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_qc_report.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_reproducibility_qc.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_spr.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_trim_adapter.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py
```

Did you run `conda/update_conda_env.sh` after installing conda env? Step 5 of https://github.com/ENCODE-DCC/atac-seq-pipeline#conda

**Comment by imk1** [comment]
I did run it when I originally installed the pipeline but not when I made the latest update.  I just ran it, and i think that might have solved the problem.  Thanks for the suggestion!
