### ISSUE TITLE
atac.wdl - add docker to task runtime

### ISSUE THREAD

**Issue by joshua-gould** [ENCODE-DCC/atac-seq-pipeline#132]
The docker runtime attribute is mandatory when running in the cloud. I understand that your tool Caper adds this, but it would be nice to have for users that want to use Cromwell directly.

**Comment by leepc12** [comment]
You can refer to [this document](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/deprecated/OLD_METHOD.md) to use Cromwell directly.
Use `workflow_opts/docker.json` to add docker attribute to `runtime {}` section.
```
java -jar cromwell-42.jar atac.wdl -i YOUR_INPUT_JSON -o workflow_opts/docker.json
```

**Comment by leepc12** [comment]
Closing this due to long inactivity
