### ISSUE TITLE
sherlock2.0: atac-seq-pipeline-v1.4.2.simg

### ISSUE THREAD

**Issue by PocketChangeJ** [ENCODE-DCC/atac-seq-pipeline#133]
Hi, 
It appears the  'atac-seq-pipeline-v1.3.0.simg' and 'atac-seq-pipeline-v1.4.2.simg' are missing.

`ESC[31mFATAL:  ESC[0m failed to retrieved path for /home/groups/cherry/encode/pipeline_singularity_images/atac-seq-pipeline-v1.3.0.simg: lstat /home/groups/cherry/encode/pipeline_singularity_images/atac-seq-pipeline-v1.3.0.simg: no such file or directory`

Thank you!

**Comment by leepc12** [comment]
Singularity images are built individually for each user. I will close this.
