### ISSUE TITLE
Resume pipeline

### ISSUE THREAD

**Issue by jwtobias** [ENCODE-DCC/atac-seq-pipeline#137]
I have two pipeline executions that failed at different points in the macs2 stage, but at approximately the same time of day. I suspect that the problem may have been related to an issue on my LSF cluster, so before I try to troubleshoot the pipeline itself, I'd like to try resuming the pipelines. These are the commands I used to start them:

caper run /home/jtobias/pk/pipeline/atac.wdl -i /home/jtobias/pk/input/stg10.json -s stg10
- used default database
- left me a metadata.json file

caper -c /home/jtobias/.caper/s12.conf run /home/jtobias/pk/pipeline/atac.wdl -i /home/jtobias/pk/input/stg12.json -s stg12
-used run-specific database
-did not write a metadata.json file

In version 1.4.2 of the pipeline, how should I resume these runs?

**Comment by leepc12** [comment]
Caper can resume but it actually starts over and take outputs from cache with `Call-Cached` message. Those cached outputs are soft-linked from previous workflows' directory.

Please check if you see `Call-cached` messages.

Caper defaults to use Cromwell's call-caching if `--file-db`  (or mysql db) is defined.

**Comment by jwtobias** [comment]
Thanks.  So in my situation, first run with default and second with a different file_db (as defined in conf file rather than on the command line), what are my caper commands to resume? The same as those that started the run?

**Comment by leepc12** [comment]
You should use the same default `file-db` for the second run. Use the same command line then pipeline will resume.

**Comment by leepc12** [comment]
Closing this due to long inactivity
