### ISSUE TITLE
Test failing at sambamba sort step in bam to tagAlign conversion

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#139]
**Describe the bug**
The test script seems to be failing with a segmentation fault at the sambamba sort step in the bam to tagAlign conversion.

**OS/Platform and dependencies**
- OS or Platform: [e.g. Ubuntu 16.04, Google Cloud, Stanford Sherlock/SCG cluster, ...] Linux cluster with slurm
- Cromwell/dxWDL version: [e.g. `cromwell-34.jar`, `dxWDL-78.jar`] cromwell-38.jar
- Conda version: If you have used Conda (`$ conda --version`). 4.6.14
- singularity version: If you have used singularity (`$ singularity --version`). N/A

**Attach error logs**
For Cromwell users only.
1) Move to your working directory where you ran a pipeline. You should be able to find a directory named `cromwell-executions/` which includes all outputs and logs for debugging.

2) Run the following command line to print all non-empty STDERR outputs. This will be greatly helpful for developers to figure out the problem. Copy-paste its output to the issue page.
```
$ find -name stderr -not -empty | xargs tail -n +1
```
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bam2ta.py", line 156, in <module>
    main()
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bam2ta.py", line 120, in main
    args.nth, args.out_dir)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bam2ta.py", line 65, in bam2ta_pe
    nmsrt_bam = sambamba_name_sort(bam, nth, out_dir)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common_genomic.py", line 101, in sambamba_name_sort
    run_shell_cmd(cmd)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=53014, PGID=53014, RC=139
STDERR=/bin/bash: line 1: 53015 Segmentation fault      sambamba sort -n /pylon5/mc5fq4p/ikaplow/atac-seq-pipeline/cromwell-executions/atac/c5679e97-9adc-49a8-938b-fa414bfe4fb6/call-bam2ta/shard-0/inputs/1292765779/ENCFF341MYG.subsampled.400.trim.merged.nodup.bam -o ENCFF341MYG.subsampled.400.trim.merged.nodup.nmsrt.bam -t 2
STDOUT=

3) (OPTIONAL) Run the following command to collect all logs. For developer's convenience, please add `[ISSUE_ID]` to the name of the tar ball file. This command will generate a tar ball including all debugging information. Post an issue with the tar ball (`.tar.gz`) attached.
```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_[ISSUE_ID].tar.gz
```

**Comment by leepc12** [comment]
Looks related to https://github.com/kundajelab/atac_dnase_pipelines/issues/98? BTW we will remove `sambamba` completely from the pipeline in the next release.

**Comment by imk1** [comment]
Thanks so much for getting back to me!  I tried everything suggested in the issue you reference, and none of it solved the problem.  Here are my outputs to ulimit -a:

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514464
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 262144
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Is the stack size sufficiently large?

If so, please let me know if you have other suggestions.  Thanks!

**Comment by leepc12** [comment]
Can you check your disk space?
```
echo $TMPDIR
df -h .
df -h $TMPDIR
df -h /tmp
```

**Comment by imk1** [comment]
Here is what I got for each of these:

echo $TMPDIR
/pylon5/mc5pihp/ikaplow/tmp

df -h .
Filesystem                Size  Used Avail Use% Mounted on
10.4.112.79@o2ib:/pylon5  6.9P  6.0P  971T  87% /pylon5

df -h $TMPDIR
Filesystem                Size  Used Avail Use% Mounted on
10.4.112.79@o2ib:/pylon5  6.9P  6.0P  971T  87% /pylon5

df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       188G   71G  110G  40% /

Thanks for helping me figure this out!

**Comment by leepc12** [comment]
I think your stack size is large enough. `/tmp` looks a bit small but `TMPDIR` is defined so `sambamba` should use `TMPDIR`.
```
$ conda search sambamba -c bioconda
Loading channels: done
# Name                       Version           Build  Channel
sambamba                       0.5.9               0  bioconda
sambamba                       0.5.9               1  bioconda
sambamba                       0.6.1               0  bioconda
sambamba                       0.6.2               0  bioconda
sambamba                       0.6.3               0  bioconda
sambamba                       0.6.5               0  bioconda
sambamba                       0.6.6               0  bioconda
sambamba                       0.6.6               1  bioconda
sambamba                       0.6.6               2  bioconda
sambamba                       0.6.8      h682856c_0  bioconda
sambamba                       0.6.8      h682856c_1  bioconda
sambamba                       0.6.8      h89e63da_2  bioconda
sambamba                       0.6.9      h89e63da_0  bioconda
sambamba                       0.7.0      h89e63da_0  bioconda
sambamba                       0.7.0      h89e63da_1  bioconda
```

Can you update your sambamba from 0.6.6 to 0.7.0 (latest on bioconda) and try again?
```
$ source activate encode-atac-seq-pipeline
$ conda install sambamba==0.7.0 -c bioconda
```

**Comment by imk1** [comment]
That produced the following error:

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sambamba==0.7.0 -> ldc=1.10

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I installed the latest version of ldc available in conda-forge.  After that, I was able to install sambamba version 0.7.0.  I then updated the environment.  sambamba seems to be working, but I now get this error:

==> ./call-idr/shard-0/execution/stderr <==
Traceback (most recent call last):
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 169, in <module>
    main()
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 137, in main
    args.idr_thresh, args.idr_rank, args.out_dir)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 93, in idr
    run_shell_cmd(cmd1)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=34653, PGID=34653, RC=127
STDERR=/bin/bash: line 1: idr: command not found
STDOUT=

==> ./call-idr_pr/shard-0/execution/stderr <==
Traceback (most recent call last):
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 169, in <module>
    main()
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 137, in main
    args.idr_thresh, args.idr_rank, args.out_dir)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 93, in idr
    run_shell_cmd(cmd1)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=34414, PGID=34414, RC=127
STDERR=/bin/bash: line 1: idr: command not found
STDOUT=

==> ./call-idr_pr/shard-1/execution/stderr <==
Traceback (most recent call last):
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 169, in <module>
    main()
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 137, in main
    args.idr_thresh, args.idr_rank, args.out_dir)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_idr.py", line 93, in idr
    run_shell_cmd(cmd1)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=34336, PGID=34336, RC=127
STDERR=/bin/bash: line 1: idr: command not found
STDOUT=

Thanks for helping me figure this out!

**Comment by leepc12** [comment]
`idr: command not found` tells you that Conda environment was not installed correctly. There are two separate Conda envs for the pipeline (encode-atac-seq-pipeline, encode-atac-seq-pipeline-python3).

You need to run the following in a correct order. Please run the following to re-install Conda envs.
```
conda/uninstall_dependencies.sh
conda/install_dependencies.sh
conda/config_conda_env.sh
conda/update_conda_env.sh
```

We will have a new release by end of this week. `sambamba` will be replaced with `samtools`.

Did you use Caper to run pipelines? If not please try with Caper next time.

**Comment by imk1** [comment]
That worked!  Thanks so much!  I will run conda/config_conda_env.sh before running conda/update_conda_env.sh if I have a problem in the future.
