### ISSUE TITLE
Read Count after Removing Duplicate Reads is Lower than Final Read Count

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#145]
**Describe the bug**
I ran the pipeline with allowing for up to 2 multi-mappers.  In the QC report, the number of reads after filtering duplicate reads is lower than the final number of filtered reads.  Why might this happen?
Here is a copy of the top of the QC table:
![image](https://user-images.githubusercontent.com/6392583/62712844-a3d94100-b9c9-11e9-8dc4-95231535c391.png)

Thanks for helping me understand this!

**OS/Platform and dependencies**
- OS or Platform: Linux cluster with slurm
- Conda version: 4.6.14
- Caper version
- If not using Caper
  - Cromwell/dxWDL version: cromwell-38.jar

**Attach error logs**
Caper users:
Caper automatically run troubleshooter for failed workflows. If not and If you ran a Caper server and then get workflow_id of your failed workflow with `caper list`. Or directory use a `metadata.json` file on Cromwell's output directory
```
$ caper troubleshoot [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

Non-Caper users:
1) Move to your working directory where you ran a pipeline. You should be able to find a directory named `cromwell-executions/` which includes all outputs and logs for debugging.

2) Run the following command line to print all non-empty STDERR outputs. This will be greatly helpful for developers to figure out the problem. Copy-paste its output to the issue page.
```
$ find -name stderr -not -empty | xargs tail -n +1
```

3) (OPTIONAL) Run the following command to collect all logs. For developer's convenience, please add `[ISSUE_ID]` to the name of the tar ball file. This command will generate a tar ball including all debugging information. Post an issue with the tar ball (`.tar.gz`) attached.
```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_[ISSUE_ID].tar.gz
```
[debug_145.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3482311/debug_145.tar.gz)

**Comment by leepc12** [comment]
This is already fixed in the current dev branch and will be applied to the next release.

**Comment by imk1** [comment]
I noticed that the number of reads in the tagAlign file is different from anything reported in the QC report.  Can I trust that the reads were filtered properly, or should I re-run the pipeline once the next release is out?  Thanks!

**Comment by leepc12** [comment]
How is it different? Can you post an example? BTW we will use `SAMstats` (https://github.com/kundajelab/SAMstats) instead of `samtools flagstat`.  `SAMstats` will be more accurate than the latter.

**Comment by imk1** [comment]
In the example above, the QC report said that the final number of reads was 21,820,160.  However, the tagAlign file had 20,853,940 lines.

Here are the results from the flagstat file for the corresponding nodup.bam file:
21820160 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
21820160 + 0 mapped (100.00%:N/A)
21820160 + 0 paired in sequencing
10910080 + 0 read1
10910080 + 0 read2
21820160 + 0 properly paired (100.00%:N/A)
21820160 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

I ran samstat on the file, and here is a screenshot of the beginning of the html report:
![image](https://user-images.githubusercontent.com/6392583/62835857-fa918580-bc2a-11e9-82b9-fac7bae20796.png)

**Comment by leepc12** [comment]
For current version of the pipeline, mito reads are removed during the BAM to TAGALIGN conversion step. So BAM still has chrM reads. We are thinking of removing chrM reads at filtering time.

**Comment by imk1** [comment]
Thanks for explaining that!
