### ISSUE TITLE
hard-link problems

### ISSUE THREAD

**Issue by fangpingmu** [ENCODE-DCC/atac-seq-pipeline#152]
I'm testing the ENCODE ATAC SEQ pipeline on a cluster. We are using BeeGFS file system, hard links do not work across directories. Due to security reasons, hard links are not supported in many network mounts and virtual environments. 

Cromwell uses hard link by default. I changed the Cromwell configuration file to solve the wdl-related hardlink problems. Now the pipeline runs to “call-reproducibility_overlap” step. 

call-reproducibility_overlap

 Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_reproducibility_qc.py", line 160, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_reproducibility_qc.py", line 76, in main
    conservative_peak = make_hard_link(args.peaks[Nt_idx], args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_common.py", line 197, in make_hard_link
    os.link(f, linked)
OSError: [Errno 1] Operation not permitted

It seems that atac-seq-pipeline/src/encode_common.py uses embedded functions to generate hardlink. 

https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/src/encode_common.py

188   os.link(f, link)
197   os.link(f, link)

 Can these os.link(f,linked) be changed to os.symlink(f, linked)?

**Comment by leepc12** [comment]
This will be fixed (by using `os.symlink` instead of `os.link`) in the next release. Commit a28c6695c9c76bcb706785691c22883ee97055cd.
