### ISSUE TITLE
Can't run pipeline through caper server on SCG

### ISSUE THREAD

**Issue by asanghi7** [ENCODE-DCC/atac-seq-pipeline#154]
Hello,

I haven't been able to run the ATAC-seq pipeline via the SCG using caper. The error below is one that I received. I definitely updated the host name with SCG node that was running the server.

HTTPConnectionPool(host='dper730xd-srcf-d16-05', port=8000): Max retries exceeded with url: /api/workflows/v1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2af230c0efd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by leepc12** [comment]
I updated Caper and it automatically takes hostname from server.
But I don't recommend to use `caper server`.

Please update Caper to >= 0.4.0 and try again.

Remove your current default configuration file `~/.caper/default.conf`.
Run `caper init scg` to make a new conf file.
This conf file includes only required parameters.
See description for each parameter on Caper's README

Also, `caper server` doesn't seem to be stable on SCG.
Let's use `caper run` for each workflow.
See Caper's REAMDE then you will get a full command line for it.

**Comment by asanghi7** [comment]
Thank you! The way to check the status of the run is to go through the output directory?

**Comment by asanghi7** [comment]
Also, do I add the --singularity flag to the "caper run" command?

**Comment by leepc12** [comment]
Yes, but let's use Conda this time and conda environment. Conda is more stable now.
Workflow-monitoring It is also described in Caper's README.
Use something like `squeue $USER | grep -v cromwell`. Give each workflow a short `JOB_NAME` when you `sbatch` them.

**Comment by asanghi7** [comment]
I'm getting an error in my slurm output that says caper: command that found. This happened after I ran the command export PATH=$PATH:~/.local/bin...I was using singularity before so perhaps my Conda isn't compatible...Conda lists no packages in environment at /home/asanghi/miniconda3/envs/encode-atac-seq-pipeline

**Comment by leepc12** [comment]
Did you re-login after you modifying your `~/.bashrc`?
Can you `ls -l ~/.local/bin` for debugging?

**Comment by leepc12** [comment]
Uninstall conda env and reinstall it.
```
$ scripts/uninstall_conda_env.sh
$ scripts/install_conda_env.sh
```

**Comment by leepc12** [comment]
Closing this due to long inactivity.
