### ISSUE TITLE
Issues finishing pipeline with Caper

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#166]
Hello, I tried running two pipelines (called `acute_male_0h` and `control_male_0h`, custom genome and 5 replicates for each), and I'm seeing a few weird things going on. 

First, I only see .log, .lck, .lobs, .properties, and .script files in the output directory for `acute_male_0h`. 

Second, the slurm log file for `acute_male_0h` has a lot of errors, including lots of read/write errors to the pipeline log files (`data commit failed`) and java stale file handle errors. However, the slurm log file for `control_male_0h` looks pretty much as expected up until the end (after writing the QC reports), where it gives this Java error: `java.util.NoSuchElementException: No value found for 'QueuedIn'`, and then a whole bunch of lines repeating this: `SingleWorkflowRunnerActor: received unexpected message: QueueWeight(0) of type cromwell.core.actor.BatchActor.QueueWeight in state RequestingMetadata`

Both pipelines have been running for ~40 hours (leader jobs are still running without child jobs), and text is still being written to the log files, but the pipelines outputs look largely complete. One of the last files created in each run were the `call-qc_report/qc.json` files, which were written 9 hours ago and look complete. As far as I can tell, only changes to the main log files have been made since then, and `metadata.json` has not been written yet. One of the slurm log files (for `acute_male_0h`) is almost 1GB. Can you help me figure out what is going on here? If I kill the leader jobs, is there a way to generate the Caper metadata file to easily organize outputs?

[logs.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3752006/logs.zip)
I attached the slurm log files and the `acute_male_0h.log` file.

**OS/Platform and dependencies**
- SCG
- Conda version: 4.7.12
- Caper version: 0.4.1

**Comment by nicolerg** [comment]
Whoops, I think I found my mistake... the HTML reports are both for `acute_male_0h`, so I must have run `sbatch` twice with the same config file instead of with the `control_male_0h` config file. Does this sound like a possible explanation for the issues described above?

**Comment by leepc12** [comment]
If you have run two pipelines without specifying `--file-db` or `-d` then both `acute_male_0h` leader jobs tried to access to the same DB file. There is a DB lock file (.lck). Did you see two leader jobs for `acute_male_0h` on `squeue`? Did you sbatch with the same job name? Did you use Conda or singularity?

**Comment by nicolerg** [comment]
I just looked through my history and saw I accidentally ran the pipeline with the same config file twice. I used Conda. The job names were also the same (oversight from re-using a command). I will change that in the future. Do you have to use `-d` every time you are running the pipelines multiple times with the same output directory? Or just when the job names are the same?

**Comment by leepc12** [comment]
No, Caper defaults to use input JSON file's basename (on `--out-dir` or your working directory) for `-d`. That job name is for `sbatch` not for Caper.

**Comment by nicolerg** [comment]
Thank you for the clarifications!
