### ISSUE TITLE
Child process runs (indefinitely?) after core dump

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#170]
A run of the pipeline failed with a core dump (bus error), probably because I didn't request enough memory. My question here is that while the leader process ended, one of the child processes kept running on the job submission system until I killed it ~12 hours later, presumably not doing much other than using compute time (no changes to any files were made for ~8 hours before I killed it). Is there a way to automatically kill all child processes along with the leader job after a pipeline failure?

**OS/Platform and dependencies**
- OS or Platform: SCG SLURM
- Conda version: 4.7.12
- Caper version: 0.4.1

**Comment by leepc12** [comment]
I think it's an issue of Cromwell. Did you run a Cromwell server (`caper server`)?

**Comment by nicolerg** [comment]
I ran it with the following command: `sbatch -A ${account} -J male_control_0h --export=ALL --mem 2G -t 4-0 --wrap "caper run ${wdl} -i ${INPUT} --out-dir ${outdir}"`.

**Comment by leepc12** [comment]
I think the cluster `SIGKILL`ed it so that Cromwell didn't have time to gracefully die `scancel`ing all its children. If `--mem 2G` was not enough please let me know so that I can update the documentation and increase default JAVA heap for `caper run`.

**Comment by nicolerg** [comment]
Okay, I will let you know if that is that case. For now I just bumped up the resource requests for different steps in the config file. This was in the `stderr` file for `call-align/shard-4`: ```8ffb3d85-bd05-4bc9-b203-3f4ca709fcb3/call-align/shard-4/execution/script: line 69: 41667 Bus error               (core dumped) python3 $(which encode_task_bowtie2.py) 8ffb3d85-bd05-4bc9-b203-3f4ca709fcb3/call-align/shard-4/inputs/1442233120/Rattus_norvegicus.Rnor_6.0.dna.toplevel.standardized.fa.tar R1/*.fastq.gz R2/*.fastq.gz --paired-end --multimapping 4 --nth 4
slurmstepd: error: *** JOB 12147096 ON dper7425-srcf-d15-25 CANCELLED AT 2019-10-23T12:38:47 ***```. Does that sound like a memory error external to bowtie?

**Comment by leepc12** [comment]
Is your backend SLURM (`backend=slurm` in your conf file)?

**Comment by nicolerg** [comment]
```
backend=slurm
slurm-account=prj_motrpac

tmp-dir=/labs/smontgom/nicolerg/tmp
```

**Comment by leepc12** [comment]
Yes you may need to increase max memory for bowtie2 in your input JSON. How big is your fastq and how many of them for each replicate?

**Comment by nicolerg** [comment]
Between 3.1G and 3.8G for each FASTQ file, 2 FASTQ files per replicate (R1 and R2), 5 replicates in the pipeline. From config file: `"atac.bowtie2_mem_mb" : 20000, "atac.bowtie2_cpu" : 4`. I bumped up `atac.bowtie2_mem_mb` to 40G.

**Comment by leepc12** [comment]
I see. Please let me know if that works.

**Comment by nicolerg** [comment]
That did work. But then does that mean child processes of the pipeline won't necessarily be killed when a memory error causes a core dump?

**Comment by leepc12** [comment]
I think it's Cromwell's issue. A kill command for SLURM is correctly defined here with `scancel ${job_id}`.
https://github.com/ENCODE-DCC/caper/blob/master/caper/caper_backend.py#L371

**Comment by nicolerg** [comment]
It happened again, except this time, the parent process didn't die either. Out of 5 more jobs I started running yesterday, 2 of them have this error in `call-align`: 
```
atac/b302bc69-05d9-4b20-b301-2d1cc87ddc46/call-align/shard-3/execution/script: line 69: 27968 Bus error               (core dumped) python3 $(which encode_task_bowtie2.py) atac/b302bc69-05d9-4b20-b301-2d1cc87ddc46/call-align/shard-3/inputs/1442233120/Rattus_norvegicus.Rnor_6.0.dna.toplevel.standardized.fa.tar R1/*.fastq.gz R2/*.fastq.gz --paired-end --multimapping 4 --nth 4
```
This is after bumping up the resources requests to `"atac.bowtie2_cpu"` : 4 and `"atac.bowtie2_mem_mb" : 40000`.

Both are still running the parent job as well as the `align` child job, e.g. `cromwell_b302bc69_align`, but nothing has been written to files in `atac/*` for several hours. Text is still being written to the `caper_file_db*log` files. Here's the tail for both:

```
COMMIT
DELETE FROM SUMMARY_STATUS_ENTRY WHERE SUMMARY_STATUS_ENTRY_ID=0
INSERT INTO SUMMARY_STATUS_ENTRY VALUES(0,'WORKFLOW_METADATA_SUMMARY_ENTRY_INCREASING',173)
COMMIT
DELETE FROM SUMMARY_STATUS_ENTRY WHERE SUMMARY_STATUS_ENTRY_ID=0
INSERT INTO SUMMARY_STATUS_ENTRY VALUES(0,'WORKFLOW_METADATA_SUMMARY_ENTRY_INCREASING',173)
COMMIT
DELETE FROM SUMMARY_STATUS_ENTRY WHERE SUMMARY_STATUS_ENTRY_ID=0
INSERT INTO SUMMARY_STATUS_ENTRY VALUES(0,'WORKFLOW_METADATA_SUMMARY_ENTRY_INCREASING',173)
COMMIT
```
The end of `cromwell-workflow-logs/workflow*log` looks like this, where the last line is repeated many times: 
```
2019-10-25 01:44:10,660 INFO  - WorkflowExecutionActor-1b7483ac-7d6b-436a-a836-cc34be39d734 [UUID(1b7483ac)]: Starting atac.call_peak_pr2, atac.call_peak_pr1
2019-10-25 01:44:12,617 WARN  - DispatchedConfigAsyncJobExecutionActor [UUID(1b7483ac)atac.call_peak_pr1:2:1]: Unrecognized runtime attribute keys: disks
2019-10-25 01:44:14,600 WARN  - DispatchedConfigAsyncJobExecutionActor [UUID(1b7483ac)atac.call_peak_pr2:2:1]: Unrecognized runtime attribute keys: disks
2019-10-25 17:10:13,521 INFO  - DispatchedConfigAsyncJobExecutionActor **[UUID(1b7483ac)atac.align:3:1]: executing: for ITER in 1 2 3; do CHK_ALIVE=$(squeue --noheader -j 12159800 --format=%i | grep 12159800); if [ -z "$CHK_ALIVE" ]; then if [ "$ITER" == 3 ]; then /bin/bash -c 'exit 1'; else sleep 20; fi; else echo $CHK_ALIVE; break; fi; done**
```

**Comment by nicolerg** [comment]
~10 minutes after `scancel`ing the parent jobs, the child jobs don't die either. Is that expected behavior?

**Comment by leepc12** [comment]
There were some parameter name changes. Please try with `atac.align_cpu` and `atac.align_mem_mb`.
```
"atac.bowtie2_*" -> "atac.align_*"
"atac.macs2_*" -> "atac.call_peak_*"
```

**Comment by nicolerg** [comment]
Whoops, I didn't mean to close the issue. Thank you, I will try that.

**Comment by ro-joshi** [comment]
I have been getting a similar memory related error randomly as well on SCG and another cluster. It has been occurring when I run a lot of pipelines simultaneously through caper. When I repeat the pipelines in isolation, they run fine. I think these problems are due to overloading the NFS filesystem where the output directory is located with huge reads/writes; I think the writes are getting cached into memory as NFS gets backed up, which quickly overwhelms the job's memory. Just a theory.

It would be nice for caper to allow a slurm job to write and read all intermediate files to and from a local disk on the cluster node, then at the end of the slurm job copy all necessary files to the output directory. This would reduce NFS traffic a lot and also potentially speed up the pipeline since there's less interaction with network storage. This hopefully would be compatible with cromwell call caching also.

**Comment by leepc12** [comment]
I think this has something to do with Cromwell's file DB. Cromwell allows a file DB (HSQLDB) instead of a default in-memory DB but the DB file grows very quickly and gets corrupted easily and still takes a lot of memory (sometimes >10GB with less than 10 workflows).

Until we figure out this issue please use MySQL DB instead. Disable HSQLDB file DB with `-n` and define MySQL parameters instead. Use `run_mysql_server_singularity.sh` to run MySQL DB on HPCs without root.

**Comment by ro-joshi** [comment]
Thanks for the response Jin. I am using `caper server`, and ` run_mysql_server_singularity.sh` for all the pipelines I'm running. Both the cromwell server and the mysql db server are running in a separate long-running slurm job and they are running fine without memory issues. Subsequent jobs/pipelines ran fine through cromwell following the memory-problem pipelines described above.

**Comment by nicolerg** [comment]
Was this supposed to be fixed in the latest release or should we still use MySQL when running pipelines in parallel?

**Comment by leepc12** [comment]
@nicolerg: both `file` (old default) DB and `in-memory` are unstable. They have a memory problem. This might not be a problem if you just `caper run` each sample (so each workflow has its own file DB). But if you want to `caper server` then yes you need to use MySQL DB.

**Comment by nicolerg** [comment]
Back to the original post in this issue, child jobs still keep running after a core dump kills the parent process. This is with `caper run` (caper v 0.6.0, pipeline v 1.5.3). From your previous comments, you said it looks like a Cromwell issue? This issue can be closed if that is the case.

**Comment by leepc12** [comment]
Did you use Conda? If you used Singularity, let's try with Conda. Conda works more stable with pipeline now. Please post your conf `~/.caper/default.conf` and a full log of `caper run` command and anything can be helpful for debugging.

**Comment by nicolerg** [comment]
I used Conda with `caper run`: `sbatch -A ${account} -J ${JOB_NAME} --export=ALL --mem 2G -t 4-0 --wrap "caper run ${wdl} -i ${INPUT} "

The parent job died, but a child process is still running - `cromwell_51e9df16_macs2_signal_track_pooled`

Here is my caper config file:
```
$ cat ~/.caper/default.conf
backend=slurm
slurm-account=prj_motrpac

tmp-dir=/projects/motrpac/tmp
```
I attached the SLURM log file. 

If I log into the node that's still running one the child jobs, I see a few processes related to this parent job in `htop`:
<img width="1440" alt="Screen Shot 2019-11-14 at 4 38 23 PM" src="https://user-images.githubusercontent.com/32148717/68907680-810fa480-06fd-11ea-9889-85c55835a730.png">
[slurm-12421778.out.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3849289/slurm-12421778.out.txt)

This issue - core dump that kills the parent job but leaves child jobs running - has happened at different places in the pipeline. Previously, it happened in the `call-align` step. 

The workflow log, the core dump file, and the output of `for file in $(find -name 'stderr'); do echo $file; cat $file; echo; done` are in the attached folder. Let me know if anything else would be helpful. 
[issue170.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3849299/issue170.zip)

**Comment by nicolerg** [comment]
Child processes continuing to run aside, these core dumps keep happening with the same couple of pipelines, and I'm having a hard time figuring out why. Again, it's a pretty nondescript bus error. This only seems to be happening with pipelines that have 5 replicates. At first I thought it was a memory error, but I tried to replicate it in the ENCODE test sample by asking for too little memory for `call-align`, and that didn't reproduce the result. 

Here are non-file-exists errors in `stderr`:
```
./call-align/shard-4/execution/stderr
/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-align/shard-4/execution/script: line 71: 92423 Bus error               (core dumped) python3 $(which encode_task_bowtie2.py) /projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-align/shard-4/inputs/1442233120/Rattus_norvegicus.Rnor_6.0.dna.toplevel.standardized.fa.tar R1/*.fastq.gz R2/*.fastq.gz --paired-end --multimapping 4 --nth 4
ln: failed to access ‘/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-align/shard-4/execution/*.bai’: No such file or directory
ln: failed to access ‘/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-align/shard-4/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-align/shard-4/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-align/shard-4/execution/*.read_length.txt’: No such file or directory

./call-macs2_signal_track_pooled/execution/stderr
/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-macs2_signal_track_pooled/execution/script: line 28: 21192 Bus error               (core dumped) python3 $(which encode_task_macs2_signal_track_atac.py) /projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-macs2_signal_track_pooled/inputs/-514581712/90133015504_R1.trim.merged.nodup.no_chrM_MT.tn5.pooled.tagAlign.gz --gensz 2870184193 --chrsz /projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-macs2_signal_track_pooled/inputs/-2060089936/motrpac_rn6.chrom.sizes --pval-thresh 0.01 --smooth-win 73
ln: failed to access ‘/projects/motrpac/PASS1A/ATAC/NOVASEQ_BATCH1/output/atac/edc69631-e2bf-48d9-9529-d350aa87f43c/call-macs2_signal_track_pooled/execution/*.pval.signal.bigwig’: No such file or directory

./call-macs2_signal_track_pooled/attempt-2/execution/stderr
slurmstepd: error: *** JOB 12448585 ON dper730xd-srcf-d16-01 CANCELLED AT 2019-11-15T14:12:45 DUE TO TIME LIMIT ***
```

So it looks like there was a timeout error during `call-macs2_signal_track_pooled`. Could that be causing the core dump? What causes these steps to go into multiple attempts, e.g. `call-macs2_signal_track_pooled/attempt-2/execution`?

Also, can you clarify the best way to resume a workflow when using Conda? I read the Caper README about using a MySQL database, but is that only for Singularity or Docker?

Thank you!

**Comment by leepc12** [comment]
Please try with increased walltime for that failing task `macs2_signal_track_pooled`. `atac.macs2_signal_track_pooled_time_hr`  in your input JSON. Check defaults in `input.md` documentation.

The latest Caper runs without metadata DB (hence, no call-caching) unless `db` in your default conf is explicitly set as `file` or `mysql`.
```
db=file
```

Those helper shell scripts work with containers only. There is no way to run MySQL with Docker or locally on HPCs like SCG and Sherlock. But both clusters have Singularity. Use that Singularity shell script to run your own MySQL server and add
```
db=mysql
# define other MySQL parameters if you changed the default port.
mysql-db-port=
```

BTW how big is your fastq? Can you get more info for that failed macs2 signal pooled job? Something like `sacct -j JOB_ID`?

**Comment by leepc12** [comment]
Can I (leepc12@stanford)get access to your output directory on SCG?

**Comment by nicolerg** [comment]
Thanks, I will add `db=file` to my caper config file. 

I can increase the walltime, but is it expected for that step to take more than 24 hours?

Here are the FASTQ file sizes:
```
-rw-r--r-- 3 nicolerg 3.3G Oct 19 16:01 90133015504_R1.fastq.gz
-rw-r--r-- 3 nicolerg 3.4G Oct 19 16:02 90133015504_R2.fastq.gz
-rw-r--r-- 3 nicolerg 3.1G Oct 19 15:31 90007015504_R1.fastq.gz
-rw-r--r-- 3 nicolerg 3.2G Oct 19 15:31 90007015504_R2.fastq.gz
-rw-r--r-- 3 nicolerg 4.6G Oct 19 15:54 90115015504_R1.fastq.gz
-rw-r--r-- 3 nicolerg 4.7G Oct 19 15:54 90115015504_R2.fastq.gz
-rw-r--r-- 3 nicolerg 3.3G Oct 19 15:46 90043015504_R1.fastq.gz
-rw-r--r-- 3 nicolerg 3.4G Oct 19 15:46 90043015504_R2.fastq.gz
-rw-r--r-- 4 nicolerg 3.2G Oct 19 15:38 90025015504_R1.fastq.gz
-rw-r--r-- 4 nicolerg 3.2G Oct 19 15:38 90025015504_R2.fastq.gz
```

Here are some of the `sacct` stats for that failed job:
![Screen Shot 2019-11-15 at 5 30 13 PM](https://user-images.githubusercontent.com/32148717/68985748-ae2b8800-07cd-11ea-83d8-3a325d983ba7.png)

I am copying the outputs to a public folder. I'll share the path with you.

**Comment by leepc12** [comment]
Yes it can take long. Are they technical replicates? How many replicates in the pipeline (in your input JSON)?

**Comment by nicolerg** [comment]
There are 5 biological replicates in these pipelines that are failing. I bumped `atac.macs2_signal_track_pooled_time_hr` up to 36 and will see if that works. 

Copying the outputs to the public folder failed due to space restrictions. I will retry after getting the space allocation bumped up.

**Comment by leepc12** [comment]
Closing this due to long inactivity.
