### ISSUE TITLE
detect_adapter.py fails for non-gzipped files

### ISSUE THREAD

**Issue by ro-joshi** [ENCODE-DCC/atac-seq-pipeline#175]
**OS/Platform and dependencies**
- OS or Platform: SCG cluster
- Conda version: conda 4.7.12
- Caper version 0.5.1

**Describe the bug**
detect_adapter.py fails if input fastq files are not gzipped, with error 
```
Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_task_trim_adapter.py", line 232, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_task_trim_adapter.py", line 175, in main
    args.adapters[i][0] = detect_most_likely_adapter(fastqs[0])
  File "/software/atac-seq-pipeline/src/detect_adapter.py", line 49, in detect_most_likely_adapter
    fname)
  File "/software/atac-seq-pipeline/src/detect_adapter.py", line 36, in detect_adapters_and_cnts
    if line.find(adapters[key]) > -1:
TypeError: must be str, not bytes. 
```

The issue is that gzip.open() by default returns bytes; open() by default returns text.

Suggest changing ```
adapters = {
    'Illumina': b'AGATCGGAAGAGC',
    'Nextera ': b'CTGTCTCTTATA',
    'smallRNA': b'TGGAATTCTCGG'
}

def open_gz(fname):
    return gzip.open(fname) if fname.endswith('.gz') else open(fname, 'r')
```
to 
```
adapters = {
    'Illumina': b'AGATCGGAAGAGC',
    'Nextera ': b'CTGTCTCTTATA',
    'smallRNA': b'TGGAATTCTCGG'
}

def open_gz(fname):
    return gzip.open(fname) if fname.endswith('.gz') else open(fname, 'rb')
``` 
OR 
```
adapters = {
    'Illumina': 'AGATCGGAAGAGC',
    'Nextera ': 'CTGTCTCTTATA',
    'smallRNA':b'TGGAATTCTCGG'
}

def open_gz(fname):
    return gzip.open(fname, 'rt') if fname.endswith('.gz') else open(fname, 'r')
```

**Comment by leepc12** [comment]
This will be fixed in the next release
