### ISSUE TITLE
Conda vs Singularity

### ISSUE THREAD

**Issue by guma44** [ENCODE-DCC/atac-seq-pipeline#179]
Hi,
Some time ago there was a warning in README:

> **WARNING**: We no longer recommend Conda for resolving dependencies and plan to phase out Conda support. Instead we recommend using Docker or Singularity. You can install Singularity and use it for this pipeline with Caper (by adding `--singularity` to command line arguments).

However, it disappeared and an opposite statement appeared. We are currently testing Singularity just because of this (we use Conda now). Could I ask what happened that the politics changed? And what is the future of Conda/Singularity? I am asking because this is also important for us.

**Comment by leepc12** [comment]
Conda was not stable at that time. Conda >= 4.7 removed some conflicting free channels from the list of default channels so it looks very stable now while stability of Singularity varies depending on the configuration of system and Singularity itself.

**Comment by guma44** [comment]
Thanks a lot that explains everything.
