### ISSUE TITLE
building hg38 genome

### ISSUE THREAD

**Issue by grrompala** [ENCODE-DCC/atac-seq-pipeline#180]
Hi,

Previously had no issues building the hg38 genome with the provided builder. 

Now running an issue where it abruptly stops at the same point. Below is the tail end of the output.
Basically it stops at this point **tar: unrecognized option '--sort=name'**  which I don't know how to interpret. I am running the builder with encode-atac-seq-pipeline activated.

Any insight would be greatly appreciated. Thanks!
  

Sorting block of length 248290277 for bucket 13
  (Using difference cover)
  Sorting block time: 00:01:17
Returning block of 268462555 for bucket 12
Getting block 14 of 15
  Reserving size (275144667) for bucket 14
  Calculating Z arrays for bucket 14
  Entering block accumulator loop for bucket 14:
  bucket 14: 10%
  bucket 14: 20%
  bucket 14: 30%
  bucket 14: 40%
  bucket 14: 50%
  bucket 14: 60%
  bucket 14: 70%
  bucket 14: 80%
  Sorting block time: 00:01:12
Returning block of 248290278 for bucket 13
  bucket 14: 90%
Getting block 15 of 15
  Reserving size (275144667) for bucket 15
  Calculating Z arrays for bucket 15
  Entering block accumulator loop for bucket 15:
  bucket 14: 100%
  Sorting block of length 252608371 for bucket 14
  (Using difference cover)
  bucket 15: 10%
  bucket 15: 20%
  bucket 15: 30%
  bucket 15: 40%
  bucket 15: 50%
  bucket 15: 60%
  bucket 15: 70%
  bucket 15: 80%
  bucket 15: 90%
  bucket 15: 100%
  Sorting block of length 76591070 for bucket 15
  (Using difference cover)
  Sorting block time: 00:00:22
Returning block of 76591071 for bucket 15
  Sorting block time: 00:01:13
Returning block of 252608372 for bucket 14
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 866420001
fchr[G]: 1465103434
fchr[T]: 2065958374
fchr[$]: 2934876451
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 982525150 bytes to primary EBWT file: GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.rev.1.bt2
Wrote 733719120 bytes to secondary EBWT file: GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 2934876451
    bwtLen: 2934876452
    sz: 733719113
    bwtSz: 733719113
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 183429779
    offsSz: 733719116
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 15285815
    numLines: 15285815
    ebwtTotLen: 978292160
    ebwtTotSz: 978292160
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:19:08
tar: unrecognized option '--sort=name'
Try `tar --help' or `tar --usage' for more information.

**Comment by leepc12** [comment]
What is your OS and version? Does `tar --help` tell you any about `--sort` parmeter?

**Comment by grrompala** [comment]
this is my school's unix-based cluster. tar --help doesn't show me any --sort parameters

**Comment by leepc12** [comment]
Edit the shell script and remove `--sort=name` from the command line.

**Comment by grrompala** [comment]
I eliminated all instances of --sort=name from the tar command and I get this error now:
tar: root\:0: Invalid owner
tar: Error is not recoverable: exiting now

In context:
Returning block of 76591071 for bucket 15
  Sorting block time: 00:01:17
Returning block of 252608372 for bucket 14
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 866420001
fchr[G]: 1465103434
fchr[T]: 2065958374
fchr[$]: 2934876451
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 982525150 bytes to primary EBWT file: GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.rev.1.bt2
Wrote 733719120 bytes to secondary EBWT file: GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 2934876451
    bwtLen: 2934876452
    sz: 733719113
    bwtSz: 733719113
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 183429779
    offsSz: 733719116
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 15285815
    numLines: 15285815
    ebwtTotLen: 978292160
    ebwtTotSz: 978292160
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:18:54
tar: root\:0: Invalid owner
tar: Error is not recoverable: exiting now

**Comment by leepc12** [comment]
Remove all TAR parameters `--sort=name --owner=root:0 --group=root:0 --mtime="UTC 2019-01-01"` and try again.

**Comment by grrompala** [comment]
This works great. Thanks! Unfortunately, just brought me to the next problem...

**Comment by nicolerg** [comment]
I had the same problem trying to build a custom genome database `build_genome_data.sh` on SCG (CentOS Linux 7). Removing the parameters worked. `download_genome_data.sh` doesn't have those `tar` parameters and ran fine for hg38 (1.5.4).

**Comment by nicolerg** [comment]
@leepc12 would it be reasonable to remove those `tar` parameters in the next patch?

**Comment by leepc12** [comment]
I will add both GRE `tar` and `grep` to the Conda environment.

**Comment by leepc12** [comment]
Fixed.
