### ISSUE TITLE
Conflict when initiating pipelines in parallel

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#185]
I initiated pipelines for ~20 samples in a loop. 10 of the pipelines failed almost immediately with this error:
```
Traceback (most recent call last):
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1266, in main
    c.run()
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 213, in run
    self.__download_cromwell_jar(), 'run',
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 590, in __download_cromwell_jar
    return cu.copy(target_uri=path)
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 469, in copy
    cu_lock.rm(quiet=True)
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 846, in rm
    os.remove(self._uri)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nicolerg/.caper/cromwell_jar/cromwell-47.jar.lock'
```
It looks like this has something to do with starting multiple pipelines at the same time. I can add a `sleep` in between commands, but can this be otherwise fixed? I'm not sure what an appropriate wait time is since the jobs might not get initiated immediately after submission to the job queue. 

**OS/Platform and dependencies**
- OS or Platform: SCG
- Caper version 0.6.0
- pipeline version 1.5.3

**Comment by leepc12** [comment]
This is Caper's issue.

This happens only when you don't have a downloaded `cromwell.jar` file in your cache directory (`~/.caper/cromwell_jar/`). Once it's downloaded you will not see this error.

10 pipelines were trying to download a `cromwell.jar` and it took > 30 seconds. Caper waits for 30 seconds until that spin lock file disappears.

I am thinking about refactoring `cURL` part (download files from URL) of Caper and will start working on it soon.

**Comment by nicolerg** [comment]
Thank you, would it be an easy fix to add that to Caper's documentation? i.e. download the newest version of `cromwell.jar` and move it to `~/.caper`? Adding a 30-second wait did resolve the issue.

**Comment by akundaje** [comment]
Yes good idea.

Jin - Lets add a temporary fix by making it very clear in the documentation.

-A

**Comment by leepc12** [comment]
@akundaje @nicolerg thanks for suggestions, but this turns out to be a race condition.

Let me correct the 30 second thing first. Caper checks if the lock file is still there every 30 second up to 100 times. So Caper should be able to wait for an hour until downloading is done. That lock file was deleted by another process so this is a race condition.

Using a spin lock file is always vulnerable to race condition. Let me think more about this... I will refactor the downloading part of Caper soon.

**Comment by leepc12** [comment]
I am closing this since it's Caper's issue.

Let's continue our discussion here.
https://github.com/ENCODE-DCC/caper/issues/34
