### ISSUE TITLE
Multimapping threshold off-by-one

### ISSUE THREAD

**Issue by strattan** [ENCODE-DCC/atac-seq-pipeline#186]
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/85c840f0a24d22c1454ac4b1351706ca788a085d/src/assign_multimappers.py#L58

The >= means we discard sets that contain the threshold value or more multimapping positions.  I think that is inconsistent with the way the multimapping workflow parameter is interpreted.  For a multimapping workflow parameter value n we invoke bowtie with -k n+1 so that we can distinguish between reads that multimap exactly n times from reads that multimap more than n times.  For those that multimap exactly n times, we know we have the best-scoring mapping in that set because bowtie gave up before reaching our threshold.  So I think in assign_multimappers we want to allow sets that contain exactly n but discard sets > n.

**Comment by akundaje** [comment]
Seth,

One thing - is it 0 based on 1 based indexing of number of alignments?

Anshul

**Comment by vervacity** [comment]
Hey Seth, understood - yes according to that definition and set up, we should change it from `>=` to `>`. Agree with changing it.

**Comment by leepc12** [comment]
Change the operator >= to >. This will be applied to the next release.

**Comment by leepc12** [comment]
Fixed.
