### ISSUE TITLE
Does bowtie2 report the best mapping as the primary?

### ISSUE THREAD

**Issue by strattan** [ENCODE-DCC/atac-seq-pipeline#187]
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/85c840f0a24d22c1454ac4b1351706ca788a085d/src/encode_task_filter.py#L70

In the previous line we've ensured that the best-scoring mapping is a member of the set of multi-mapping positions for each multi-mapping read.  Does bowtie2 guarantee that the best-scoring mapping it finds is marked as the primary?  That is the way I interpret this from the bowtie2 docs:

> It reports all alignments found, in descending order by alignment score. ... Each reported read or pair alignment beyond the first has the SAM ‘secondary’ bit ... Bowtie 2 does not “find” alignments in any specific order, so for reads that have more than N distinct, valid alignments, Bowtie 2 does not guarantee that the N alignments reported are the best possible in terms of alignment score.

But I'm hoping we can clarify for the record that we're sure that the best-scoring read is marked as the primary.

**Comment by vervacity** [comment]
Seth, my reading of the docs (http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#k-mode-search-for-one-or-more-alignments-report-each) is that:

1) bowtie2 will find up to N distinct valid alignments in any order. This means the best possible may or may not be found, but there will be N
2) those N alignments get ordered before being reported. As such, the first one (best score) should be marked primary and all the others should be marked secondary.

In this set up, the best scoring mapping should also be the primary. Let me know if I missed anything in the docs/my interpretation!

**Comment by leepc12** [comment]
Closing this.
