### ISSUE TITLE
Adjust qc2tsv output?

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#188]
Would it be possible to change the headings in the output of `qc2tsv` to make it more clear what each column is? Right now it looks like this:
![Screen Shot 2019-11-13 at 10 40 50 AM](https://user-images.githubusercontent.com/32148717/68793757-699fc100-0602-11ea-80fb-515319a3891c.png)
The only way for me to interpret each column right now is to open it in Excel and fill in each header/subheader across columns:
![Screen Shot 2019-11-13 at 10 42 40 AM](https://user-images.githubusercontent.com/32148717/68793827-93f17e80-0602-11ea-8305-8f3459728491.png)
Alternatively, maybe the most interpretable version (or at least language-friendly), each column could be named with all of the levels collapsed into one variable name, e.g. `peak_stat.peak_region_size.overlap_opt.75_pct`.

When the pipeline is run with single samples, the rows are also staggered, e.g.:
![Screen Shot 2019-11-13 at 10 48 00 AM](https://user-images.githubusercontent.com/32148717/68794072-2003a600-0603-11ea-8b4c-df86657725b4.png)

But `qc2tsv` is still really helpful to compile metrics across a batch of samples as-is! Thanks for incorporating this feature!

**Comment by akundaje** [comment]
Agree with these suggestions

**Comment by leepc12** [comment]
Thanks for your suggestion. `qc2tsv` was designed for making a spreadsheet for Google Sheets or Excel.

1) Collapsing header rows (using . notation)
I will parameterize this. A flag `--collapse-header` will be added.

2) Staggering
It's actually not staggering. `qc.json` has 1) quality metrics for the whole experiment and 2) quality metrics for each bio replicate. So number of rows for a single workflow is like `1 + num_rep`. If that looks staggered than I will combine two rows 1) and rep1 of 2).

**Comment by nicolerg** [comment]
(1) would be great!

For (2), thanks for the clarification. I think it would make more sense to do what you're suggesting, i.e. combine rows of {whole experiment} and {rep1} since {whole experiment} and {replicate} QC metrics do not overlap, at least with the current column definitions.

**Comment by leepc12** [comment]
Updated `qc2tsv`, See release note for v0.1.2
https://github.com/ENCODE-DCC/qc2tsv/releases/tag/v0.1.2

Closing this.

Please make a new issue on qc2tsv's github repo if you have more to discuss.
