### ISSUE TITLE
atac.align_mito Failed

### ISSUE THREAD

**Issue by Stormsky99** [ENCODE-DCC/atac-seq-pipeline#189]
Hi
When I tried " caper run atac.wdl -i my.json", there was an error :

atac.align_mito Failed. SHARD_IDX=0, RC=None, JOB_ID=10592, RUN_START=2019-11-14T15:12:20.627Z, RUN_END=2019-11-14T15:19:45.756Z, STDOUT=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/89503459-8c4f-49dc-ba5f-7ed68e438cc9/call-align_mito/shard-0/execution/stdout, STDERR=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/89503459-8c4f-49dc-ba5f-7ed68e438cc9/call-align_mito/shard-0/execution/stderr
STDERR_CONTENTS=

atac.align Failed. SHARD_IDX=0, RC=None, JOB_ID=10527, RUN_START=2019-11-14T15:12:14.647Z, RUN_END=2019-11-14T15:44:09.817Z, STDOUT=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/89503459-8c4f-49dc-ba5f-7ed68e438cc9/call-align/shard-0/execution/stdout, STDERR=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/89503459-8c4f-49dc-ba5f-7ed68e438cc9/call-align/shard-0/execution/stderr
STDERR_CONTENTS=

Please, What should I do to solve this problem?
Any comments would be appreciated

Best.
[at_test.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3847506/at_test.json.txt)

**Comment by leepc12** [comment]
Can you post your full `caper run` output log? Do you have enough resource on your system?

**Comment by Stormsky99** [comment]
Hi Jin，
Thank you for comments.

In run.log, it shows "Bad output 'align_mito.bam': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
But I found default.conf is totally empty

Best.

[run.log](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3849462/run.log)
[default.conf.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3849464/default.conf.txt)

**Comment by leepc12** [comment]
Please post contents of this file `/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_tes                                                             t/atac/9b5b4afb-237f-4f47-9c11-a29d78e9431e/call-align_mito/shard-1/execution/*.log`

```
$ cat /home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_tes                                                             t/atac/9b5b4afb-237f-4f47-9c11-a29d78e9431e/call-align_mito/shard-1/execution/*.log
```

**Comment by Stormsky99** [comment]
Here is the call-align_mito.align.log:
4634245 reads; of these:
  4634245 (100.00%) were paired; of these:
    4338567 (93.62%) aligned concordantly 0 times
    295678 (6.38%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    4338567 pairs aligned concordantly 0 times; of these:
      403 (0.01%) aligned discordantly 1 time
    ----
    4338164 pairs aligned 0 times concordantly or discordantly; of these:
      8676328 mates make up the pairs; of these:
        8675081 (99.99%) aligned 0 times
        1247 (0.01%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
6.40% overall alignment rate
[2019080102_R1_val_1.merged.align.log](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3861583/2019080102_R1_val_1.merged.align.log)

**Comment by Stormsky99** [comment]
Hi，Jin

Here is the&nbsp;call-align_mito&nbsp;align.log:
4634245 reads; of these:
4634245 (100.00%) were paired; of these:
4338567 (93.62%) aligned concordantly 0 times
295678 (6.38%) aligned concordantly exactly 1 time
0 (0.00%) aligned concordantly &gt;1 times
----
4338567 pairs aligned concordantly 0 times; of these:
403 (0.01%) aligned discordantly 1 time
----
4338164 pairs aligned 0 times concordantly or discordantly; of these:
8676328 mates make up the pairs; of these:
8675081 (99.99%) aligned 0 times
1247 (0.01%) aligned exactly 1 time
0 (0.00%) aligned &gt;1 times
6.40% overall alignment rate



And this is the&nbsp;call-align&nbsp;align.log:
4634245 reads; of these:
4634245 (100.00%) were paired; of these:
129956 (2.80%) aligned concordantly 0 times
4012356 (86.58%) aligned concordantly exactly 1 time
491933 (10.62%) aligned concordantly &gt;1 times
----
129956 pairs aligned concordantly 0 times; of these:
7260 (5.59%) aligned discordantly 1 time
----
122696 pairs aligned 0 times concordantly or discordantly; of these:
245392 mates make up the pairs; of these:
207027 (84.37%) aligned 0 times
30795 (12.55%) aligned exactly 1 time
7570 (3.08%) aligned &gt;1 times
97.77% overall alignment rate



And the bam files already existed, it looks like alignment worked.
So I have no idea that why atac-pipeline stopped



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jin Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 上午7:23
收件人:&nbsp;"ENCODE-DCC/atac-seq-pipeline"<atac-seq-pipeline@noreply.github.com&gt;;
抄送:&nbsp;"董宇昊"<446554759@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ENCODE-DCC/atac-seq-pipeline] atac.align_mito Failed (#189)




Please post contents of this file /home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_tes                                                             t/atac/9b5b4afb-237f-4f47-9c11-a29d78e9431e/call-align_mito/shard-1/execution/*.log
 $ cat /home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_tes                                                             t/atac/9b5b4afb-237f-4f47-9c11-a29d78e9431e/call-align_mito/shard-1/execution/*.log

**Comment by leepc12** [comment]
Please read Caper's README and do `caper init` according to your platform.

`cd` to the failed task directory.
```
$ cd /home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/9b5b4afb-237f-4f47-9c11-a29d78e9431e/call-align_mito/shard-0/execution/

$ cat stdout

$ cat stderr

$ cat *.align.log
```

**Comment by Stormsky99** [comment]
After Initialization, I run it again, but it still shows "atac.align_mito Failed".
There is the stdout and align.log, stderr is empty.

5109863 reads; of these:
  5109863 (100.00%) were paired; of these:
    4860908 (95.13%) aligned concordantly 0 times
    248955 (4.87%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    4860908 pairs aligned concordantly 0 times; of these:
      340 (0.01%) aligned discordantly 1 time
    ----
    4860568 pairs aligned 0 times concordantly or discordantly; of these:
      9721136 mates make up the pairs; of these:
        9720150 (99.99%) aligned 0 times
        986 (0.01%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
4.89% overall alignment rate
[stdout.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3889913/stdout.txt)

**Comment by leepc12** [comment]
I think pipeline failed at here.
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/atac.wdl#L1130

Activate pipeline's conda env and 
```
$ conda activate encode-atac-seq-pipeline
$ which encode_task_post_align.py
$ cat $(which encode_task_post_align.py)
$ head -n20 [YOUR_PIPELINE_GIT_DIR]/atac.wdl
```

What is your pipeline version? and did you upgrade it from older versions? if so did you update the conda environment (`scripts/update_conda_env.sh`) as mentioned in a release note?

**Comment by Stormsky99** [comment]
Hi, Jin
Thank you for your patience.
However, after I updated the conda environment, it showed same error. I downloaded the pipeline at 31 Oct, and now My pipeline version is v1.5.1.

[atac.wdl-head.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3895246/atac.wdl-head.txt)

[encode_task_post_align.py.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3895245/encode_task_post_align.py.txt)

**Comment by leepc12** [comment]
Please update your pipeline to the latest (v1.5.4). You may need to re-install pipeline's conda env.

**Comment by Stormsky99** [comment]
Hi, Jin
I updated my pipeline, and reinstall the conda env, but, it failed again...

# ENCODE ATAC-Seq/DNase-Seq pipeline
# Author: Jin Lee (leepc12@gmail.com)
#CAPER docker quay.io/encode-dcc/atac-seq-pipeline:v1.5.4
#CAPER singularity docker://quay.io/encode-dcc/atac-seq-pipeline:v1.5.4
#CROO out_def https://storage.googleapis.com/encode-pipeline-output-definition/atac.croo.json


atac.align_mito Failed. SHARD_IDX=0, RC=None, JOB_ID=14915, RUN_START=2019-11-28T05:58:28.020Z, RUN_END=2019-11-28T06:07:31.053Z, STDOUT=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align_mito/shard-0/execution/stdout, STDERR=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align_mito/shard-0/execution/stderr
STDERR_CONTENTS=

atac.align_mito Failed. SHARD_IDX=1, RC=None, JOB_ID=14928, RUN_START=2019-11-28T05:58:30.021Z, RUN_END=2019-11-28T06:07:46.528Z, STDOUT=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align_mito/shard-1/execution/stdout, STDERR=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align_mito/shard-1/execution/stderr
STDERR_CONTENTS=

atac.align Failed. SHARD_IDX=0, RC=None, JOB_ID=14897, RUN_START=2019-11-28T05:58:26.020Z, RUN_END=2019-11-28T06:30:31.380Z, STDOUT=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align/shard-0/execution/stdout, STDERR=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align/shard-0/execution/stderr
STDERR_CONTENTS=

atac.align Failed. SHARD_IDX=1, RC=None, JOB_ID=14879, RUN_START=2019-11-28T05:58:24.079Z, RUN_END=2019-11-28T06:29:54.770Z, STDOUT=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align/shard-1/execution/stdout, STDERR=/home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/call-align/shard-1/execution/stderr
STDERR_CONTENTS=

[Caper] run:  1 f2231b86-b3c0-47c9-8289-da96d8e02858 /home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858/metadata.json

**Comment by leepc12** [comment]
Please post your input JSON and contents of your genome TSV file (`"atac.genome_tsv"`) in it.

**Comment by Stormsky99** [comment]
HI, Jin
Here are my inupt JSON and genome.tsv.
Best.

[at_test.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3914223/at_test.json.txt)
[mm10.tsv.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3914224/mm10.tsv.txt)

**Comment by leepc12** [comment]
Please go to failed workflow's output directory and run the following to make a TAR ball of all logs. And then upload that tar.gz here.

```
$ cd /home/users/yhdong/annuo/ZY_ATACseq_lane_20190801/caper_test/atac/f2231b86-b3c0-47c9-8289-da96d8e02858
$ find -name stdout -or -name stderr -or -name *.log -or -name *.qc -or -name *.txt | tar -zcf debug.tar.gz -T -
```

**Comment by Stormsky99** [comment]
Hi, Jin
Here is the tar ball of all logs.
Best.
[debug.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3919438/debug.tar.gz)

**Comment by leepc12** [comment]
I couldn't figure out the problem. All `align` tasks ran successfully but Cromwell failed to catch (glob) outputs. I think it can be an OS or file system related problem...

What is your OS and file system (NFS or physically mounted disk or special fs)? What are resources (cpu, memory, ...) on your system?

Please try with Singularity/Docker instead of Conda or try on other platforms.

**Comment by Stormsky99** [comment]
Hi, Jin
Thanks for your help and patience, it took you a lot of time.
I failed at CenOS system（Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 GNU/Linux）, but now when I tried it on Ubuntu（Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 GNU/Linux）, it worked well......Space should be enough, maybe it's the system problem...
[df-h.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3924760/df-h.txt)

Can I just use the bam files in the "call-align/shard-0/excution/" to peakcalling as:
macs2 callpeak -t t.bam -c c.bam -f BAM --shift -100 --extsize --nomodel -B -g mm -n xx --outdir xxx

Would it be same as your pipeline's results ?

Best.

**Comment by leepc12** [comment]
It's weird. I ran >=100 pipelines on HPC with CentOS and it worked fine. Are you working on a special file system?

Please refer to this for the actual MACS2 command line (`cmd0`). There is also a post processing (`cmd1` and `cmd2`) of raw narrowPeak.gz from MACS2.
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/src/encode_task_macs2_atac.py#L58

**Comment by Stormsky99** [comment]
Thank you, Jin
Actually I don't know, it's another lab's server, and I have no Administrator rights...Maybe I should reinstall Cromwell or Java?
Best.

**Comment by leepc12** [comment]
Did you use cromwell-47 (Caper downloads and uses it by default)?

No, Java is not the problem here.

Can you run it on a different file system? If you ran it on your home directory, try on your server's scratch directory. Check all mounted disks with the following command.
```
$ df -h
```

**Comment by Stormsky99** [comment]
Hi, Jin
Sorry, I can't change other disk, I have no Administrator rights, and my whole directory shows same "df -h".


I installed cromwell-47, But when I activate pipeline environment, it shows cromwell command not found...
Could it be the problem?


Best.
------------------ Original ------------------

**Comment by Stormsky99** [comment]
Hi, Jin
Sorry, my server is with PBS cluster engine actually,...
Before, firstly, I connected to node1, and activate environment, then initialized as "**caper init local**", and then ran the pipline as "caper run wdl -i json", and it showed "atac.align_mito Failed".
Well, today I connected to node1, and initialized as "**caper init pbs**", next it showed a different error..."atac.read_genome_tsv Failed"

Sorry, Jin. Did I keep initializing wrong platform ?
And how pipeline can read genome.tsv successfully when it was initialized as local, but failed as pbs?

Sorry to keep bothering you.

Best.

**Comment by leepc12** [comment]
Initialize it with `caper init pbs`.
You should not use a local mode.
You should not connect to node1.

See this instruction. It's for SGE but PBS should work similarly.
https://github.com/ENCODE-DCC/caper#running-pipelines-on-sge-clusters

**ON A LOGIN NODE**, Use this command line instead for running a pipeline. It's like submitting caper itself to the cluster engine and caper will `qsub` its subtasks. Caper is another job manager.
```
echo "caper run [WDL] -i [INPUT_JSON]" | qsub -V -N [JOB_NAME] -lwalltime=144:00:00
```

**Comment by Stormsky99** [comment]
Hi, Jin
Thank you, and Sorry for Initializing wrong platform before...
But on the login node, after initialization, I ran as: echo "caper run [WDL] -i [INPUT_JSON]" | qsub -V -N [JOB_NAME] -lwalltime=144:00:00", it reported: "qsub: submit error (Bad UID for job execution MSG=ruserok failed validating yhdong/yhdong from node4)", and be unable to start job.
Then I ran "caper run [WDL] -i [INPUT_JSON]" derectly on the login node, however, it won't start job either.
Matbe the command can not apply on pbs or there is something wrong on pbs server?

Have a nice day
Best.

**Comment by leepc12** [comment]
I think your PBS engine requires a username explicitly. Run the following:
```
echo "caper run [WDL] -i [INPUT_JSON] --pbs-extra-param \" -u [YOUR_USER_NAME]\"" | qsub -u [YOUR_USER_NAME] -V -N -lwalltime=144:00:00
```
The basic idea here is to let Caper pass an extra parameter set to the engine, which is ` -u [YOUR_USER_NAME]`. Make sure that you have a whitespace before ` -u`.

**Comment by Stormsky99** [comment]
Hi, Jin
Thank you for advice.
I ran: echo "caper run ~/software/atac-seq-pipeline-master/atac.wdl -i ~/annuo/ZY_ATACseq_lane_20190801/caper_test/at_test.json --pbs-extra-param \" -u yhdong\""  | qsub -u yhdong -V -N caper -l walltime=144:00:00
But it showed same error in stderr.submit file: "qsub: submit error (Bad UID for job execution MSG=ruserok failed validating yhdong/yhdong from node4)"
It seems like, the server can not submit jobs on calculation nodes. And Caper running on calculation nodes can not qsub its subtasks.
Well, when I ran caper on the login node, it just sticked in:
2019-12-09 19:25:49,301 cromwell-system-akka.dispatchers.backend-dispatcher-105 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(b3227c52)atac.read_genome_tsv:NA:1]: executing: qstat 45620
Over and over again...
Could you please tell me that is there something else I should change in commands?

Have a nice day
Best.

**Comment by leepc12** [comment]
Did you run it on login nodes like the following?
```
caper run ~/software/atac-seq-pipeline-master/atac.wdl -i ~/annuo/ZY_ATACseq_lane_20190801/caper_test/at_test.json --pbs-extra-param " -u yhdong"
```

**Comment by Stormsky99** [comment]
Hi, Jin
Yes, and I tried both commands with and without --pbs-extra-param " -u yhdong", and it reported same log.
It sticked in : 2019-12-10 10:29:23,847 cromwell-system-akka.dispatchers.backend-dispatcher-132 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(ea4f65f5)atac.read_genome_tsv:NA:1]: executing: qstat 45649
So I have to cancel it with Ctrl+C
Did it work successfully ? Maybe I should just wait enough long time?

[log.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3942769/log.txt)

Best.

**Comment by leepc12** [comment]
If that toy problem takes so long then something is definitely wrong. Can you get any PBS log (or anything helpful) for that job 45620?

**Comment by Stormsky99** [comment]
Hi, Jin
I ran it again, and used qstat -f jobID to get some information.

Have a nice day


Best.

[qstat.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3944765/qstat.txt)
[run_log.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3944766/run_log.txt)

**Comment by leepc12** [comment]
When you `qsub` a small job, does it start immediately? I think the failed task `read_genome_tsv` were just queued for waiting (for 30 minutes for your failed job) to be run? Please figure out the reason why that job `45620` failed.

**Comment by Stormsky99** [comment]
Hi, Jin
Apologies for the delayed reply.
I still cannot figure out why caper jobs failed while Other jobs are working correctly.
Thank you for your patience, I'm still a noob in bioinfo. Maybe it's just my pbs server setting is not appropriate for caper jobs and I have no Administrator rights to change it. So I would follow your pipeline manually.
Anyway, Thank you again for your advice, it helps a lot.
Have a nice day

Best.
