### ISSUE TITLE
pipeline fails at call-filter step

### ISSUE THREAD

**Issue by mkdegorter** [ENCODE-DCC/atac-seq-pipeline#19]
I am experiencing an issue with the call-filter step. The pipeline fails with the following stderr:

Traceback (most recent call last):
  File "/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src/encode_filter.py", line 392, in <module>
    main()
  File "/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src/encode_filter.py", line 319, in main
    filt_bam, args.out_dir)
  File "/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src/encode_filter.py", line 176, in mark_dup_picard
    run_shell_cmd(cmd)
  File "/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process
ln: failed to access ‘*.flagstat.qc’: No such file or directory
ln: failed to access ‘*.dup.qc’: No such file or directory
mkdir: cannot create directory ‘/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/cromwell-executions/atac/2ebc8ee7-ecae-441c-9df5-82898ae59666/call-filter/shard-0/execution/glob-37a62
59cc0c1dae299a7866489dff0bd’: File exists
ln: failed to create hard link ‘/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/cromwell-executions/atac/2ebc8ee7-ecae-441c-9df5-82898ae59666/call-filter/shard-0/execution/glob-37a62
59cc0c1dae299a7866489dff0bd/null’: File exists
ln: failed to access ‘*.pbc.qc’: No such file or directory
mkdir: cannot create directory ‘/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/cromwell-executions/atac/2ebc8ee7-ecae-441c-9df5-82898ae59666/call-filter/shard-0/execution/glob-37a62
59cc0c1dae299a7866489dff0bd’: File exists
ln: failed to create hard link ‘/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/cromwell-executions/atac/2ebc8ee7-ecae-441c-9df5-82898ae59666/call-filter/shard-0/execution/glob-37a62
59cc0c1dae299a7866489dff0bd/null’: File exists
ln: failed to access ‘*.mito_dup.txt’: No such file or directory

And stdout:
[2018-07-10 20:47:57,293 INFO] ['/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src/encode_filter.py', '/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/cromwell-executions/atac/2ebc8
ee7-ecae-441c-9df5-82898ae59666/call-filter/shard-0/inputs/-4793129/SCS47_merge_R1.trim.merged.bam', '--paired-end', '--multimapping', '4', '--dup-marker', 'picard', '--mapq-thresh'
, '30']
[2018-07-10 20:47:57,294 INFO] Initializing and making output directory...
[2018-07-10 20:47:57,294 INFO] Removing unmapped/low-quality reads...
[2018-07-10 20:47:57,299 INFO] run_shell_cmd: PID=128254, CMD=samtools view -F 524 -f 2 -u /labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/cromwell-executions/atac/2ebc8ee7-ecae-441c
-9df5-82898ae59666/call-filter/shard-0/inputs/-4793129/SCS47_merge_R1.trim.merged.bam | sambamba sort -n /dev/stdin -o SCS47_merge_R1.trim.merged.tmp_filt.bam -t 1 
[2018-07-10 21:28:04,936 INFO] run_shell_cmd: PID=132462, CMD=samtools view -h SCS47_merge_R1.trim.merged.tmp_filt.bam -@ 1 | $(which assign_multimappers.py) -k 4 --paired-end | sam
tools fixmate -r /dev/stdin SCS47_merge_R1.trim.merged.fixmate.bam
[2018-07-10 21:41:49,466 INFO] run_shell_cmd: PID=133516, CMD=rm -f SCS47_merge_R1.trim.merged.tmp_filt.bam
[2018-07-10 21:41:50,121 INFO] run_shell_cmd: PID=133518, CMD=samtools view -F 1804 -f 2 -u SCS47_merge_R1.trim.merged.fixmate.bam | sambamba sort /dev/stdin -o SCS47_merge_R1.trim.
merged.filt.bam -t 1
[2018-07-10 22:00:35,046 INFO] run_shell_cmd: PID=135008, CMD=rm -f SCS47_merge_R1.trim.merged.fixmate.bam
[2018-07-10 22:00:35,366 INFO] Marking dupes with picard...
[2018-07-10 22:00:35,371 INFO] run_shell_cmd: PID=135010, CMD=java -Xmx4G -jar $(which picard.jar) MarkDuplicates INPUT=SCS47_merge_R1.trim.merged.filt.bam OUTPUT=SCS47_merge_R1.tri
m.merged.dupmark.bam METRICS_FILE=SCS47_merge_R1.trim.merged.dup.qc VALIDATION_STRINGENCY=LENIENT ASSUME_SORTED=true REMOVE_DUPLICATES=false
PID=135010: which: no picard.jar in (/home/mdegorte/miniconda3/envs/encode-atac-seq-pipeline/bin:/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src:/home/mdegorte/miniconda3/bin:/la
bs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src:/home/mdegorte/miniconda3/bin:/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src:/home/mdegorte/miniconda3/bin:/scg/slurm/current/bin
:/scg/slurm/current/sbin:/scg/slurm/utils:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/mdegorte/.bds:/home/mdegorte/.globus-cli-virtualenv/bin:/home
/mdegorte/bin:/home/mdegorte/.bds:/home/mdegorte/.globus-cli-virtualenv/bin:/home/mdegorte/.bds:/home/mdegorte/.globus-cli-virtualenv/bin:/home/mdegorte/bin)
PID=135010: Error: Unable to access jarfile MarkDuplicates
[2018-07-10 22:00:35,399 ERROR] Unknown exception caught. Killing process group 135010...
Traceback (most recent call last):
  File "/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src/encode_common.py", line 224, in run_shell_cmd
    p.returncode, cmd)
CalledProcessError: Command 'java -Xmx4G -jar $(which picard.jar) MarkDuplicates INPUT=SCS47_merge_R1.trim.merged.filt.bam OUTPUT=SCS47_merge_R1.trim.merged.dupmark.bam METRICS_FILE
=SCS47_merge_R1.trim.merged.dup.qc VALIDATION_STRINGENCY=LENIENT ASSUME_SORTED=true REMOVE_DUPLICATES=false' returned non-zero exit status 1

It looks like an issue with picard. Any help would be appreciated. Thanks!

**Comment by computbiolgeek** [comment]
I had a similar issue. My workflow stopped after the call-filter step had finished, which was successful. The weird thing is that the workflow did not continue to the next task. I checked `stderr`, here is what's in it:
_mkdir: cannot create directory ‘/gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd’: File exists
ln: failed to create hard link ‘/gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd/null’: File exists
mkdir: cannot create directory ‘/gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd’: File exists
ln: failed to create hard link ‘/gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd/null’: File exists_

I then `grep`-ed the `script` file, which supposedly was generated by `cromwell`, for `mkdir`, here is what I got:
_mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-3bcbe4e7489c90f75e0523ac6f3a9385
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-6efbc60cb1e0959bab4e467327a9416c
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-e2a84eed5523fc4955f617236139026c
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-1b4794e80f740fd50137e3a948d7ba79
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-85baf8309ae5456274184b199e3a7924
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd
mkdir /gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/78b2472f-b0e8-4594-9ceb-e9c1a109ff4d/call-filter/shard-0/execution/glob-464553c80b37704e09c623386a14d01f_

As can be seen, for some reason, `cromwell` put into the `script` file three copies of the `mkdir` command reported in `stderr`. I'm still trying to figure out why `cromwell` did this. If anyone has any clue, please help. Thanks!

**Comment by leepc12** [comment]
Please try this for more debugging info. It looks like dependency installer didn't work correctly.
```
$ source activate encode-atac-seq-pipeline
$ which picard.jar
```

**Comment by computbiolgeek** [comment]
Thank you very much for the reply. `picard.jar` is indeed in my PATH. `which picard.jar` gives `/ysm-gpfs/pi/xxxx/bl626/opt/picard/picard.jar`.

The pipeline managed to run ever task til finishing the _macs_pr2_ task. In the `stderr` file of this task, I got the same error as before:

_mkdir: cannot create directory ‘/gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/68d2b106-34f7-40fd-9f9c-3f91226ad6d9/call-macs2_pr2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd’: File exists
ln: failed to create hard link ‘/gpfs/slayman/pi/xxxx/bl626/projects/entex/test_pipeline/cromwell-executions/atac/68d2b106-34f7-40fd-9f9c-3f91226ad6d9/call-macs2_pr2/shard-0/execution/glob-37a6259cc0c1dae299a7866489dff0bd/null’: File exists_

To give more info, which hopefully might be helpful to debugging, I submitted the pipeline to our cluster using the following command line:

`$ java -jar -Dconfig.file=./atac_workflow_options.conf -Dbackend.default=slurm /ysm-gpfs/pi/xxxx/bl626/opt/cromwell/cromwell-33.1.jar run atac.wdl -i atac_inputs.json`

My workflow configuration file look like this:

[atac_workflow_options.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2232400/atac_workflow_options.txt)

and my input file in json format looks like this:

[atac_inputs.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2232430/atac_inputs.txt)

Github does not allow me attaching `.conf` and `.json` files. So I renamed atac_workflow_options.conf to atac_workflow_options.txt and atac_inputs.json to atac_inputs.txt just for the purpose of attaching them.

Another interesting thing I have noticed is that the workflow loves to stop for 'no reason' after finishing the bowtie2 task. I've tried this workflow 10+ times, I would say 80% of them stoped after finishing bowtie2. And it gave absolutely nothing in the stderr file.

Thank you again!

**Comment by mkdegorter** [comment]
When I try:

$ source activate encode-atac-seq-pipeline
$ which picard.jar

I get the following:

/usr/bin/which: no picard.jar in (/home/mdegorte/miniconda3/envs/encode-atac-seq-pipeline/bin:/labs/smontgom/mdegorte/ATAC/atac-seq-pipeline/src:/home/mdegorte/miniconda3/bin:/scg/slurm/current/bin:/scg/slurm/current/sbin:/scg/slurm/utils:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/mdegorte/.bds:/home/mdegorte/.globus-cli-virtualenv/bin:/home/mdegorte/bin)

Please let me know how to proceed. Thanks!

**Comment by computbiolgeek** [comment]
Hi, for this issue, you can try to install picard.jar locally, say you install it under directory `$HOME/opt/picard`, then you append the following line to your .bashrc file: 
`export PATH="$HOME/opt/picard:$PATH"`

**Comment by leepc12** [comment]
Closing this due to long inactivity. Please let me know if this error still persists.
