### ISSUE TITLE
Viewing bigbed (.bb) files on UCSC Browser

### ISSUE THREAD

**Issue by rameshvnair** [ENCODE-DCC/atac-seq-pipeline#192]
When I view the .bb peak files from the ATAC-Seq pipeline on the UCSC Browser as a custom track I get the following error regarding the file format. Could chromosome names be made lowercase for compatibility, e.g., chr1 as in UCSC browser error below? I tried uploading the idr_reprodicibilty conservative peaks .bb file via an url as required. Thanks.
    Error Unrecognized format line 2 of https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://drive.google.com/open?id%3D1RE31MTtS5ekd0m7igCJan_oEmz_-TpQn&followup=https://drive.google.com/open?id%3D1RE31MTtS5ekd0m7igCJan_oEmz_-TpQn: (note: chrom names are case sensitive, e.g.: correct: 'chr1', incorrect: 'Chr1', incorrect: '1')

**Comment by leepc12** [comment]
We cannot add such edge-case customization to the pipeline. Can you start from building a UCSC-browser-compatible genome (with lower case chromosome names) or manually change cases in `*.bfilt.narrowPeak.gz` and convert it to BB using `bedToBigBed`?

**Comment by rameshvnair** [comment]
Thanks, will try rebuilding the bigbed (.bb) file after the desired change.

**Comment by leepc12** [comment]
Closing this due to long inactivity
