### ISSUE TITLE
Output guide

### ISSUE THREAD

**Issue by jmzvillarreal** [ENCODE-DCC/atac-seq-pipeline#194]
Hi,
I am running the atac pipeline for the first time and I am was wondering where could I find a guide to go through all the folders in the output... 
thanks in advance !
Jaime.

**Comment by leepc12** [comment]
We will update documentation for outputs. Until then use [Croo](https://github.com/ENCODE-DCC/croo) to organize outputs and you will find a file table and a task graph that summaries/describes all outputs.

**Comment by leepc12** [comment]
Please use Croo to get description for each output file. Closing this.
