### ISSUE TITLE
[Caper] Error (womtool): WDL or input JSON is invalid.

### ISSUE THREAD

**Issue by rdbcasillas** [ENCODE-DCC/atac-seq-pipeline#195]
**Describe the bug**
Womtool unable to validate input json. Warnings with parameters flagged are pasted below. 

**OS/Platform**
- OS/Platform: Ubuntu 16.04
- Conda version: Did not use Conda
- Pipeline version: v1.5.4
- Caper version: v0.6.1

**Caper configuration file**

db=mysql
file-db=~/.caper/default_file_db

**Input JSON file**

{

    "atac.genome_tsv" : "/vol_d/references/mm10/mm10.tsv",
    "atac.paired_end" : true,
    "atac.fastqs_rep1_R1" : ["/vol_c/P7-P14-rawdata/P14/rep1/P14_rep1_R1.fastq.gz"],
    "atac.fastqs_rep1_R2" : ["/vol_c/P7-P14-rawdata/P14/rep1/P14_rep1_R2.fastq.gz"],
    "atac.fastqs_rep2_R1" : ["/vol_c/P7-P14-rawdata/P14/rep2/P14_rep2_R1.fastq.gz"],
    "atac.fastqs_rep2_R2" : ["/vol_c/P7-P14-rawdata/P14/rep2/P14_rep2_R2.fastq.gz"],
    "atac.auto_detect_adapter" : true,

    "atac.title" : "P14 ATAC (paired end)",
    "atac.description" : "ATAC pipeline for P14 dataset",

    "atac.pipeline_type" : "atac",

    "atac.align_only" : false,
    "atac.true_rep_only" : false,

    "atac.multimapping" : 0,

    "atac.dup_marker" : "picard",
    "atac.mapq_thresh" : 30,
    "atac.no_dup_removal" : false,

    "atac.subsample_reads" : 0,

    "atac.enable_xcor" : false,
    "atac.xcor_subsample_reads" : 25000000,

    "atac.cap_num_peak" : 300000,
    "atac.pval_thresh" : 0.01,
    "atac.smooth_win" : 150,

    "atac.enable_idr" : false,
    "atac.idr_thresh" : 0.1,

    "atac.trim_adapter_cpu" : 16,
    "atac.trim_adapter_mem_mb" : 42000,

    "atac.align_cpu": 16,
    "atac.align_mem_mb" : 42000,

    "atac.filter_cpu" : 16,
    "atac.filter_mem_mb" : 42000,

    "atac.bam2ta_cpu" : 16,
    "atac.bam2ta_mem_mb" : 42000,

    "atac.spr_mem_mb" : 32000,

    "atac.xcor_cpu" : 16,
    "atac.xcor_mem_mb" : 42000,

    "atac.macs2_signal_track_mem_mb" : 42000,

    "atac.ataqc_mem_mb" : 42000
}

**Error log**
➜  atac-seq-pipeline **sudo caper run atac.wdl -i $INPUT -m P14.json --docker**
[CaperURI] read from local, src: /mnt/mm10_atac_pe.json
[CaperURI] read from local, src: /vol_d/references/mm10/mm10.tsv
[CaperURI] copying from url to local, src: https://github.com/broadinstitute/cromwell/releases/download/47/cromwell-47.jar
[CaperURI] file already exists. skip downloading and ignore HTTP_ERR 416
[CaperURI] copying skipped, target: /home/ishv99/.caper/cromwell_jar/cromwell-47.jar
[CaperURI] copying from url to local, src: https://github.com/broadinstitute/cromwell/releases/download/47/womtool-47.jar
[CaperURI] file already exists. skip downloading and ignore HTTP_ERR 416
[CaperURI] copying skipped, target: /home/ishv99/.caper/womtool_jar/womtool-47.jar
**[Caper] Validating WDL/input JSON with womtool...
WARNING: Unexpected input provided: atac.trim_adapter_cpu
WARNING: Unexpected input provided: atac.ataqc_mem_mb
WARNING: Unexpected input provided: atac.trim_adapter_mem_mb
[Caper] Error (womtool): WDL or input JSON is invalid.**

$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

**Comment by leepc12** [comment]
See the above warning to fix your input JSON. These are old parameters.
```
WARNING: Unexpected input provided: atac.trim_adapter_cpu
WARNING: Unexpected input provided: atac.ataqc_mem_mb
WARNING: Unexpected input provided: atac.trim_adapter_mem_mb
```

**Comment by leepc12** [comment]
Closing this due to long inactivity
