### ISSUE TITLE
Samples being excluded from call-call_peak_pooled and call-macs2_signal_track_pooled

### ISSUE THREAD

**Issue by vpeng2016** [ENCODE-DCC/atac-seq-pipeline#197]
I am running the ATAC-seq pipeline with paired-end sequencing from biological duplicates. I've noticed that for certain pairs of duplicates, one of the replicates is excluded from pooled peak calling and signal track generation (there is only one tagAlign file called in the inputs directory).
**Is this intended behavior due to poor IDR testing?** Based on the QC report, the pseudoreplicates passed IDR.

**If this is intended behavior, do you know what statistic is used to decide whether a sample is excluded?**

Thanks!

**OS/Platform**
- OS/Platform: CentOS release 6.9
- Conda version: conda 4.7.12
- Pipeline version: v1.5.2

**Comment by leepc12** [comment]
Please upload Input JSON file here

**Comment by vpeng2016** [comment]
{
    "atac.title" : "WT",
    "atac.description" : "WT",

    "atac.pipeline_type" : "atac",
    "atac.align_only" : false,
    "atac.true_rep_only" : false,

    "atac.genome_tsv" : "/scratch/vpeng/atac_input/input/genome/mm10.tsv",

    "atac.paired_end" : true,

    "atac.fastqs_rep1_R1" : [
        "/scratch/vpeng/atac_input/input/fastqs/24.2975_2.R1.fq.gz"
    ],
    "atac.fastqs_rep1_R2" : [
        "/scratch/vpeng/atac_input/input/fastqs/24.2975_2.R2.fq.gz"
    ],
    "atac.fastqs_rep2_R1" : [
        "/scratch/vpeng/atac_input/input/fastqs/25.2976_1.R1.fq.gz"
    ],
    "atac.fastqs_rep2_R2" : [
        "/scratch/vpeng/atac_input/input/fastqs/25.2976_1.R2.fq.gz"
    ],

    "atac.auto_detect_adapter" : true,

    "atac.multimapping" : 4,

    "atac.pval_thresh" : 0.01,
    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.enable_xcor" : true
}

**Comment by leepc12** [comment]
A pooled replicate takes a file name prefix from the first replicate only. That doesn't mean that the second replicate is excluded from pooling.

**Comment by akundaje** [comment]
Jin - This is a common point of confusion. We should change the file naming
as we had discussed before.

-Anshul.

**Comment by vpeng2016** [comment]
Ah, I see. Thank you very much for the clarification!

**Comment by leepc12** [comment]
@akundaje: I think we already discussed it an year ago. Most UNIX based systems do not support a filename longer than 255. So we cannot blindly concatenate filenames (like the old BDS pipeline did) or we cannot use a fixed prefix like `rep1` or `rep2` because it's still important to keep a filename prefix that implies where it is derived from.

If we have three TAG-ALIGNs to be merged: `rep1.tagAlign.gz`, `rep2.tagAlign.gz` and `rep3.tagAlign.gz`. Then pooled TAG-ALIGN will have a filename `rep1.pooled.tagAlign.gz`. I think `.pooled.` explicitly shows that it is a pooled file.

**Comment by akundaje** [comment]
And I had discussed with you that having Rep1 in the file name is extremely
confusing. Having pooled doesnt help with the prefix says Rep1

-A

**Comment by leepc12** [comment]
@akundaje: OK, I will remove rep1 prefix from the pooled TA so that pooled TA will have a fixed filename of `rep.pooled.tagAlign.gz`.

**Comment by akundaje** [comment]
Yeah that sounds less confusing
