### ISSUE TITLE
Error in pipeline

### ISSUE THREAD

**Issue by cultivo-hy** [ENCODE-DCC/atac-seq-pipeline#20]
**Describe the bug**
Hi. I'm trying to run the atac-seq-pipeline and old version(deprecated) is working.
But this new version makes some errors when running the pipeline( encode_trim_adapter.py) . 

 [error] WorkflowManagerActor Workflow 5a715660-fc5d-425f-9b4a-8b5b94ce81e8 failed (during ExecutingWorkflowState): Job atac.trim_adapter:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.

I attached stderr log. and I'm not sure 'input.json' is correct.
I tried to use this (https://www.encodeproject.org/experiments/ENCSR245LNF/) replicate2.

input.json  
{

    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/home/dmb/hoyongLee/atac-seq-pipeline/hg38.tsv",
    
    "atac.fastqs" : [[
               [
                 "/home/dmb/hoyongLee/data/ENCFF154KNN.fastq",
                 "/home/dmb/hoyongLee/data/ENCFF829SBE.fastq"
               ],
               [
                "/home/dmb/hoyongLee/data/ENCFF565CVN.fastq",
                "/home/dmb/hoyongLee/data/ENCFF092IJN.fastq"
               ],
               [
                "/home/dmb/hoyongLee/data/ENCFF351LRE.fastq",
                "/home/dmb/hoyongLee/data/ENCFF803XRX.fastq"
               ],
               [
                "/home/dmb/hoyongLee/data/ENCFF709FLO.fastq",
                "/home/dmb/hoyongLee/data/ENCFF396BSZ.fastq"
               ],
               [
                "/home/dmb/hoyongLee/data/ENCFF247VZG.fastq",
                "/home/dmb/hoyongLee/data/ENCFF738DHW.fastq"
               ]
    ]],

    "atac.paired_end" : true,
    "atac.multimapping" : 4,

    "atac.trim_adapter.auto_detect_adapter" : true,

    "atac.bowtie2.cpu" : 4,
    "atac.bowtie2.mem_mb" : 16000,

    "atac.filter.cpu" : 4,
    "atac.filter.mem_mb" : 12000,

    "atac.macs2_mem_mb" : 16000,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.qc_report.name" : "ENCSR245LNF",
    "atac.qc_report.desc" : "ATAC-seq on Mus musculus C57BL/6 frontal cortex adult"
}

**OS/Platform and dependencies**
- OS or Platform:  Ubuntu 16.04, AWS instance
- Cromwell/dxWDL version:  cromwell-33.1
- Conda version: 4.5.4

**Attach logs**

 File "/home/dmb/hoyongLee/atac-seq-pipeline/cromwell-executions/atac/e765d0d0-ffee-4c81-b679-1d2cccce874c/call-trim_adapter/shard-0/execution/write_tsv_55ca5bd3e4730afa22126a0109b4636d.tmp", line 1
   2     /home/dmb/hoyongLee/atac-seq-pipeline/cromwell-executions/atac/e765d0d0-ffee-4c81-b679-1d2cccce874c/call-trim_adapter/shard-0/inputs/-1676945734/ENCFF154KNN.fastq  /home/dmb/hoyongLee/atac-seq-pipeline/             cromwell-executions/atac/e765d0d0-ffee-4c81-b679-1d2cccce874c/call-trim_adapter/shard-0/inputs/-1676945734/ENCFF829SBE.fastq
   3     ^
   4 SyntaxError: invalid syntax

**Comment by leepc12** [comment]
Did you install Conda dependencies (`installers/install_dependencies.sh`) for the pipeline?
Did you activate conda env (`source activate encode-atac-seq-pipeline`) before running pipeline?

**Comment by cultivo-hy** [comment]
Thanks, Lee. I missed some parts and solved this problem.
Now, the pipeline is working. 
By the way, Is there any reasons using a tagAlign format in Macs2?
I wonder if there are differences in the result when using normal Bam format.
(Is possible to skip bam2ta.py in a pipeline?)

**Comment by leepc12** [comment]
That sounds good..

Yes, MACS2 can work with BAMs too but there are other parts of the pipeline that use TAG-ALIGN format. We wanted to use a unified input for those tasks not to complicate the pipeline's task dependency tree.

BAM2TA doesn't take long. It's simply a `samtools view | awk` task.

**Comment by leepc12** [comment]
closing this due to long inactivity
