### ISSUE TITLE
Add back read count from sequencer in QC report?

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#201]
Could you please add back the "read count from sequencer" QC metric that used to be output by the ATAQC module since `align.samstat.total_reads` is much larger than the raw read count when the multimapping parameter is greater than 1?

Pipeline version: 1.5.4

**Comment by leepc12** [comment]
I am sorry about late response. Currently we don't have a plan for this since we already refactored the ATAQC module.

**Comment by leepc12** [comment]
Closing this issue due to long inactivity.
