### ISSUE TITLE
5/20 pipelines fail with JSONDecodeError

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#202]
I ran 20 workflows with identical parameters and the same reference genome in parallel. 15 of them finished without error, but the other 5 failed with this error. Can you please help me figure out what is going on here? `[WFID]/call-overlap_pr/shard-0/execution` for the five failed workflows is empty, with no `stderr` files.
```
2019-12-10 00:23:17,303 cromwell-system-akka.dispatchers.backend-dispatcher-488 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(33498628)atac.overlap_pr:0:1]: `
touch null
python3 $(which encode_task_overlap.py) \
	/projects/motrpac/PASS1A/ATAC/RUN14/output/atac/33498628-f485-4ef4-8db4-4726a02c632a/call-overlap_pr/shard-0/inputs/-730758128/H6_female_1h_acute_heart_S16_L001_R1_001.trim.merged.nodup.no_chrM_MT.tn5.pr1.pval0.01.300K.narrowPeak.gz /projects/motrpac/PASS1A/ATAC/RUN14/output/atac/33498628-f485-4ef4-8db4-4726a02c632a/call-overlap_pr/shard-0/inputs/-100299503/H6_female_1h_acute_heart_S16_L001_R1_001.trim.merged.nodup.no_chrM_MT.tn5.pr2.pval0.01.300K.narrowPeak.gz /projects/motrpac/PASS1A/ATAC/RUN14/output/atac/33498628-f485-4ef4-8db4-4726a02c632a/call-overlap_pr/shard-0/inputs/-1019954336/H6_female_1h_acute_heart_S16_L001_R1_001.trim.merged.nodup.no_chrM_MT.tn5.pval0.01.300K.narrowPeak.gz \
	--prefix rep1-pr1_vs_rep1-pr2 \
	--peak-type narrowPeak \
	--chrsz /projects/motrpac/PASS1A/ATAC/RUN14/output/atac/33498628-f485-4ef4-8db4-4726a02c632a/call-overlap_pr/shard-0/inputs/-1254032490/motrpac_rn6.chrom.sizes \
	 \
	--nonamecheck \
	--regex-bfilt-peak-chr-name 'chr[\dXY]+' \
	--ta /projects/motrpac/PASS1A/ATAC/RUN14/output/atac/33498628-f485-4ef4-8db4-4726a02c632a/call-overlap_pr/shard-0/inputs/1050766451/H6_female_1h_acute_heart_S16_L001_R1_001.trim.merged.nodup.no_chrM_MT.tn5.tagAlign.gz`
Traceback (most recent call last):
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1266, in main
    c.run()
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 272, in run
    json.loads(fp.read()))
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = sel
[JSONDecodeError.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3946411/JSONDecodeError.zip)
f.raw_decode(s, idx=_w(s, 0).end())
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**OS/Platform**
- OS/Platform: SCG 
- Conda version: conda 4.7.12
- Pipeline version: 1.5.4
- Caper version: 0.6.1

**Caper configuration file**
```
backend=slurm
slurm-account=prj_motrpac

tmp-dir=/projects/motrpac/tmp

db=file
```

**Input JSON file**
Each JSON file looks something like this, just with different FASTQ files and descriptions:
```
{
    "atac.title" : "H6_female_1h_acute_heart_S16",
    "atac.genome_tsv" : "[...]ATAC/REFERENCES/motrpac_rn6/motrpac_rn6.tsv",

    "atac.description" : "PASS1A RUN14",
    "atac.pipeline_type" : "atac",

    "atac.paired_end" : true,
    "atac.multimapping" : 4,
    "atac.auto_detect_adapter" : true,
    "atac.enable_idr" : false,

    "atac.filter_cpu" : 4,
    "atac.bam2ta_cpu" : 4,

    "atac.align_mem_mb" : 40000,
    "atac.filter_mem_mb" : 40000,
    "atac.bam2ta_mem_mb" : 40000,
    "atac.spr_mem_mb" : 40000,

    "atac.fastqs_rep1_R1" : [
        "[...]H6_female_1h_acute_heart_S16_L001_R1_001.fastq.gz",
        "[...]H6_female_1h_acute_heart_S16_L002_R1_001.fastq.gz"
    ],

    "atac.fastqs_rep1_R2" : [
        "[...]H6_female_1h_acute_heart_S16_L001_R2_001.fastq.gz",
        "[...]H6_female_1h_acute_heart_S16_L002_R2_001.fastq.gz"
    ]

}
```

**Error log**
I attached the SLURM log file and the caper files. 

`caper list` and `caper debug [WFID]` give me this error: `HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/workflows/v1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b201f83f828>: Failed to establish a new connection: [Errno 111] Connection refused'))
Help: cannot connect to server. Check if server is dead or still spinning up.` 
No metadata.json file is generated if the workflow fails. 
[JSONDecodeError.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3946479/JSONDecodeError.zip)

**Comment by nicolerg** [comment]
3 of the 5 failed workflows also start with this error, which may correspond to the 2 Java-related core dumps I also see in the output folder:
```
Success!
Uncaught error from thread [cromwell-system-akka.dispatchers.backend-dispatcher-343]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[cromwell-system]
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
        at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
        at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
        at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
        at akka.actor.ActorCell.invoke(ActorCell.scala:584)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
        at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 11 more
Caused by: java.util.zip.ZipException: error reading zip file
        at java.util.zip.ZipFile.read(Native Method)
        at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at sun.misc.Resource.getBytes(Resource.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        ... 17 more

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "cromwell-system-shutdown-hook-1"
```
I attached one of the log files accompanying one of the core dumps. 
[hs_err_pid2775.log.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3946475/hs_err_pid2775.log.zip)

**Comment by leepc12** [comment]
Did you interrupt it (e.g. Control + C)? That error means that Caper failed to find a `metadata.json` file when trying to troubleshoot the failed workflow. So that is not the actual reason for failure.

Please find any non-empty `stderr` file and make a TAR ball of all text files .qc, .txt, .log. including `stdout` and `stderr` and upload it here.

I think your job reached the `overlap` task, which is almost close to the final step of the pipeline and there is no downstream analysis which requires JAVA. I think that JAVA error occurred in Cromwell itself. What is your `_JAVA_OPTS` env var? Did you run `caper server`? If so, it's not recommended on HPCs.

**Comment by nicolerg** [comment]
Thanks, Jin. 

No, I did not interrupt it. I have never seen a `metadata.json` file when a workflow failed - only when it successfully completes. 

No, I did not use `caper sever`. I used `caper run`. 

`$JAVA_OPTS` and `$_JAVA_OPTS` are both empty, so I'm not sure.

This isn't a tarball, but it's a copy of all of the *qc, *log, and *txt files, as well as concatenated stdout are stderr log files (named by parent folder). Please let me know if there is a different way you would like me to collect files. 
[debug.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3946965/debug.zip)

**Comment by nicolerg** [comment]
I restarted the workflows with identical input JSON files and identical commands using the file DBs, and they finished without error. Is there some limit on the number of workflows than can be run in parallel? There could have also been some kind of issue with SCG when they were running the first time, but I'm not clear what.

**Comment by leepc12** [comment]
Default JAVA memory for `caper run` mode is 1GB by default. You can change it in your conf file `~/.caper/default.conf`. I will increase it to 2GB in the next release.
```
java-heap-run=2G
```
Cromwell is a kind of a memory devourer like other JAVA apps. I think failed runs went over the 1 GB limit somehow.

**Comment by leepc12** [comment]
Sorry it's already 2G by default. Can you try with 3G or 4G?

**Comment by nicolerg** [comment]
Thanks, I added `java-heap-run=4G` to `~/.caper/default.conf` and will try it the next time I process a batch of samples.

**Comment by imk1** [comment]
I am having this problem too, and setting java-heap-run=4G in ~/.caper/default.conf did not solve it.

**Comment by leepc12** [comment]
@imk1: Did you try with a file DB or MySQL DB?

**Comment by imk1** [comment]
I tried using a file DB, but I am not sure if I used the file DB correctly.  I set file-db=[directory on drive with a lot of space].

**Comment by leepc12** [comment]
@imk1: You should have `db=file` to use a file DB. Please upload your Caper conf (`~/.caper/default.conf`) and your input JSON file. Also, your full Caper screen output log and anything helpful for debugging.

**Comment by imk1** [comment]
How do I determine what file the file DB should be?

Since I could not figure out how to use the file db, I am sending the results from a run of the pipeline without it.

This is what I ran:
sbatch -p pfen1 -J CaperTest --export=ALL --mem 4G -t 4-0 --wrap "caper run /home/ikaplow/atac-seq-pipeline/atac.wdl -i /home/ikaplow/atac-seq-pipeline/example_input_json/caper/ENCSR356KRQ_subsampled_caper.json"

This is my ~/.caper/default.conf:
backend=slurm

# define one of the followings (or both) according to your
# cluster's SLURM configuration.
slurm-partition=pfen1
slurm-account=

java-heap-run=4G

tmp-dir=

**Comment by imk1** [comment]
Downgrading to caper version 0.4.1 might have solved the problem.  I need to see if I got lucky with my test run or if it works consistently now.

**Comment by leepc12** [comment]
@imk1: `caper debug` only works with a Caper/Cromwell server. Your SLURM log says that JAVA memory/thread error occurred.
```
Exception in thread "pool-4-thread-8" java.lang.OutOfMemoryError: unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
```


Try with limited number of concurrent jobs per workflow. You can control it with `--max-concurrent-tasks`. It's 40 by default.
```
caper run ... --max-concurrent-tasks 2
```

I think these can also be helpful.
https://gatkforums.broadinstitute.org/wdl/discussion/12346/cromwell-java-out-of-memory-unable-to-create-new-native-thread
http://www.mastertheboss.com/jboss-server/jboss-monitoring/how-to-solve-javalangoutofmemoryerror-unable-to-create-new-native-thread

**Comment by imk1** [comment]
Thanks for the suggestion and the links!

I tried the following 3 things, and they seem to have mostly solved the problem:
1.  Adding --max-concurrent-tasks 2
2.  Running ulimit -u 8192
3.  Running export _JAVA_OPTIONS="-Xms256M -Xmx728M -XX:ParallelGCThreads=1 -Xss256k"

**Comment by leepc12** [comment]
Closing this due to long inactivity
