### ISSUE TITLE
Read Filtering before bam File Generation

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#204]
I know that reads that multi-map too many times, reads with duplicates, or reads that map to the mitochondria are filtered when creating the nodup.bam file.

Is there any filtering done in the creation of the original bam file (found in the call-bowtie2 directory)?

Is there any filtering done at the adapter trimming stage (before mapping)?

Thanks so much!

Irene

**Comment by leepc12** [comment]
There is no read filtering for those.

**Comment by imk1** [comment]
Thanks!
