### ISSUE TITLE
caper hard link error

### ISSUE THREAD

**Issue by fangpingmu** [ENCODE-DCC/atac-seq-pipeline#205]
I'm testing the ENCODE ATAC SEQ pipeline on a cluster. 

A lot of hard link problems appear. 

Due to security reasons, hard links are not supported in many network mounts and virtual environments.

Cromwell uses hard link by default. caper is a wraper to cromwell. I changed the Cromwell configuration file to solve the wdl-related hardlink problems.

How to handle the hard link problems using caper? Are there ways to transfer cromwell configuration file to caper?

**Comment by akundaje** [comment]
Jin - this is a recurring problem. Can we use soft links instead of hard
links.

Anshul

**Comment by fangpingmu** [comment]
This seems to be a well-known problem for cromwell community. 

Have you tried this cached-copy for caper?

https://cromwell.readthedocs.io/en/stable/backends/HPC/

cached-copy is intended for a shared filesystem that runs on multiple physical disks, where docker containers are used. Hard-links don't work between different physical disks and soft-links don't work with docker. Copying uses a lot of space if a multitude of tasks use the same input. cached-copy copies the file only once to the physical disk containing the <workflow_root> and then uses hard links for every task that needs the input file. This can save a lot of space.

**Comment by akundaje** [comment]
Thanks. That's a great pointer.

Jin - let's look into this and try to avoid the hard links

**Comment by leepc12** [comment]
If hard-linking fails, Cromwell tries soft-linking or copying. You can simply ignore these localization failure warnings. I also get those warning when I run pipelines on network-mounted disks and no problem so far.

Caper uses Cromwell's default location strategies.
```
filesystems {
 local {
   localization: [
     "hard-link", "soft-link", "copy"
   ]
 }
}
```

`cached-copy` seems to be experimental. I will need to test it after my vacation.
