### ISSUE TITLE
Change in .bam file names in call-filter folder? 

### ISSUE THREAD

**Issue by cbmporter** [ENCODE-DCC/atac-seq-pipeline#206]
I am following a colleague's analysis, and they pointed me to a file in the "call-filter" folder with the suffix "trim.merged.nodup.bam", but I am not finding this file, I only have a file with the suffix "merged.nodup.bam". 

After doing some googling, I have found evidence that this file can indeed be found in the call-filter folder of at least some versions of the pipeline. I can't figure out if I have run the pipeline in a different or incorrect way, or if the naming convention has possibly just changed between versions. The pipeline completed successfully, I'm just not finding the file I expected to see. 

I am running the atac pipeline as a WDL on Terra, the pipeline version is 1.4.1. 

Here is an excerpt of my .json file (parameters not shown are just fastq paths, title, description, and CPU and memory specifications): 

    "encode_atac.pipeline_type" : "atac",
    "encode_atac.align_only" : false,
    "encode_atac.true_rep_only" : false,
    "encode_atac.genome_tsv" : "gs://encode-pipeline-genome-data/mm10_google.tsv",

    "encode_atac.paired_end" : true,
    "encode_atac.multimapping" : 4,

    "encode_atac.auto_detect_adapter" : true,

    "encode_atac.enable_xcor" : true

Thank you!

**Comment by leepc12** [comment]
(Recursively) Find `*.nodup.bam` under `call-filter` directory. Ignore `.trim.merged.` prefix.

**Comment by leepc12** [comment]
Closing this due to long inactivity
