### ISSUE TITLE
preseq not Working

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#208]
**Describe the bug**
The pipeline fails for me every time I try to use preseq.  I cannot tell if preseq is not working or if there is an internal time limit for preseq that is insufficient for my data.  I submitted the pipeline with 4 days of run-time, and it was running for < 3 days.  Thanks in advance for helping me trouble-shoot this!

**OS/Platform**
- OS/Platform: Linux cluster with Centos 6
- Conda version: 4.7.12
- Pipeline version: v1.5.4
- Caper version: 0.5.1

**Caper configuration file**
[defaults]
backend=slurm
slurm-partition=pfen1
slurm-account=ikaplow
java-heap-run=4G
tmp-dir=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/caper_tmp
no-file-db=True
ip=localhost
port=8000
show-completed-task=True

**Input JSON file**
{
 "atac.genome_tsv" : "/home/ikaplow/RegulatoryElementEvolutionProject/GenomeDataPipelines/mm10/mm10.tsv",
 "atac.fastqs_rep1_R1" : [ "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O1Cneg/O1Cneg_CKDL190142778-1a-N705-N503_HMHTYDSXX_L2_1.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O1Cneg/O1Cneg_CKDL190142778-1a-N705-N503_HMHTYDSXX_L3_1.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O1Cneg/O1Cneg_CKDL190142778-1a-N705-N503_HMHTYDSXX_L4_1.fq.gz" ],
 "atac.fastqs_rep1_R2" : [ "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O1Cneg/O1Cneg_CKDL190142778-1a-N705-N503_HMHTYDSXX_L2_2.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O1Cneg/O1Cneg_CKDL190142778-1a-N705-N503_HMHTYDSXX_L3_2.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O1Cneg/O1Cneg_CKDL190142778-1a-N705-N503_HMHTYDSXX_L4_2.fq.gz" ],
 "atac.fastqs_rep2_R1" : [ "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O2Cneg/O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L2_1.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O2Cneg/O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L3_1.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O2Cneg/O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L4_1.fq.gz" ],
 "atac.fastqs_rep2_R2" : [ "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O2Cneg/O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L2_2.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O2Cneg/O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L3_2.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O2Cneg/O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L4_2.fq.gz" ],
 "atac.fastqs_rep3_R1" : [ "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O3Cneg/O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L2_1.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O3Cneg/O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L3_1.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O3Cneg/O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L4_1.fq.gz" ],
 "atac.fastqs_rep3_R2" : [ "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O3Cneg/O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L2_2.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O3Cneg/O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L3_2.fq.gz", "/projects/MPRA/bats/Rousettus_aegyptiacus/fastqs/128.120.88.251/H202SC19103078/Rawdata/O3Cneg/O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L4_2.fq.gz" ],
 "atac.pipeline_type" : "atac",
 "atac.paired_end" : true,
 "atac.auto_detect_adapter" : true,
 "atac.multimapping" : 0,
 "atac.enable_xcor" : false,
 "atac.cap_num_peak" : 300000,
 "atac.filter_chrs" : ["chrM", "MT"],
 "atac.smooth_win" : 150,
 "atac.enable_idr" : true,
 "atac.idr_thresh" : 0.1,
 "atac.enable_compare_to_roadmap" : true,
 "atac.enable_preseq" : true,
 "atac.align_mem_mb" : 40000,
 "atac.call_peak_time_hr" : 48,
 "atac.title" : "my title",
 "atac.description" : "my description"
}

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

[Caper] troubleshooting 974eb88f-f0c4-4eff-b71e-982bf1f37670 ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "The job was aborted from outside Cromwell"
            },
            {
                "message": "The job was aborted from outside Cromwell",
                "causedBy": []
            }
        ],
        "message": "Workflow failed"
    }
]

atac.read_genome_tsv Done. SHARD_IDX=-1, RC=0, JOB_ID=12006920, RUN_START=2019-12-18T19:03:54.768Z, RUN_END=2019-12-18T19:04:35.903Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-read_genome_tsv/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-read_genome_tsv/execution/stderr
STDERR_CONTENTS=

atac.filter Done. SHARD_IDX=1, RC=0, JOB_ID=12006998, RUN_START=2019-12-19T10:14:52.559Z, RUN_END=2019-12-19T22:06:01.935Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-filter/shard-1/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-filter/shard-1/execution/stderr
STDERR_CONTENTS=

atac.filter Done. SHARD_IDX=2, RC=0, JOB_ID=12007002, RUN_START=2019-12-19T11:14:52.548Z, RUN_END=2019-12-19T22:59:29.149Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-filter/shard-2/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-filter/shard-2/execution/stderr
STDERR_CONTENTS=

atac.align Done. SHARD_IDX=0, RC=0, JOB_ID=12006924, RUN_START=2019-12-18T19:04:44.560Z, RUN_END=2019-12-19T17:24:44.672Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-align/shard-0/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-align/shard-0/execution/stderr
STDERR_CONTENTS=

atac.align Done. SHARD_IDX=1, RC=0, JOB_ID=12006923, RUN_START=2019-12-18T19:04:42.591Z, RUN_END=2019-12-19T10:14:43.832Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-align/shard-1/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-align/shard-1/execution/stderr
STDERR_CONTENTS=

atac.align Done. SHARD_IDX=2, RC=0, JOB_ID=12006922, RUN_START=2019-12-18T19:04:40.588Z, RUN_END=2019-12-19T11:14:42.663Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-align/shard-2/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-align/shard-2/execution/stderr
STDERR_CONTENTS=

atac.preseq Failed. SHARD_IDX=1, RC=None, JOB_ID=12006999, RUN_START=2019-12-19T10:14:54.556Z, RUN_END=2019-12-19T11:32:25.829Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/execution/stderr
STDERR_CONTENTS=
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/tmp.ce39b542
INFO    2019-12-19 05:42:57     EstimateLibraryComplexity

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    EstimateLibraryComplexity -INPUT ./O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L2_1.trim.merged.no_rg.bam -OUTPUT O2Cneg_CKDL190142778-1a-N707-N503_HMHTYDSXX_L2_1.trim.merged.picardcomplexity.qc -USE_JDK_DEFLATER TRUE -USE_JDK_INFLATER TRUE -VERBOSITY ERROR -QUIET TRUE
**********

slurmstepd: *** JOB 12006999 CANCELLED AT 2019-12-19T06:15:32 DUE TO TIME LIMIT on compute-1-12 ***
/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/execution/script: line 1: 109419 Terminated              tee '/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/execution/stdout' < "$out974eb88f"
/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/execution/script: line 1: 109420 Terminated              tee '/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-1/execution/stderr' < "$err974eb88f" 1>&2

atac.preseq Failed. SHARD_IDX=2, RC=None, JOB_ID=12007003, RUN_START=2019-12-19T11:14:54.551Z, RUN_END=2019-12-19T13:28:34.930Z, STDOUT=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/execution/stdout, STDERR=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/execution/stderr
STDERR_CONTENTS=
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/tmp.29701d5e
INFO    2019-12-19 07:49:54     EstimateLibraryComplexity

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    EstimateLibraryComplexity -INPUT ./O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L2_1.trim.merged.no_rg.bam -OUTPUT O3Cneg_CKDL190142778-1a-N706-N503_HMHTYDSXX_L2_1.trim.merged.picardcomplexity.qc -USE_JDK_DEFLATER TRUE -USE_JDK_INFLATER TRUE -VERBOSITY ERROR -QUIET TRUE
**********

slurmstepd: *** JOB 12007003 CANCELLED AT 2019-12-19T08:16:32 DUE TO TIME LIMIT on compute-1-12 ***
/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/execution/script: line 1: 119295 Terminated              tee '/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/execution/stdout' < "$out974eb88f"
/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/execution/script: line 1: 119296 Terminated              tee '/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGrant/MouseDNase/CortexSSTMinusOld/atac/974eb88f-f0c4-4eff-b71e-982bf1f37670/call-preseq/shard-2/execution/stderr' < "$err974eb88f" 1>&2

**Comment by akundaje** [comment]
Preseq is a waste of time. The other complexity measures are good enough

**Comment by imk1** [comment]
I changed "atac.enable_preseq" to false, and that solved the problem.  I do not use the preseq results very much because there are so many other complexity metrics in the report, but it occurred to me that others might be using it.  Therefore, do not worry about fixing this for me alone.
