### ISSUE TITLE
Simplify conda installation

### ISSUE THREAD

**Issue by karl616** [ENCODE-DCC/atac-seq-pipeline#21]
Hi,

would it be interesting to you to simplify the conda installation procedure?

I would be willing to help. There are a couple of things that could be done:

1. Add idr, phantompeakqualtools and picard-v2.10.6 to bioconda
1. See if it is possible to fix graphviz, otherwise enforce the anaconda version already in the environment file

My goal would be to be able to set up the environment directly from an environment file.

**Comment by karl616** [comment]
I started with an update to the idr recipe:
https://github.com/bioconda/bioconda-recipes/pull/10112

**Comment by karl616** [comment]
Picard 2.10.6 is available in bioconda.
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/7ec10b6cb310cbdda9eddd42d884a4b2a5de6127/installers/install_dependencies.sh#L51-L53

The `picard.jar` file is present under the share folder. Perhaps it is possible to use this?

**Comment by karl616** [comment]
#22 should allow picard tools to be installed directly through conda instead

**Comment by leepc12** [comment]
Thanks for your work on this. We appreciate it. We can talk more on your PR.
