### ISSUE TITLE
Can I resume the pipeline after revising regex_bfilt_peak_chr_name

### ISSUE THREAD

**Issue by Jinxian52099** [ENCODE-DCC/atac-seq-pipeline#210]
Hello!

The pipeline stopped at blacklist filtering for peaks. I check the logfile and found that I set a wrong regex_bfilt_peak_chr_name.

After I revised the regex_bfilt_peak_chr_name in genome_tsv file, can I run the pipeline from where it stopped (blacklist filtering for peaks)? If yes, can you tell me the commands I can use?

Or should I restart the pipeline from the beginning (trimming, mapping and so on)? 

Following is my output directory. Thank you very much!

./atac/
└── fc46d38b-7018-4ab3-b3b8-c545ef9b29e6
    ├── call-align
    ├── call-align_mito
    ├── call-bam2ta
    ├── call-call_peak
    ├── call-call_peak_pooled
    ├── call-call_peak_ppr1
    ├── call-call_peak_ppr2
    ├── call-call_peak_pr1
    ├── call-call_peak_pr2
    ├── call-filter
    ├── call-frac_mito
    ├── call-fraglen_stat_pe
    ├── call-gc_bias
    ├── call-macs2_signal_track
    ├── call-macs2_signal_track_pooled
    ├── call-pool_ta
    ├── call-pool_ta_pr1
    ├── call-pool_ta_pr2
    ├── call-read_genome_tsv
    └── call-spr

**Comment by leepc12** [comment]
Yes, if you have set up a database with `--db`. You can simply restart the pipeline with the same command line and then Cromwell (Caper) will automatically collect previous re-usable outputs.

For Cromwell (and its wrapper Caper), resuming means starting from the beginning by re-using outputs from previous workflows. See Cromwell's documentation about call-caching for details.

**Comment by leepc12** [comment]
Closing this due to long inactivity
