### ISSUE TITLE
Running out of Time for atac.gc_bias and atac.fraglen_stat_pe

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#212]
Multiple jobs of mine have been cancelled due to not finishing within the time limits for atac.fraglen_stat_pe and atac.gc_bias.  Which resource parameter do I need to increase in order to increase the time limits for these modules?

Thanks so much!

**Comment by leepc12** [comment]
I will increase walltime for these tasks. It's currently 1 hour which is too short.
Edit the following line until I fix this. Increase `time : 1` to 6.

https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/atac.wdl#L1719
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/atac.wdl#L1743

**Comment by imk1** [comment]
Thanks so much!
