### ISSUE TITLE
macOS: zcat, split, shuf

### ISSUE THREAD

**Issue by kaplans1** [ENCODE-DCC/atac-seq-pipeline#216]
I am on macOS Mojave.
Running on test json, using pipeline's Conda env.
I ran into the issue where I think zcat was creating. .gz.Z files instead of plain .gz files. See here:
http://fanhuan.github.io/en/2016/01/07/zcat-vs-gzcat/
The fix seemed to be to replace zcat with gzcat, which got me further along in the pipeline, but further compatibility(?) issues came up. I made the following changes:

changed zcat to gzcat in: 
encode_task_merge_fastq.py
encode_lib_common.py
encode_lib_genomic.py
encode_task_bam2ta.py
encode_task_spr.py

changed split to gsplit in:
encode_task_spr.py

changed shuf to gshuf in:
encode_task_spr.py

Each change helped me get further, but this is where I'm currently stuck.

Something fails in encode_task_spr.py 

The process gives the error:

STDERR=gshuf: ‘/dev/fd/63’: end of file

If I revert to shuf, it gives:

STDERR=shuf: ‘/dev/fd/63’: end of file

From the traceback it looks like it's coming from here, but my troubleshooting has been expended and I'm not sure where to go:

cmd1 = 'gzcat -f {} | sed \'N;s/\\n/\\t/\' | '
    cmd1 += 'gshuf --random-source=<(openssl enc -aes-256-ctr '
    cmd1 += '-pass pass:$(gzcat -f {} | wc -c) '
    cmd1 += '-nosalt </dev/zero 2>/dev/null) | '
    cmd1 += 'gsplit -d -l {} - {}.'
    cmd1 = cmd1.format(
        ta,
        ta,
        nlines,
        prefix)

It feels like I'm doing something wrong. Is there a smarter way to work around this, besides abandoning macOS?

**Comment by leepc12** [comment]
Instead of modifying pipeline codes add the following to your `~/.bashrc` and re-login.
```
alias zcat=gzcat
alias shuf=gshuf
alias split=gsplit
```

**Comment by kaplans1** [comment]
Thank you for the fast response. 

I've added it, and I believe the aliases are loading. To test if it was loading, I added a test bogus alias:
alias sed=gsed
It threw a bunch of errors when I activated the pipeline, saying gsed does not exist, which makes sense.

Unfortunately even though I added the aliases, it seems to fail at the point it initially failed (encode_task_trim_adapter.py)

**Comment by leepc12** [comment]
Can you install Docker and try with `caper run ... --docker`?
That will get rid of all annoying dependency errors.

**Comment by kaplans1** [comment]
I believe Docker resolved all issues - thank you.
