### ISSUE TITLE
How to cite the use of this pipeline?

### ISSUE THREAD

**Issue by vpeng2016** [ENCODE-DCC/atac-seq-pipeline#219]
Hi,

Do you have a recommendation on how to cite/reference the use of this pipeline in analysis of non-ENCODE data?

Thank you!

**Comment by akundaje** [comment]
Hi,

Please cite the 2012 main ENCODE paper and the Github URL of the pipeline

Thanks,
Anshul.

**Comment by ernstki** [comment]
To save the next visitor some time:

> ENCODE Project Consortium (2012). An integrated encyclopedia of DNA elements in the human genome. _Nature_, 489(7414), 57–74. https://doi.org/10.1038/nature11247

Here is a reasonable citation format for a GitHub repository, in an [APA-like style](https://web.archive.org/web/20180109030114/https://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html):

> ENCODE-DCC/atac-seq-pipeline [Computer software]. (2017). Retrieved from
https://github.com/ENCODE-DCC/atac-seq-pipeline

This does not reflect, however, which _version_ you used, so it may be helpful to note that in your "Methods" section. Ideally, the [Zenodo DOI](https://doi.org/10.5281/zenodo.596029) displayed in the README would be up-to-date, but as of this writing, that still points to an antiquated release (0.3.0).

See also:
 
- https://www.encodeproject.org/help/citing-encode

Hope that helps somebody.
