### ISSUE TITLE
related to issue #67

### ISSUE THREAD

**Issue by Baharehh** [ENCODE-DCC/atac-seq-pipeline#225]
Sorry Jin I had one more question which you addressed it here beautifully but I just want to male sure:
I have 2 experimental conditions: Cre/dCre and 3 samples.
can you please check the below to see if the array seems fine?
-if it's fine then seem like in your array, "rep" is indeed the experimental or biological condition?! and you recommend 1 x rep for each run?

**atac.fastqs_rep1_R1 = [Cre1_R1.fastq.gz, Cre2_R1.fastq.gz, Cre3_R1.fastq.gz]
atac.fastqs_rep1_R2 = [Cre1_R2.fastq.gz, Cre2_R2.fastq.gz, Cre3_R2.fastq.gz]

atac.fastqs_rep2_R1 = [dCre1_R1.fastq.gz, dCre2_R1.fastq.gz, dCre3_R1.fastq.gz]
atac.fastqs_rep2_R2 = [dCre1_R2.fastq.gz, dCre2_R2.fastq.gz, dCre3_R2.fastq.gz]**

**Comment by leepc12** [comment]
I would do something like this. Two experiments mean two pipelines.

One input JSON for Cre.
```
atac.fastqs_rep1_R1 = [Cre1_R1.fastq.gz],
atac.fastqs_rep1_R2 = [Cre1_R2.fastq.gz],

atac.fastqs_rep2_R1 = [Cre2_R1.fastq.gz],
atac.fastqs_rep2_R2 = [Cre2_R2.fastq.gz],

atac.fastqs_rep3_R1 = [Cre3_R1.fastq.gz],
atac.fastqs_rep3_R2 = [Cre3_R2.fastq.gz],
```

Another similar input JSON for dCre.

**Comment by Baharehh** [comment]
Thank you. 
But I want overlapping peaks for downstream DE analysis ...
do you think then i use bedtools to get the overlapping peaks?
Thanks
B
