### ISSUE TITLE
Workflow failed because some of the replicates didn't run through?

### ISSUE THREAD

**Issue by hoholee** [ENCODE-DCC/atac-seq-pipeline#226]
Hi,

I ran the atac-seq-pipeline with local backend and it failed possibly because it somehow skipped one of the three replicates in certain steps. This is a task graph generated by croo:

![image](https://user-images.githubusercontent.com/10512707/75615921-e8136680-5afe-11ea-89fe-1dbbd497205c.png)

It seems that the pipeline didn't run rep2 for the atac.filter step, and the folder for rep2 (shard-1) was not even created:
![image](https://user-images.githubusercontent.com/10512707/75615951-52c4a200-5aff-11ea-9ccb-b978a48222a9.png)

And here is my config json and the output metadata json:
[json.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/4271067/json.zip)

One thing I noticed is that the bam file for rep2 is much bigger than the bam files for rep1/3 (~17G vs ~8G). Do you think the limited compute resource is the reason that the pipeline skipped rep2?

Would you please help me debug this? Let me know if you need other log files. Thank you!

**Comment by leepc12** [comment]
I looked into your `metadata.json` file and found that it failed due to this bug (missing reg2map_bed file). https://github.com/ENCODE-DCC/atac-seq-pipeline/issues/36

Pipeline should be able to use `dnase` file (which is already defined in hg19 genome TSV file) instead of `reg2map_bed` if it doesn't exist.

Fixed in commit a3512e4e0c929bd90c8aa7a0834dd19e1e315005. So this will also be fixed in the next release.

**Comment by hoholee** [comment]
Yes, the `reg2map_bed` job is one bug of this and thanks for fixing that. I'll try your fix later.

But the `reg2map_bed` step is run pretty late after the `filter` and `bam2ta` steps, right? For some reason the rep2 didn't go through these two steps and also the following steps, without any obvious error report (at least from what I can see)...

I'm trying to rerun this with the `atac.enable_compare_to_roadmap` option set to false. And I set the resource parameters as follows:
```
"atac.align_cpu": 4,
  "atac.align_mem_mb": 20000,
  "atac.align_time_hr": 48,
  "atac.filter_cpu": 2,
  "atac.filter_mem_mb": 20000,
  "atac.filter_time_hr": 24,
  "atac.bam2ta_cpu": 2,
  "atac.bam2ta_mem_mb": 10000,
  "atac.bam2ta_time_hr": 6,
```
Hopefully I can recover the rep2...

**Comment by leepc12** [comment]
Your pipelines already reached to task `idr_pr` for all replicates. All replicates also have TAG-ALIGNs, which are outputs of `bam2ta` task.

Each replicate goes in parallel. But if any problem is found on one replicate, then Cromwell removes all queued tasks (it doesn't stop any running tasks though) related to that replicate (represented by `shard_index` in a `scatter` block).

It's still weird Croo failed to generate a task graph including those TAG-ALIGNs.

So set `enable_compare_to_roadmap` off and try again and see what happens.

**Comment by hoholee** [comment]
Hmm I just realized I uploaded the wrong json flies (I ran multiple samples that got similar issue but I picked the wrong one to show you). Here are the log files for the sample that actually encountered the replicate-skipping issue:
  
[logs.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/4277851/logs.zip)

Task graph shows no jobs finished after atac.align for rep2:
![image](https://user-images.githubusercontent.com/10512707/75716831-da87e900-5c84-11ea-8f78-66023086d3bd.png)

Folders do not exist for rep2 (shard-1):
![image](https://user-images.githubusercontent.com/10512707/75716898-0014f280-5c85-11ea-8824-70d981e95bd9.png)
 
And of course filtered bam files and TAG-ALIGN files do not exist either:
![image](https://user-images.githubusercontent.com/10512707/75717129-613cc600-5c85-11ea-8b87-4e4db2a65468.png)

![image](https://user-images.githubusercontent.com/10512707/75717011-305c9100-5c85-11ea-8f47-bc8ed9cd98f2.png)

It will be weird that Cromwell only removed the output files of rep2 from previous steps when it encountered the error in the `compare_to_roadmap` step, isn't it?

And I did some `grep` in the `metadata.json` file, much fewer lines with `shard-1` are found compared to `shard-0` and `shard-2`:
![image](https://user-images.githubusercontent.com/10512707/75717516-1c655f00-5c86-11ea-8a99-6069f9fa7ae5.png)

I guess there are other issues besides the `reg2map_bed` bug. Anyway I'm testing with your fix and also with the `enable_compare_to_roadmap` set to off. I will follow up once the pipeline finished.

**Comment by hoholee** [comment]
OK it finished without errors after I used your fix. Thanks for the help! And I'm closing this issue.
