### ISSUE TITLE
Macs2 p-val threshold change

### ISSUE THREAD

**Issue by rbronste** [ENCODE-DCC/atac-seq-pipeline#23]
It seems that a user can't adjust the Macs2 callpeak p-val threshold from 0.1? I might be missing something but how can one do this within the pipeline? Thank you.

**Comment by leepc12** [comment]
You can adjust p-val in your input JSON file (`""atac.pval_thresh").

See this for details. https://encode-dcc.github.io/wdl-pipelines/input_json_atac.html.

**Comment by rbronste** [comment]
Currently I am running the command as follows:

bds atac.bds -species mm10 -nth 16 -chrsz /sonas-hs/tollkuhn/hpc_norepl/home/rbronste/mm10.chrom.sizes -gensz mm - bwt2_idx .....................

Is the JSON file something I have to create additionally or does it get created during the running of the pipeline? Thank you!

**Comment by leepc12** [comment]
Please try with a new pipeline.
Closing this issue due to long inactivity.
