### ISSUE TITLE
Q on finding code that was run

### ISSUE THREAD

**Issue by olechnwin** [ENCODE-DCC/atac-seq-pipeline#231]
Hi,
I am trying to find the actual script that was run to perform IDR analysis. Can someone please let me know how can I find this?

Thank you!

**Comment by leepc12** [comment]
Here it is. 
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/src/encode_task_idr.py

**Comment by olechnwin** [comment]
Hi @leepc12 

Appreciate your quick reply. However, I'm trying to find the actual commands that was run after you set all the parameters. So, specific to my run.
Specifically, I am trying to find out how to the pipeline run IDR on more than two replicates and how the final peaks list are generated. I've run the pipeline with samples that have three replicates and now I'd like to find the commands on how to do IDR.

Thanks again!

**Comment by leepc12** [comment]
On your output directory run to find `stdout` files for IDR tasks. There are multiple calling of IDR task per replicate, pseudo-replicate, pooled replicate and so on.
```
$ find -name stderr | grep idr
```
Create a task graph by running Croo on your `metadata.json` output file. This will help you understand input/output of multiple IDR instances.

**Comment by olechnwin** [comment]
Thanks! I'll try that.

**Comment by leepc12** [comment]
Closing due to long inactivity.
