### ISSUE TITLE
Unable to start the job using PBS clustering

### ISSUE THREAD

**Issue by jessiechan0752** [ENCODE-DCC/atac-seq-pipeline#232]
Hi,

I try to use the pipeline to run some trial but it seems that the pipeline was not working in my scenario.

The key problem reported in the standard output of the PBS submitted job is :

[Caper] troubleshooting 001e0721-14c9-4805-b314-2c8dba4aa577 ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Unable to start job. Check the stderr file for possible errors: /atac/001e0721-14c9-4805-b314-2c8dba4aa577/call-read_genome_tsv/execution/stderr.submit"
            }
        ],
        "message": "Workflow failed"
    }
]

The content in the stderr.submit is:

socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd.

Your kind help will be much appreciated!
Thank you !

**Comment by leepc12** [comment]
Does your PBS cluster allow submitting (qsub) jobs on a compute node?

**Comment by jessiechan0752** [comment]
@leepc12 Yes. My IT manager said "It appeared that your PBS job attempted to submit another PBS job within such job and the configuration is not correct. Maybe you can check if that is the case."  Is there a way to check the configuration for PBS cluster?

**Comment by leepc12** [comment]
Yes, that's what Caper does on PBS. You may need to run it in a local mode. Run `caper init local` to reset your conf file `~/.caper/default.conf`. Make a backup if you want to keep old one.

And then,
```
$ conda activate encode-atac-seq-pipeline
$ echo "caper run atac.wdl -i your_input.json --max-concurrent-tasks 1" | qsub -V ... # with 4 cpus and 40GB of memory
```

**Comment by jessiechan0752** [comment]
@leepc12 Thank you! It works now!
