### ISSUE TITLE
Input file is a bam file,it seems picard have some problems

### ISSUE THREAD

**Issue by zhangpicb** [ENCODE-DCC/atac-seq-pipeline#237]
**Describe the bug**
Input file is a bam file,it seems that picard step has some problems.

First,if only use a bam, shoud I use "atac.paired_end": false in json file?
Second,picard step has some problems,more information are in error log.

**output**
only hav this output
call-filter
call-filter_no_dedup
call-read_genome_tsv
croo.filetable.fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b.tsv
croo.report.fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b.html
croo.task_graph.fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b.dot
croo.task_graph.fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b.svg
metadata.json

**OS/Platform**
- OS/Platform: CentOS Linux release 7.6.1810 (Core)
- Conda version: conda 4.7.12
- Pipeline version: v1.7.0
- Caper version: v0.7.0

**Caper configuration file**

backend=local
tmp-dir=/picb/lilab3/zhangliandong/ATACENCODE/caper_tmp

**Input JSON file**
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v1/hg19_caper.tsv",
    "atac.paired_end": false,
    "atac.bams" :["/picb/lilab3/zhangliandong/100atacLCLs/data/HG00112.bam"],
    "atac.auto_detect_adapter" : true,
    "atac.enable_xcor" : true,
    "atac.title" : "pipelinetest",
    "atac.description" : "A pipeline test "
}

**Error log**
nohup.out:

> Success!`

>Workflow fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b transitioned to state FailedCaper's output 
directory.

>atac.filter_no_dedup RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=84975, RUN_START=2020-03-20T11:18:43.987Z, RUN_END=2020-03-20T11:59:58.857Z, STDOUT=/picb/lilab3/zhangliandong/100atacLCLs/data/pipelinetest/atac/fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b/call-filter_no_dedup/shard-0/execution/stdout, STDERR=/picb/lilab3/zhangliandong/100atacLCLs/data/pipelinetest/atac/fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b/call-filter_no_dedup/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 305, in main
    filt_bam, args.out_dir, args.picard_java_heap)
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 174, in mark_dup_picard
    run_shell_cmd(cmd)
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=86030, PGID=86030, RC=1
STDERR=Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/picb/lilab3/zhangliandong/100atacLCLs/data/pipelinetest/atac/fd7e9890-7467-41eb-8a1a-eb5dfe1aac2b/call-filter_no_dedup/shard-0/tmp.82fb0eb1

```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

**Comment by leepc12** [comment]
Please upload a full nohup.out.

**Comment by zhangpicb** [comment]
> Please upload a full nohup.out.


[nohup.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/4379496/nohup.txt)

**Comment by leepc12** [comment]
That looks like your BAM quality problem.
```
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  1: RGHS38_20368:6:1101:15313:75144
```
https://gatkforums.broadinstitute.org/gatk/discussion/13658/i-got-someting-wrong-with-value-was-put-into-pairinfomap-more-than-once-and-read-name-regex

**Comment by zhangpicb** [comment]
> That looks like your BAM quality problem.
> 
> ```
> Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  1: RGHS38_20368:6:1101:15313:75144
> ```
> 
> https://gatkforums.broadinstitute.org/gatk/discussion/13658/i-got-someting-wrong-with-value-was-put-into-pairinfomap-more-than-once-and-read-name-regex

This bam comes from a cram file.Maybe fastq.gz file may avoid this error.I convert this cram file to 2 fastq.gz file.
`samtools fastq -@4 -1 sample1_R1.fastq -2 sample1_R2.fastq sample1.cram`
And there has a new error.
[nohup.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/4387227/nohup.txt)

**Comment by leepc12** [comment]
Error reason:
```
STDERR=[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
```
I think there is still quality issue on your BAM/FASTQ.


At the bottom of your log, you can find both STDOUT and STDERR of failed tasks and STDOUT has all the command lines so that you can reproduce the same error. Activate Conda environment and run each command line.
```
atac.filter Failed. SHARD_IDX=1, RC=1, JOB_ID=16568, RUN_START=2020-03-26T02:49:54.927Z, RUN_END=2020-03-26T02:50:14.638Z, STDOUT=/picb/lilab3/zhangliandong/100atacLCLs/HG00112/pipeline/atac/b4f692a4-dd0b-480c-9496-692f555c7050/call-filter/shard-1/attempt-2/execution/stdout, STDERR=/picb/lilab3/zhangliandong/100atacLCLs/HG00112/pipeline/atac/b4f692a4-dd0b-480c-9496-692f555c7050/call-filter/shard-1/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 296, in main
    args.nth, args.out_dir)
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 109, in rm_unmapped_lowq_reads_pe
    run_shell_cmd(cmd1)
  File "/picb/lilab3/zhangliandong/miniconda/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=16580, PGID=16580, RC=1
STDERR=[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
STDOUT=
```

**Comment by leepc12** [comment]
Closing due to long inactivity.
