### ISSUE TITLE
no encode_trim_adapter.py

### ISSUE THREAD

**Issue by yysheep2020** [ENCODE-DCC/atac-seq-pipeline#239]
**Describe the bug**
no encode_trim_adapter.py

**OS/Platform**
- SCG cluster
- Conda version: If you used Conda (`$ conda --version`).
- Pipeline version: 1.1.7.1
- Caper version: caper/0.4.1

**Caper configuration file**
backend=slurm
slurm-account=baas_lab_seungkim

tmp-dir=/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/tt

**Input JSON file**
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/reference/ENCODE/pipeline_genome_data/hg19_scg.tsv",

    "atac.fastqs_rep1_R1" : [
    "/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/SFGF-Kim-YH-14365/YH_AT_2A-TAAGGCGA-ATAGAGAG_S1_L005_R1_001.fastq.gz"
    ],
    "atac.fastqs_rep1_R2" : [
    "/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/SFGF-Kim-YH-14365/YH_AT_2A-TAAGGCGA-ATAGAGAG_S1_L005_R2_001.fastq.gz"
    ],

    "atac.fastqs_rep2_R1" : [
    "/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/SFGF-Kim-YH-14365/YH_AT_2B-CGTACTAG-ATAGAGAG_S2_L005_R1_001.fastq.gz"
    ],
	"atac.fastqs_rep2_R2" : [
    "/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/SFGF-Kim-YH-14365/YH_AT_2B-CGTACTAG-ATAGAGAG_S2_L005_R2_001.fastq.gz"
    ],

    "atac.paired_end" : true,
    "atac.multimapping" : 4,

    "atac.auto_detect_adapter" : true,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.enable_xcor" : true,

    "atac.title" : "atac",
    "atac.description" : "ATAC-seq",

    "atac.trim_adapter.cpu" : 1,
    "atac.trim_adapter.mem_mb" : 8000,
    "atac.trim_adapter.time_hr" : 6,
    "atac.bowtie2_cpu" : 1,
    "atac.bowtie2_mem_mb" : 8000,
    "atac.bowtie2_time_hr" : 6,
    "atac.filter_cpu" : 1,
    "atac.filter_mem_mb" : 8000,
    "atac.filter_time_hr" : 6,
    "atac.macs2_mem_mb" : 10000,
    "atac.macs2_time_hr" : 24,
    "atac.ataqc.mem_mb" : 10000,
    "atac.ataqc.mem_java_mb" : 8000,
    "atac.ataqc.time_hr" : 24
}

**Job Script**
#!/bin/bash -l

#SBATCH -J atac
#SBATCH --mem=5G
#SBATCH --export=ALL
#SBATCH -t 48:00:00
#SBATCH --mail-type=NONE
#SBATCH -A baas_lab_seungkim
#SBATCH -o %x.o%j

module load caper/0.4.1
conda activate atac-pipeline
module load caper/0.4.1

caper run /scg/apps/legacy/atac-seq-pipeline/1.1.7.1/atac.wdl -i /oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/human_input.json

**Error log**

file is in /oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/atac/ddbc3f8a-19fe-4198-a1b8-d2f5fc7bac24/call-trim_adapter/shard-1/execution
stderr file:

which: no encode_trim_adapter.py in (/scg/apps/software/caper/0.4.1/bin:/scg/apps/software/caper/0.4.1/envs/atac-pipeline/bin:/scg/apps/software/caper/0.4.1/condabin:/scg/slurm/current/bin:/scg/slurm/current/sbin:/scg/slurm/utils:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/yanyang8/.dotnet/tools:/home/yanyang8/.local/bin:/home/yanyang8/bin:/opt/dell/srvadmin/bin)
  File "/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/atac/ddbc3f8a-19fe-4198-a1b8-d2f5fc7bac24/call-trim_adapter/shard-1/execution/write_tsv_e81776aace8ddd163532b24173b2edc1.tmp", line 1
    /oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/atac/ddbc3f8a-19fe-4198-a1b8-d2f5fc7bac24/call-trim_adapter/shard-1/inputs/883532912/YH_AT_2B-CGTACTAG-ATAGAGAG_S2_L005_R1_001.fastq.gz    /oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/atac/ddbc3f8a-19fe-4198-a1b8-d2f5fc7bac24/call-trim_adapter/shard-1/inputs/883532912/YH_AT_2B-CGTACTAG-ATAGAGAG_S2_L005_R2_001.fastq.gz
    ^
SyntaxError: invalid syntax
ln: failed to access ‘/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/atac/ddbc3f8a-19fe-4198-a1b8-d2f5fc7bac24/call-trim_adapter/shard-1/execution/R1/*.fastq.gz’: No such file or directory
ln: failed to access ‘/oak/stanford/scg/lab_seungkim/2020_Baas_Service_YH/trim/human_2/atac/ddbc3f8a-19fe-4198-a1b8-d2f5fc7bac24/call-trim_adapter/shard-1/execution/R2/*.fastq.gz’: No such file or directory

**Comment by leepc12** [comment]
Your pipeline looks very old.

Please use the latest pipeline. `git clone` from this repo (master branch).

**Comment by yysheep2020** [comment]
I tried to ask admin to update the lastest caper. But how to activate the encode-atac-pipeline conda env?

**Comment by leepc12** [comment]
Follow instruction on READMEs for the pipeline and Caper.
Briefly, install miniconda3 on your local home first, `git clone` this repo. , run `scripts/install_conda_env.sh` on pipeline's repo to install pipeline's conda env. activate pipeline's environment. Caper is already included in the env.

Follow instruction for SCG on Caper's README.

**Comment by yysheep2020** [comment]
for 1 rep data, how to preprocessed the input file?

**Comment by leepc12** [comment]
Those two params have nothing to do with the number of replicates.
Use default values for them.
Use "atac.subsample_reads" if want to reduce your sample's read depth. 0 is by default and it means no subsampling.

**Comment by yysheep2020** [comment]
Got it. So the pipeline will accept 1 rep PE reads and automatically subsample the reads to make pseudoreps? Am I correct?

**Comment by leepc12** [comment]
Yes, pipeline generates two pseudos for each 1 rep. Pseudo thing has nothing to do with the number of replicates.

**Comment by yysheep2020** [comment]
If I use pre-trimed sequence data, I should set "atac.auto_detect_adapter" : false. SO it will skip the trim-adapter step. Am I right?

**Comment by leepc12** [comment]
Yes, set it as `false`. That's right.

**Comment by leepc12** [comment]
Closing due to long inactivity.
