### ISSUE TITLE
Dataset with Paired-End and Single End Data

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#240]
I have a dataset with a mix of paired-end and single-end data for the same biological replicate.  In an older version of the pipeline, this was handled by using the atac.fastqs_rep1_R1 and atac.fastqs_rep1_R2 inputs for the paired-end data and the atac.fastqs_rep1 for the single-end data.  The atac.fastqs_rep1 seems to no longer be an input option for the json file.  How should I handle this now?  Should I add the single-end data to the fastq.gz list for atac.fastqs_rep1_R1, or do I need to do something else?  Thanks so much!

**Comment by leepc12** [comment]
If you have SE rep1 and PE rep2.
```javascript
{
    "atac.fastqs_rep1_R1": [ ],
    "atac.fastqs_rep2_R1": [ ],
    "atac.fastqs_rep2_R2": [ ],
    "atac.paired_ends: [ false, true ],
}
```

**Comment by imk1** [comment]
I have both SE and PE for replicate 1.  How should I handle that?  Thanks!

**Comment by leepc12** [comment]
I think that cannot be handled by pipeline.

**Comment by imk1** [comment]
Thanks for clarifying!
