### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by Kmrouj** [ENCODE-DCC/atac-seq-pipeline#241]
**Describe the bug**
A clear and concise description of what the problem is.

**OS/Platform**
- OS/Platform: [e.g. Ubuntu 16.04, Google Cloud, Stanford Sherlock/SCG cluster, ...]
- Conda version: If you used Conda (`$ conda --version`).
- Pipeline version: [e.g. v1.5.3]
- Caper version: [e.g. v0.6.0]

**Caper configuration file**
Paste contents of `~/.caper/default.conf`.

**Input JSON file**
Paste contents of your input JSON file.

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

**Comment by Kmrouj** [comment]
Hi, I'm trying to install all the elements required for using the pipeline. However, when I try to execute the $ 'bash scripts/install_conda_env.sh' command I keep receiving an Error.
Here are my command lines (on my mac terminal)
'cd /Users/karimmrouj/ENCODE-DCC-atac-seq-pipeline-46f2a92/scripts 
bash scripts/install_conda_env.sh'  
Thank you

**Comment by leepc12** [comment]
Run it on repo's root directory (not on `scripts/`) or run `bash install_conda_env.sh` on `scripts/`.

**Comment by Kmrouj** [comment]
After running on the root directory here's the return. I can not tell if it was installed or not.
<img width="1126" alt="Screen Shot 2020-04-01 at 10 26 52 AM" src="https://user-images.githubusercontent.com/56937863/78167552-8b5be200-7403-11ea-804f-4519544c348f.png">

**Comment by leepc12** [comment]
Please install GNU `grep` by using `home brew` or something. OSX's default `grep` cannot parse Perl-style reg-ex.

**Comment by Kmrouj** [comment]
Unfortunately, it did not help. So after uninstalling grep and  installing it again using home brew and then running 'cd /Users/karimmrouj/ENCODE-DCC-atac-seq-pipeline-46f2a92
bash scripts/install_conda_env.sh' I still have the same error

**Comment by leepc12** [comment]
Can you edit two bash scripts? Basically OSX's `grep` is based on extended reg-ex, which does not have `-P` parameter (Perl-style reg-ex). So we are going to replace `grep -P` with `grep -E` and also replace `\s` that is not supported by extended reg-ex.

Line 19-20 of `install_conda_env.sh`.
Replace
```bash
CONDA_PREFIX_PY3=$(conda env list | grep -P "\b${CONDA_ENV_PY3}\s" | awk '{if (NF==3) print $3; else print $2}')
CONDA_PREFIX_PY2=$(conda env list | grep -P "\b${CONDA_ENV_PY2}\s" | awk '{if (NF==3) print $3; else print $2}')
```
with:
```bash
CONDA_PREFIX_PY3=$(conda env list | grep -E "\b${CONDA_ENV_PY3}[[:space:]]\s" | awk '{if (NF==3) print $3; else print $2}')
CONDA_PREFIX_PY2=$(conda env list | grep -E "\b${CONDA_ENV_PY2}[[:space:]]" | awk '{if (NF==3) print $3; else print $2}')
```

Line 11 of `update_conda_env.sh`.
Replace
```bash
CONDA_PREFIX_PY3=$(conda env list | grep -P "\b${CONDA_ENV_PY3}\s" | awk '{if (NF==3) print $3; else print $2}')
```
with 
```bash
CONDA_PREFIX_PY3=$(conda env list | grep -E "\b${CONDA_ENV_PY3}[[:space:]]" | awk '{if (NF==3) print $3; else print $2}')
```

**Comment by Kmrouj** [comment]
Indeed it did solve the problem, successfully installed 
Thanks a lot for your help,  I will now move to Caper configuration (I hope it's not difficult) 
<img width="866" alt="Screen Shot 2020-04-01 at 11 27 15 AM" src="https://user-images.githubusercontent.com/56937863/78173302-5b650c80-740c-11ea-9539-2776857ce161.png">
