### ISSUE TITLE
macs2_signal_track_pooled failed

### ISSUE THREAD

**Issue by artnasamran** [ENCODE-DCC/atac-seq-pipeline#245]
**Describe the bug**
Received an error at the atac.macs2_signal_track_pooled step. The pipeline runs without any errors when using the test input file (https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ_subsampled_caper.json) using the same set up. Can you please help me debug this?

**OS/Platform**
- OS/Platform: Amazon Linux 2
- Conda version: conda 4.8.2
- Pipeline version: v1.7.0
- Caper version: 0.7.0

**Caper configuration file**
Contents of `~/.caper/default.conf`:
backend=aws
aws-batch-arn=arn:aws:batch:us-east-2:097051626737:job-queue/default-08c06710-6e1f-11ea-a336-023ebc410218
aws-region=us-east-2
out-s3-bucket=s3://x/

# DO NOT use /tmp here
# Caper stores all important temp files and cached big data files here
# If not defined, Caper will make .caper_tmp/ on your local output directory
# which is defined by out-dir, --out-dir or $CWD
# Use a local absolute path here
tmp-dir=/home/ec2-user/data/x/

cromwell=/home/ec2-user/.caper/cromwell_jar/cromwell-47.jar
womtool=/home/ec2-user/.caper/womtool_jar/womtool-47.jar

**Input JSON file**
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/hg38_caper.tsv",
    "atac.fastqs_rep1_R1" : [ 
        "https://x/NPB_3124_R1.fastq.gz" 
    ],
    "atac.fastqs_rep1_R2" : [ 
        "https://x/NPB_3124_R2.fastq.gz" 
    ],
    "atac.fastqs_rep2_R1" : [ 
        "https://x/NPB_2585_R1.fastq.gz" 
    ],
    "atac.fastqs_rep2_R2" : [ 
        "https://x/NPB_2585_R2.fastq.gz" 
    ],
    "atac.paired_end" : true,
    "atac.auto_detect_adapter" : true,
    "atac.title" : "20200318_x_atacseq",
    "atac.description" : "x"
}

**Error log**
Output of $ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]:
[Caper] troubleshooting 9b88156e-0200-45d0-a120-041905562298 ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.macs2_signal_track_pooled:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]

atac.macs2_signal_track_pooled Failed. SHARD_IDX=-1, RC=1, JOB_ID=46373195-0822-46e7-8df5-45bd1fe8456f, RUN_START=2020-04-03T19:31:34.234Z, RUN_END=2020-04-03T21:24:00.268Z, STDOUT=s3://x/atac/9b88156e-0200-45d0-a120-041905562298/call-macs2_signal_track_pooled/macs2_signal_track_pooled-stdout.log, STDERR=s3://x/atac/9b88156e-0200-45d0-a120-041905562298/call-macs2_signal_track_pooled/macs2_signal_track_pooled-stderr.log
[CaperURI] copying from s3 to local, src: s3://x/atac/9b88156e-0200-45d0-a120-041905562298/call-macs2_signal_track_pooled/macs2_signal_track_pooled-stderr.log
[CaperURI] copying skipped, target: /home/ec2-user/data/x/atac/9b88156e-0200-45d0-a120-041905562298/call-macs2_signal_track_pooled/macs2_signal_track_pooled-stderr.log
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_task_macs2_signal_track_atac.py", line 171, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_task_macs2_signal_track_atac.py", line 162, in main
    args.smooth_win, args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_task_macs2_signal_track_atac.py", line 94, in macs2_signal_track
    run_shell_cmd(cmd5)
  File "/software/atac-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=24, PGID=24, RC=137
STDERR=/bin/bash: line 1:    25 Killed                  LC_COLLATE=C sort -k1,1 -k2,2n basename_prefix.pooled.fc.signal.bedgraph
        26 Done                    | awk 'BEGIN{OFS="\t"}{if (NR==1 || NR>1 && (prev_chr!=$1 || prev_chr==$1 && prev_chr_e<=$2)) {print $0}; prev_chr=$1; prev_chr_e=$3;}' > basename_prefix.pooled.fc.signal.srt.bedgraph
STDOUT=

I replaced some names in URLs with "x" for privacy. Please let me know if you need any additional information.

**Comment by leepc12** [comment]
```
/bin/bash: line 1: 25 Killed LC_COLLATE=C sort -k1,1 -k2,2n
```
Your job was killed in an instance. I think it's OOM. Increase `atac.macs2_signal_track_mem_mb` to 32000 and try again. It's 16000 by default.

**Comment by artnasamran** [comment]
Thanks! I'll try that. Is there a way to rerun the workflow starting from a specific step?

I'm getting a new error in which the rerun fails on the atac_align step. Here's the debug output of the job:
Found failures:
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "[Attempted 1 time(s)] - IOException: Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-rc.txt",
                "causedBy": [
                    {
                        "message": "Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-rc.txt",
                        "causedBy": [
                            {
                                "message": "s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-rc.txt",
                                "causedBy": []
                            }
                        ]
                    }
                ]
            },
            {
                "causedBy": [
                    {
                        "causedBy": [
                            {
                                "causedBy": [],
                                "message": "s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-rc.txt"
                            }
                        ],
                        "message": "Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-rc.txt"
                    }
                ],
                "message": "[Attempted 1 time(s)] - IOException: Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-rc.txt"
            },
            {
                "causedBy": [
                    {
                        "causedBy": [
                            {
                                "causedBy": [],
                                "message": "s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-rc.txt"
                            }
                        ],
                        "message": "Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-rc.txt"
                    }
                ],
                "message": "[Attempted 1 time(s)] - IOException: Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-rc.txt"
            },
            {
                "message": "[Attempted 1 time(s)] - IOException: Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-rc.txt",
                "causedBy": [
                    {
                        "message": "Could not read from s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-rc.txt: s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-rc.txt",
                        "causedBy": [
                            {
                                "message": "s3://s3.amazonaws.com/x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-rc.txt",
                                "causedBy": []
                            }
                        ]
                    }
                ]
            }
        ]
    }
]

atac.align_mito Failed. SHARD_IDX=0, RC=None, JOB_ID=289e0906-d3c1-4ba9-b11d-b1034de80d78, RUN_START=2020-04-07T05:18:13.793Z, RUN_END=2020-04-07T05:40:11.721Z, STDOUT=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-stdout.log, STDERR=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-0/align_mito-0-stderr.log

atac.align_mito Failed. SHARD_IDX=1, RC=None, JOB_ID=d9cc0a44-286d-4b49-b325-a48f4d350973, RUN_START=2020-04-07T05:18:15.803Z, RUN_END=2020-04-07T05:38:42.617Z, STDOUT=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-stdout.log, STDERR=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align_mito/shard-1/align_mito-1-stderr.log

atac.align Failed. SHARD_IDX=0, RC=None, JOB_ID=5322d2ea-4419-4be3-97e0-bcb14da268fa, RUN_START=2020-04-07T05:18:09.811Z, RUN_END=2020-04-07T05:36:44.876Z, STDOUT=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-stdout.log, STDERR=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-0/align-0-stderr.log

atac.align Failed. SHARD_IDX=1, RC=None, JOB_ID=41a966ee-18bc-4c86-a04c-6bfd098dca75, RUN_START=2020-04-07T05:18:11.806Z, RUN_END=2020-04-07T05:41:09.418Z, STDOUT=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-stdout.log, STDERR=s3://x/atac/c2a9a669-9946-4074-ad42-9cadaa9117f3/call-align/shard-1/align-1-stderr.log

**Comment by leepc12** [comment]
`align` is the first step of the pipeline. Something is wrong with your AWS/Caper configuration?

**Comment by artnasamran** [comment]
Previously, my set up successfully completed the test data run and all steps for my dataset except for atac.macs2_signal_track_pooled. Now it's continually failing on the first step despite no changes to the configuration. Any ideas of what could be causing this error?

**Comment by artnasamran** [comment]
Whenever I resubmit an atacseq job, call-read_genome_tsv and call-align succeed, but call-align_mito fails. The call-align_mito step fails on this error, "IOException: Could not read from s3://x/atac/f57bcec1-cf40-4efd-9e2e-c63bffa8a29d/call-align_mito/shard-1/align_mito-1-rc.txt: s3://s3.amazonaws.com/x/atac/f57bcec1-cf40-4efd-9e2e-c63bffa8a29d/call-align_mito/shard-1/align_mito-1-rc.txt"

The part that I don't understand is that all other steps are able to read and write to the same s3 directory. Do you have any advice/suggestions for debugging this aside from looking at caper debug and caper metadata?

**Comment by leepc12** [comment]
Can you try with this in your input JSON? We have a mirror for reference genome data on S3.
```
{
    "atac.genome_tsv": "s3://encode-pipeline-genome-data/genome_tsv/v1/hg38_aws.tsv"
}
```

**Comment by artnasamran** [comment]
Yes, this is the error that I get after switching the reference genome to the s3 address:
[CaperURI] read from s3, src: s3://encode-pipeline-genome-data/genome_tsv/v1/hg38_aws.tsv
download failed: s3://encode-pipeline-genome-data/genome_tsv/v1/hg38_aws.tsv to - An error occurred (403) when calling the HeadObject operation: Forbidden
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1269, in main
    c.submit()
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 393, in submit
    input_file = self.__create_input_json_file(tmp_dir)
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 671, in __create_input_json_file
    uri_type=uri_type, uri_exts=self._deepcopy_ext)
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 807, in deepcopy
    uri_type=uri_type, uri_exts=uri_exts)
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 776, in __deepcopy_json
    updated = recurse_dict(new_d, uri_type)
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 749, in recurse_dict
    d_parent_key=k, updated=updated)
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 758, in recurse_dict
    uri_type=uri_type, uri_exts=uri_exts)
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 810, in deepcopy
    uri_type=uri_type, uri_exts=uri_exts, delim='\t')
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 705, in __deepcopy_tsv
    contents = self.get_file_contents()
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 490, in get_file_contents
    self._uri, '-']).decode()
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/home/ec2-user/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['aws', 's3', 'cp', '--only-show-errors', 's3://encode-pipeline-genome-data/genome_tsv/v1/hg38_aws.tsv', '-']' returned non-zero exit status 1.

**Comment by leepc12** [comment]
Sorry, just made those S3 buckets public. Can you try again?

**Comment by artnasamran** [comment]
I tried it again and it's running. I also changed atac.macs2_signal_track_mem_mb to 64000 since the previous run failed at the same spot with the same error:
STDERR=/bin/bash: line 1:    25 Killed                  LC_COLLATE=C sort -k1,1 -k2,2n NPB_3124_R1.trim.nodup.no_chrM_MT.tn5.fc.signal.bedgraph
        26 Done                    | awk 'BEGIN{OFS="\t"}{if (NR==1 || NR>1 && (prev_chr!=$1 || prev_chr==$1 && prev_chr_e<=$2)) {print $0}; prev_chr=$1; prev_chr_e=$3;}' > NPB_3124_R1.trim.nodup.no_chrM_MT.tn5.fc.signal.srt.bedgraph

**Comment by leepc12** [comment]
I think there are two mixed problems 1) `Killed LC_COLLATE=C sort` and 2) `IOException: Could not read from`. I think 2) is a temporary problem on AWS/S3. I think 1) is OOM. Please increase memory further.

**Comment by artnasamran** [comment]
It successfully ran after increasing atac.macs2_signal_track_mem_mb to 128000. Also, the s3 problem (not the reference on private setting), seems to go away if I set a new output directory every run. This leads me to 2 follow up questions for future runs of the pipeline.
1) Can you recommend a way to calculate the memory required for the signal track step based on the size of the starting fastq files? In this example, each fastq was ~4-5GB x2 for paired end.
2) Are there instructions or is it possible to start the pipeline at a specified step? For example, my initial run was failing at the signal track and pooled signal track step. Could I have restarted the pipeline using the previous alignments that succeeded?

Thanks for your help thus far. I greatly appreciate it.

**Comment by leepc12** [comment]
Thanks for reporting it.

1. Currently there is no way to estimate it. If default memory is not enough you can gradually increase it and see if it works. I have a plan to automatically determining required resources for each task. It's in my todo list.

2. No, you cannot start from a specific step if your input JSON has FASTQs only. If you have setup your Cromwell's DB correctly (`--db` and other parameters according to chosen DB type: e.g. `--db file --file-db [DB_PATH_PREFIX]`). You can simply re-run with the same command line then Cromwell will start over but re-use outputs from previous failed workflows.

**Comment by artnasamran** [comment]
Thanks! I'll try --db in future runs.
