### ISSUE TITLE
Naming convention with pooled files

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#246]
Is line 40 of `encode_task_pool_ta.py` supposed to be 
```prefix = os.path.join(out_dir,basename_prefix)```
instead of
```prefix = os.path.join(out_dir,'basename_prefix')```
?

I think a similar bug is in another script but can't find it. 

RE this chunk:
```
def pool_ta(tas, col, basename_prefix, out_dir):
    if len(tas) > 1:
        if basename_prefix is not None:
            prefix = os.path.join(out_dir,'basename_prefix')
        else:
            prefix = os.path.join(out_dir,
                              os.path.basename(strip_ext_ta(tas[0])))
        pooled_ta = '{}.pooled.tagAlign.gz'.format(prefix)
...
```
After running the pipeline with replicates, we get signal file names like `signal/pooled-rep/basename_prefix.pooled.pval.signal.bigwig` and `peak/pooled-rep/basename_prefix.pooled.pval0.01.300K.narrowPeak.gz` after running Croo. 

**OS/Platform**
- OS/Platform: Google Cloud
- Pipeline version: 1.7.0
- Croo version: 0.3.4

**Comment by leepc12** [comment]
Sorry about this. This is already fixed in the dev branch and is currently under our code review process. Will be merged soon to make a new release.
https://github.com/ENCODE-DCC/atac-seq-pipeline/pull/243/commits/5550f08994b8ce96230cd67fa8c2dc1493ab0963

**Comment by nicolerg** [comment]
Thank you!
