### ISSUE TITLE
version cromwell

### ISSUE THREAD

**Issue by gmgitx** [ENCODE-DCC/atac-seq-pipeline#25]
Very nice tool, thanks for valuable work! I used this pipeline and run on slurm, for this goal, I followed official guidances, seems two guidances:

one is [tutorial_slurm.md](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/tutorial_slurm.md) the other is [slurm](https://encode-dcc.github.io/wdl-pipelines/install.html#slurm) 

At first, I think it's good to complement each other, but there are something conflict, my question: 1 if I meet this problem, I follow which guide? 2 Now I use which cromwell version here? 3  Should I install [WOMtool](https://cromwell.readthedocs.io/en/develop/WOMtool/) and related toolchain (scala...) for use cromwell to finish this pipeline, it also make me feel very confused? Thank you!!!

**Comment by leepc12** [comment]
You need to follow [tutorial_slurm.md](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/tutorial_slurm.md). The latter is an old one. We will deprecate it.
