### ISSUE TITLE
How to restart a failed run in local backend?

### ISSUE THREAD

**Issue by lijinbio** [ENCODE-DCC/atac-seq-pipeline#255]
Hi all,

I am running a single workflow in the local backend without a server. It has finished the long-time alignment step but failed in a downstream step. I am wondering if `caper run` can restart the workflow by skipping those successfully finished steps, such as the alignment step. Thank you.

Best regards,
Jin

**Comment by leepc12** [comment]
Please read [this section](https://github.com/ENCODE-DCC/caper/blob/master/README.md#metadata-database).

**Comment by lijinbio** [comment]
It works. Thanks for your info.
