### ISSUE TITLE
To use atac-seq-pipeline results to detect differential ATAC regions.

### ISSUE THREAD

**Issue by lijinbio** [ENCODE-DCC/atac-seq-pipeline#258]
Hi all,

I have ATAC-Seq data in two biological conditions, and I want to detect differential ATAC regions between the two conditions. May I ask how could I use atac-seq-pipeline to do the differential analysis? Thank you.

Best regards,
Jin

**Comment by leepc12** [comment]
Run a pipeline for each condition and compare optimal peaks between two pipelines.

**Comment by lijinbio** [comment]
> Run a pipeline for each condition and compare optimal peaks between two pipelines.

Does the atac-seq-pipeline support the comparison of optimal peaks between two pipelines?

**Comment by leepc12** [comment]
If you meant biological replicates by biological conditions then run a single pipeline with two replicates (`rep1`, `rep2` in input JSON). Pipeline can do differential analysis between two biological replicates.

Otherwise, use other tools to compare narrowPeaks from two pipelines.

**Comment by lijinbio** [comment]
Thank you for your explanation. Your explanation confirmed my understanding of what the atac-seq-pipeline has done. I may use other tools to compare narrowPeaks from two pipelines. Thank you.
