### ISSUE TITLE
Rename Optimal Peaks

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/atac-seq-pipeline#260]
Hello @leepc12, 

Is there any reason the optimal peaks from "reproducibility_overlap" are not prefixed with the sample name? 

This is a very important and useful feature of the BAM files which are prefixed with the sample ID of the FASTQs.

**Comment by leepc12** [comment]
`reproducibility_overlap` is an analysis that take into account all replicates, their pseudos and pooled replicate. So there are too many FASTQs involved in that. That's why we don't prefix it.
