### ISSUE TITLE
Add BAMScale?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/atac-seq-pipeline#263]
Is there potential to add BAMScale in the future for creating bigWigs? 
[BAMScale](https://github.com/ncbi/BAMscale)

**Comment by YogiOnBioinformatics** [comment]
just wanted to follow up on this.

**Comment by leepc12** [comment]
Sorry, we currently don't have a plan for this.

**Comment by akundaje** [comment]
I would like to add that if you or others added features to the code base and made a pull request, we would be happy to test, verify and include if it provides useful functionality.

**Comment by YogiOnBioinformatics** [comment]
alright sounds good! 
if we do add that functionality ourselves, i can open a PR about it. 

thanks as always for this great pipeline you've provided :)!
