### ISSUE TITLE
Calling Peaks with TagAlign instead of BAM?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/atac-seq-pipeline#265]
From my understanding, in version 1.7.1 of this pipeline, peaks are initially called from the TagAlign files. 
As well, all subsequent filtering of the `narrowPeak` files is based off of the initial TagAlign file. 

What is the reason for this? 
Why are the most filtered BAMs from `task filter (call-filter/)` not used for peak calling?

**Comment by leepc12** [comment]
TAG-ALIGN is a simplified (including read's genome coordinate/strand only) BED version of that filtered BAM and MACS2 peak caller can take in either TAG-ALIGN or BAM. They are equivalent.

Also, pipeline have some useful parameters for TAG-ALIGN. e.g. subsampling, you can subsample TAG-ALIGN and pass it to MACS2 peak caller.

**Comment by YogiOnBioinformatics** [comment]
Thanks for the info and for the quick response 😄 

This is actually part of a broader issue I'm having. 
My lab decided to upgrade this pipeline from `v 1.1.7` to `v 1.7.1`. 

We found relatively low overlap between filtered peak files comparing the older and newer pipeline versions. 
We are better trying to understand why this might be. 

I've looked through the many versions changelogs and I understand there are quite a few new steps and many tool upgrades. 

Still even with that said, do you have any suggestions for understanding what exactly is causing significant differences in the filtered peak files comparing the older and newer pipeline versions?

**Comment by YogiOnBioinformatics** [comment]
don't mean to bother. 
just wanted to follow up on this.

**Comment by akundaje** [comment]
The main changes driving differences in peak calls from 1.1.7 to 1.7 would be
- Allowing upto 4 multimapping reads to prevent mappability holes (this changes the filtering of the BAM files)
- Reducing the raw peak calling p-value thresholds from 0.1 to 0.05 (more stringent peak calls)

There are also upgrades of versions of various tools that would drive some differences but I believe these two changes would cause the biggest differences between those two versions.

What are you peak summaries for your dataset and the mutual overlap between the two versions.

**Comment by YogiOnBioinformatics** [comment]
@akundaje thank you so much for this explanation!
Just two questions about the p-value thresholds... 
1. Which specific `task` does the p-value threshold come into play? 
2. Is there any way to change this threshold?

In terms of my dataset...
I used 100 samples run with the 1.1.7 and 1.7.1 versions and then for each set of most filtered peaks (from `call-reproducibility_overlap`), I ran [bedtools jaccard](https://bedtools.readthedocs.io/en/latest/content/tools/jaccard.html). 

Specifically, I ran bedtools Jaccard between each set of peaks for each sample ran with the two different pipeline versions. Hopefully that makes sense! 
From that, I was able to calculate the median of all these 100 Jaccard statistics and the median absolute deviation. 

MEDIAN: 0.642921 (median absolute deviation: 0.0168475)

**Comment by akundaje** [comment]
Yes you should be able to change the pvalue threshold in the raw peak
calling step.

Jin - can point you to exactly how

**Comment by YogiOnBioinformatics** [comment]
Sounds good, thanks again @akundaje! 
Just curious but do you think the median value I put up above seems suspicious to you?

I will wait for @leepc12 to show me how to change the p-value threshold.

**Comment by leepc12** [comment]
That is controlled by `atac.pval_thresh` in your input JSON, this parameter will be passed to `macs2 callpeak`.

**Comment by akundaje** [comment]
I can't interpret the median values. If for a few datasets you post
- (A) #peaks from v1.1.7
- (B) #peaks from v1.7.4
- #peaks of A that overlap peaks in B
- #peaks of B that overlap peaks in A

**Comment by YogiOnBioinformatics** [comment]
I will try to get those numbers over if I can. 

A question for both @leepc12 and @akundaje. 

You mentioned that in `version 1.7.1`, `macs2 callpeak` is called with a p-value of 0.05. 
Based on what I'm seeing, `version 1.7.1` uses a p-value of 0.01

Just want to make sure there isn't a misunderstanding here?

**Comment by leepc12** [comment]
@YogiOnBioinformatics : That's right. `atac.pval_thresh` has been fixed at `0.01`.

I think @akundaje meant IDR threshold (`atac.idr_thresh`). It changed from `0.1` to `0.05`.

**Comment by YogiOnBioinformatics** [comment]
Thanks very much! 

One other thing. 
I wanted to compare the number of `Total Reads` from the filtered and deduped BAMs for each sample between analysis of each of the pipeline versions. 
I used the data from the `qc.json` file to accomplish this. 

Hence, I subtracted the number of `Total Reads` from the most filtered BAMs between BAMs retrieved from each pipeline version. 
I did this for 100 samples and found the average difference in `Total Reads` between version `1.7.1` and `1.1.7` was **3823343**

Between `version 1.1.7` and `version 1.7.1` were there major differences in filtering and deduping BAMs? 
Major changes in either code or big jumps in tools' versions?

**Comment by YogiOnBioinformatics** [comment]
sorry to bother. 
just wanted to follow up on this.

**Comment by leepc12** [comment]
We switched from `samtools flagstat` to [`SAMstats`](https://github.com/kundajelab/SAMstats). 
Other than this please see release notes (e.g. version changes).

**Comment by akundaje** [comment]
Yeah to add to it further

Samtools flagstat does NOT report the read statistics correctly
particularly in how it counts multimapping reads.

We modified it and released SamStat that reports read statistics correctly.

So you will see differences in numbers. The SamStat numbers are more
correct.

-Anshul.

**Comment by YogiOnBioinformatics** [comment]
ah awesome! 

thanks for all the info guys! 
I'll close this in a bit if nothing else pops up. 

Thanks as always for providing this pipeline 😄

**Comment by leepc12** [comment]
Closing due to long inactivity.

**Comment by YogiOnBioinformatics** [comment]
Yes good call @leepc12! 
Sorry I didn't close it before.

**Comment by YogiOnBioinformatics** [comment]
@akundaje @leepc12  your message about Samtools Flagstat not being good in `v1.1.7` is of interest to me. 

To refresh about this thread, our lab/consortium was looking at upgrading our pipeline version to `v1.7.1`.

We took 100 samples and ran it through each version of the pipeline. 
To understand causal sources of variation, we looked at some descriptive statistics. 

I've attached a bar graph with median difference values between samples using the `qc.json` file for each pipeline version.
(i.e. 
**median[**
      `sample1_v1.1.7` Total Reads - `sample1_v1.7.1` Total Reads
      `sample2_v1.1.7` Total Reads - `sample_v1.7.1` Total Reads
etc....**]**
)

We looked at:  

- Total Reads 
- Mapped Reads 
- Final Reads
- Filtered Reads

**Is the massive difference in Total Reads and Mapped Reads a result of `v1.1.7 Samtools flagstat` issues?**


![Screenshot (23)](https://user-images.githubusercontent.com/38919947/94381601-f3b42380-0107-11eb-9a29-b0a1a9a47fe6.png)

**Comment by akundaje** [comment]
We switched from reporting the samtools flagstat outputs to reporting the
actual alignments after removing redundant reporting that is present in
samtools flagstat. We call this new tool 'samstat'. You can of course run
samtools flagstat on the BAMs from the new pipeline to compare the samtools
flagstat results head to head with the old pipeline. That should tell you
if the difference you are observing is a flagstat vs samstat effect (which
should be expected) or whether there are actually differences in the
alignments between the two pipelines.

The fact that the final read stats match up well tells me that it is just a
flagstat vs samstat difference. Samstat is the more correct reporting of
alignments.

-Anshul.

**Comment by YogiOnBioinformatics** [comment]
Awesome! 
For the `v1.1.7` pipeline, if I wanted to get the true total reads and mapped reads... 
I could definitely use SAMstat. 
However, couldn't I also use the `Bowtie2` alignment log?

That shouldn't be erroneous right since it's from `Bowtie2` and not `flagstat`?

**Comment by leepc12** [comment]
But we do the same `SAMstat`ting on both unfiltered raw BAM and deduped/filtered BAM and compare them. We have bowtie2 log for the raw BAM only.

v1.1.7 generates bowtie2 log https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/v1.1.7/atac.wdl#L1294
So parse this file to get number of reads.

Find this file in `your output root directory/WORKFLOW_ID/call-bowtie2/shard-[REPLICATE_ID_ZERO_BASED]/glob*/*.log`.

**Comment by YogiOnBioinformatics** [comment]
Thanks so much!
