### ISSUE TITLE
tn5 shift

### ISSUE THREAD

**Issue by chesi** [ENCODE-DCC/atac-seq-pipeline#270]
Hello,
I am running the pipeline starting from 2 *R1.PE2SE.nodup.tn5.tagAlign.gz tag input files.
I suppose these are already tn5 shifted, but I noticed that the first step when I run is a "shift_tag" job.
So they get shifted twice? Is there a way to disable the tn5 shift step if it's already been performed before?

Thanks!
A.

**Comment by chesi** [comment]
I attach the log file. shift_tag is the first job run.
[bds.log.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/5120454/bds.log.txt)

**Comment by leepc12** [comment]
BDS pipeline has been deprecated long time ago. We no longer maintain it.
One possible workaround should be setting pipeline type as `dnase`.
Add `-dnase_seq` to your command line. Then TN5 shifting will be skipped.

**Comment by chesi** [comment]
OK, thanks!
