### ISSUE TITLE
Documentation of output files

### ISSUE THREAD

**Issue by olechnwin** [ENCODE-DCC/atac-seq-pipeline#271]
Hi,
Can someone please let me know where is the documentation of what each column is in the output files generated. I am currently wondering about the columns in overlap_reproducibility/overlap.optimal_peak.narrowPeak.gz which was recommended as the "best peaks".  However, I'm most likely will want to explore other output files in the future as well.

Thank you!

**Comment by leepc12** [comment]
It's narrowPeak. See its suffix in the file name. https://genome.ucsc.edu/FAQ/FAQformat.html#format12

**Comment by olechnwin** [comment]
Thanks for your quick reply. So, there isn't any documentation of what the columns are for each specific output files.
Regarding overlap.optimal_peak.narrowPeak.gz, since this file is generated by overlapping peaks in my case I assumed they are from the two replicates I have. Therefore, I'm not sure whether the genomic location refers to one replicate peak or overlap/merged replicates peaks and what about the p-values, signal values are they averages of two replicates?

**Comment by akundaje** [comment]
They are peaks (coordinates and scores) from pooled replicates (reads
pooled across all replicates) that pass IDR or overlap reproducibility
criteria wrt peaks from true replicates and pseudo replicates

The exact steps are in the protocol specification linked on the main README.

"The ATAC-seq pipeline protocol specification is here
<https://docs.google.com/document/d/1f0Cm4vRyDQDu0bMehHD7P7KOMxTOP-HiNoIvL1VcBt8/edit?usp=sharing>.
Some parts of the ATAC-seq pipeline were developed in collaboration with
Jason Buenrostro, Alicia Schep and Will Greenleaf at Stanford."


https://docs.google.com/document/d/1f0Cm4vRyDQDu0bMehHD7P7KOMxTOP-HiNoIvL1VcBt8/edit?usp=sharing

Anshul

**Comment by olechnwin** [comment]
Thank you so much for your reply. Just a quick clarification, so the peaks information like pvalues, signalValues would be from each respective peaks from true replicates and pseudo replicates?

Please don't take this as a bad thing because I find the pipeline very useful and I understand how difficult keeping a good documentation. In the ATAC-seq pipeline protocol, it mentioned:  "IDR Threshold: Use IDR threshold of 10% for all pairwise analyse". There is another reference for this "Get peaks passing IDR threshold of 10%". However, in the filename and in the commands it mentioned "IDR_THRESH=0.05". Also, ${REP1_VS_REP2}.IDR0.05.narrowPeak.gz output of IDR was said to have 19 columns but there is only 10 columns. Is there any plan on updating the pipeline?

**Comment by akundaje** [comment]
> Thank you so much for your reply. Just a quick clarification, so the peaks
> information like pvalues, signalValues would be from each respective peaks
> from true replicates and pseudo replicates?Please don't take this as a bad
> thing because I find the pipeline very useful and I understand how
> difficult keeping a good documentation. In the ATAC-seq pipeline protocol,
> it mentioned: "IDR Threshold: Use IDR threshold of 10% for all pairwise
> analyse". There is another reference for this "Get peaks passing IDR
> threshold of 10%". However, in the filename and in the commands it
> mentioned "IDR_THRESH=0.05". Also, ${REP1_VS_REP2}.IDR0.05.narrowPeak.gz
> output of IDR was said to have 19 columns but there is only 10 columns. Is
> there any plan on updating the pipeline?
>

So the way it works is
1. Call peaks on the pooled data with relaxed thresholds pval < 0.01 (P).
Use upto top 300K peaks.
2. Call peaks on true replicates with relaxed thresholds (R1, R2). Use upto
top 300K peaks.
3. Call peaks on pooled pseudo-replicates with relaxed thresholds (PR1,
PR2). Use upto top 300K peaks.
Pooled pseudoreps are generated by taking the pooled reads and
randomly sampling into two disjoint sets of reads. The
pooled-pseudoreps hence represent only sampling effects.
4. Find all peaks in P that overlap any peak in R1 AND R2 (this is
conservative overlap peak set COS). Notice that the peak coordinates and
all other columns eg. pvalues etc. in COS are hence all coming from P. Just
the subset of peaks in P that are reproducible.
5. Find all peaks in P that overlap any peak in PR1 AND PR2 (this is the
pseudoreplicate overlap peak set POS)
6. Compare number of peaks in POS vs COS. The maximum of the two is
referred to as the "optimal naive overlap peak set"

Now for IDR. Any IDR run takes 3 peak sets.
a. A master peak set which is the pooled set of peaks P
b. a pair of peak sets from true reps (R1, R2) or pseudoreps (PR1, PR2)
IDR will find a subset of peaks in P that are reproducible AND rank
consistent.  So the IDR peak set is a subset of P and a subset of COS/POS.
The raw output of IDR has 21 columns that capture all the relevant columns
for each peak in P, its IDR scores and the overlap peaks in each of the
reps. That output is infact produced by the pipeline in one of the
directories. But then the global IDR score column is thresholded and only
the subset of peaks in P that pass that threshold are retained as IDR
peaks. Hence, the final IDR threshold peaks are in narrowPeak file format
with 10 columns that are directly from P.

7. Run IDR on P, R1, R2. The peaks in P that pass IDR < 0.05 are called the
conservative IDR peak set (CIS)
8.  Run IDR on P, PR1, PR2. The peaks in P that pass IDR < 0.05 are called
the pseudorep IDR peak set (PIS)
9.  Compare number of peaks in CIS vs PIS. The maximum of the two is
referred to as the "optimal IDR peak set"

Sorry for the small errors in the google doc pipeline spec. Some of the
parameters have changed over the versions and some of the comments were not
edited. The code contents are up to date. They are meant to give a
line-by-line walk through of the pipeline.

We have more detailed protocols paper coming out soon.

-Anshul.

**Comment by olechnwin** [comment]
wow! Thank you very much for a very detailed explanation. That is very helpful.

Another clarification question: so the best peak set (i.e. "overlap.optimal_peak.narrowPeak.gz") is the "optimal IDR peak set" in step 9? or the "optimal naive overlap peak set" in step 6?

Thank you for keeping the code contents up to date. They are helpful to see how each step was run in the pipeline.

**Comment by YogiOnBioinformatics** [comment]
To comment on this @akundaje , I really am excited to read the protocols paper! 
Is there any place that you will announce it? 

I really do want to read it!

**Comment by akundaje** [comment]
Hope to have the preprint out by Oct 1. Will announce it on twitter and add
the link to the repos.

**Comment by YogiOnBioinformatics** [comment]
?Awesome! Looking forward to it and congrats!


________________________________
Yogindra Raghav
YogiOnBioinformatics(tm)

Massachusetts Institute of Technology (MIT)
Department of Biological Engineering
Lab of Dr. Ernest Fraenkel

Affiliate at Broad Institute of MIT and Harvard

LinkedIn: YogiOnBioinformatics<https://www.linkedin.com/in/yogionbioinformatics/>
GitHub: YogiOnBioinformatics<https://github.com/YogiOnBioinformatics>

Email: yraghav@mit.edu
Alternate Email: yraghav@broadinstitute.org
Office Address: 21 Ames St #16-244, Cambridge, MA 02142

________________________________
