### ISSUE TITLE
Can't install conda environment

### ISSUE THREAD

**Issue by xc1573** [ENCODE-DCC/atac-seq-pipeline#275]
Hi Guys! 
I was trying to install the pipeline conda environment on the HPC but I was stuck at the fifth step which is Install pipeline's Conda environment. I tried bash scripts/uninstall_conda_env.sh but I get an error saying  bash: scripts/uninstall_conda_env.sh: No such file or directory. I didn't find out any script folder under my miniconda3 folder.
Does anyone know how to fix it？Thanks a lot!

**Comment by leepc12** [comment]
`scripts/uninstall_conda_env.sh` is on pipeline's git directory.
When you install Conda environment on HPCs. Do it on a compute node.
Your session can be killed if you do it on a login node.

**Comment by xc1573** [comment]
yeah thanks for your reply ! I installed it successfully now.

**Comment by leepc12** [comment]
That sounds great.
