### ISSUE TITLE
Cutadapt not found

### ISSUE THREAD

**Issue by giardine** [ENCODE-DCC/atac-seq-pipeline#278]
I am getting errors when trying to run the pipeline.  "cutadapt: command not found"  I do a conda activate encode-atac-seq-pipeline, and cutadapt is found just before running caper run.  Our scheduling system is Torque so I installed as local and wrote my own submission script.  The other problem I had during install is that my home disk space is full so I had to write to a different directory.  I put a symlink in for .caper.  

## 
- OS/Platform: Torque cluster (RedHat 6)
- Conda version: 4.8.3
- Pipeline version: v1.8.0
- Caper version: v1.1.0

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
backend=local
local-hash-strat=path+modtime
local-loc-dir=
cromwell=/storage/home/bmg137/.caper/cromwell_jar/cromwell-52.jar
womtool=/storage/home/bmg137/.caper/womtool_jar/womtool-52.jar

## **Input JSON file**
Paste contents of your input JSON file.
This is not relevent to the error.

##Torque script
cd /gpfs/scratch/bmg137/production/dhs/atac/CD34/hg38/2880_2882_2884
export PATH="/storage/work/bmg137/miniconda2w/bin:$PATH"
conda activate encode-atac-seq-pipeline
which cutadapt
caper run /storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/atac.wdl -i /gpfs/scratch/bmg137/production/dhs/atac/CD34/hg38/2880_2882_2884/2880.json
exit

## **Troubleshooting result**

If you ran `caper run` without Caper server then Caper automatically runs a troubleshooter for failed workflows. Find troubleshooting result in the bottom of Caper's screen log.

Paste troubleshooting result.
* Started troubleshooting workflow: id=f72e56b6-2e71-45cf-9a49-690803bfb7ff, status=Failed
* Found failures JSON object.
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Job atac.align_mito:1:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            },
            {
                "causedBy": [],
                "message": "Job atac.align_mito:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            },
....
==== NAME=atac.align_mito, STATUS=RetryableFailure, PARENT=
SHARD_IDX=0, RC=1, JOB_ID=110883
START=2020-09-16T12:08:33.972Z, END=2020-09-16T12:08:47.661Z
STDOUT=/gpfs/scratch/bmg137/production/dhs/atac/CD34/hg38/2880_2882_2884/atac/f72e56b6-2e71-45cf-9a49-690803bfb7ff/call-align_mito/shard-0/execution/stdout
STDERR=/gpfs/scratch/bmg137/production/dhs/atac/CD34/hg38/2880_2882_2884/atac/f72e56b6-2e71-45cf-9a49-690803bfb7ff/call-align_mito/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/src/encode_task_trim_adapter.py", line 214, in <module>
    main()
  File "/storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/src/encode_task_trim_adapter.py", line 182, in main
    args.out_dir)
  File "/storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/src/encode_task_trim_adapter.py", line 129, in trim_adapter_pe
    run_shell_cmd(cmd)
  File "/storage/work/b/bmg137/encode/atacWorkflow/atac-seq-pipeline/src/encode_lib_common.py", line 331, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=110967, PGID=110967, RC=127, DURATION_SEC=0.2
STDERR=/bin/bash: line 1: cutadapt: command not found
STDOUT=
....

**Comment by leepc12** [comment]
That means pipeline ran without the environment.
Try with `source activate` instead of `conda activate`.
Also, if you have Singularity then try with `--singualrity`.

**Comment by giardine** [comment]
When I used source activate, I get a warning that says to use conda 
activate.  The which cutadapt after the activation works.  The environment 
is not being passed down through the pipeline.   Putting conda activate in 
bashrc also works, but is not a good work around as it will need edited 
every time I want to run under a different environment.

Belinda

**Comment by leepc12** [comment]
Check if your cluster passes all environment variables to compute nodes.
Something like `qsub -V` in SGE.

**Comment by giardine** [comment]
If I submit with qsub -V, it does pass in new variables I have exported. 
The PATH is not so clear.  The PATH in my window is different from the 
PATH in qsub, and the PATH in qsub -V.  So the PATH has 3 different 
values.  Since I added the activate to bashrc all 3 contain
/storage/work/bmg137/miniconda2w/envs/encode-atac-seq-pipeline/bin

Belinda

**Comment by leepc12** [comment]
Oh. conda activate doesn't work in a shell script.
Do not include Conda activation in a shell script.

Do something like this.
```bash
$ source activate encode-atac-seq-pipeline
$ echo "caper run ..." | qsub -V ........
```

**Comment by giardine** [comment]
Yes it does if you use conda, not source.

#!/bin/bash

conda deactivate
echo "Without conda environment"
which cutadapt

conda activate encode-atac-seq-pipeline
echo "With conda environment"
which cutadapt

exit

This produces:
Without conda environment
which: no cutadapt in 
(/storage/work/bmg137/miniconda2w/bin:/usr/local/bin:/usr/local/sbin:/opt/moab/bin:/opt/mam/bin:/storage/work/bmg137/miniconda2w/bin:/storage/home/bmg137/perl5/bin:/storage/home/bmg137/perl5/bin:/storage/home/bmg137/conda3/bin:/storage/work/bmg137/encode/tfWorkflow/chip-seq-pipeline2/src:/storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/src:/storage/work/bmg137/miniconda2w/bin:/storage/work/bmg137/miniconda2w/condabin:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/opt/moab/bin:/opt/mam/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/openssh-7.4p1-el7/bin:/usr/local/sbin:/opt/ibutils/bin:/opt/puppetlabs/bin:/storage/home/bmg137/bin:/storage/work/bmg137/bin:/gpfs/group/rch8/legacy/biostar/bin)
With conda environment
/storage/work/bmg137/miniconda2w/envs/encode-atac-seq-pipeline/bin/cutadapt

Belinda

**Comment by leepc12** [comment]
Is it miniconda2? Can you try with miniconda3?

**Comment by giardine** [comment]
I started with miniconda2, but have done an update.
conda -V
conda 4.8.3

Belinda

**Comment by giardine** [comment]
Under info I see it is associated with Python2.  I have another conda 
install that I could use.

      active environment : None
             shell level : 0
        user config file : /storage/home/bmg137/.condarc
  populated config files : /storage/home/bmg137/.condarc
           conda version : 4.8.3
     conda-build version : 3.18.11
          python version : 3.7.6.final.0
        virtual packages : __glibc=2.12
        base environment : /storage/work/bmg137/anaconda3  (writable)
            channel URLs : https://conda.anaconda.org/bioconda/linux-64
                           https://conda.anaconda.org/bioconda/noarch
                           https://conda.anaconda.org/conda-forge/linux-64
                           https://conda.anaconda.org/conda-forge/noarch
                           https://repo.anaconda.com/pkgs/main/linux-64
                           https://repo.anaconda.com/pkgs/main/noarch
                           https://repo.anaconda.com/pkgs/r/linux-64
                           https://repo.anaconda.com/pkgs/r/noarch
           package cache : /storage/work/bmg137/.conda/pkgs
        envs directories : /storage/work/bmg137/anaconda3/envs
                           /storage/home/bmg137/.conda/envs
                platform : linux-64
              user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 
Linux/2.6.32-754.33.1.el6.x86_64 rhel/6.10 glibc/2.12
                 UID:GID : 135089:135089
              netrc file : None
            offline mode : False

I am guessing I would have to reinstall everything.  I will try that after 
the run I have going now finishes.

Belinda

**Comment by leepc12** [comment]
Pipeline's conda env doesn't seem to be activated correctly.
```
Traceback (most recent call last):
File "/storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/src/encode_task_trim_adapter.py", line 214, in
main()
```
So pipeline should run `encode_task_trim_adapter.py` inside the conda env. i.e. 
`YOUR_CONDA_ROOT/envs/encode-atac-seq-ppipeline/bin/encode_task_trim_adapter.py`
But pipeline tried to run it from `/storage/work/bmg137/encode/atacWorkflow/atac-seq-pipeline/src/`.
Something is wrong with your Conda and env.

My env:
```
leepc12@nandi:/users/leepc12/code/autouri$ source activate encode-atac-seq-pipeline
which cutadapt
(encode-atac-seq-pipeline) leepc12@nandi:/users/leepc12/code/autouri$ which cutadapt
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/cutadapt
(encode-atac-seq-pipeline) leepc12@nandi:/users/leepc12/code/autouri$ which encode_task_trim_adapter.py
/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_trim_adapter.py
(encode-atac-seq-pipeline) leepc12@nandi:/users/leepc12/code/autouri$
```

**Comment by leepc12** [comment]
Also, Conda is not a perfect virtual env. It has some flaws especially when you mix different versions of Conda (miniconda, anaconda, ...).
It's recommended to install miniconda3 and remove other Condas from your `PATH` (in your `~/.bashrc`).

**Comment by giardine** [comment]
I did as you recommended.  Everything says it is installed but during the 
test run it errors.

==== NAME=atac.filter, STATUS=RetryableFailure, PARENT=
SHARD_IDX=1, RC=1, JOB_ID=70096
START=2020-09-18T14:17:46.730Z, END=2020-09-18T14:18:15.398Z
STDOUT=/gpfs/scratch/bmg137/atacTest/atac/02c490a3-14e3-4327-8af2-3ea6055b962f/call-filter/shard-1/execution/stdout
STDERR=/gpfs/scratch/bmg137/atacTest/atac/02c490a3-14e3-4327-8af2-3ea6055b962f/call-filter/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
   File 
"/storage/work/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", 
line 417, in <module>
     main()
   File 
"/storage/work/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", 
line 350, in main
     filt_bam, args.out_dir, args.picard_java_heap)
   File 
"/storage/work/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", 
line 198, in mark_dup_picard
     dup_qc=dup_qc,
   File 
"/storage/work/b/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", 
line 331, in run_shell_cmd
     raise Exception(err_str)
Exception: PID=72023, PGID=72023, RC=1, DURATION_SEC=1.2
STDERR=Picked up _JAVA_OPTIONS: 
-Djava.io.tmpdir=/gpfs/scratch/bmg137/atacTest/atac/02c490a3-14e3-4327-8af2-3ea6055b962f/call-filter/shard-1/tmp.a6dd4158
ERROR: Unrecognized option: USE_JDK_DEFLATER

Belinda

**Comment by leepc12** [comment]
I think pipeline picked up wrong version of `picard` or `picard.jar`, which will be in your base Conda env `(base)` or in your local `~/.local/bin`.
Something is still wrong in Conda environment?
Check version of Picard. It should be 2.20.7
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/scripts/requirements.txt#L13

```bash
leepc12@nandi:~$ source activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) leepc12@nandi:~$ picard MarkDuplicates --version
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4024M -XX:ParallelGCThreads=1
2.20.7-SNAPSHOT
```

Take a closer look at your `PATH` before/activate pipeline's conda env.
Also, check `conda env list`. I also have different Conda installation like anaconda.
But I excluded it from my PATH.

```bash
(encode-atac-seq-pipeline) leepc12@nandi:~$ conda env list
# conda environments:
#
base                     /users/leepc12/miniconda3
aquas_chipseq            /users/leepc12/miniconda3/envs/aquas_chipseq
aquas_chipseq_py3        /users/leepc12/miniconda3/envs/aquas_chipseq_py3
cut-n-run-pipeline       /users/leepc12/miniconda3/envs/cut-n-run-pipeline
cut-n-run-pipeline-python2     /users/leepc12/miniconda3/envs/cut-n-run-pipeline-python2
encode-atac-seq-pipeline  *  /users/leepc12/miniconda3/envs/encode-atac-seq-pipeline
encode-atac-seq-pipeline-python2     /users/leepc12/miniconda3/envs/encode-atac-seq-pipeline-python2
encode-atac-seq-pipeline___     /users/leepc12/miniconda3/envs/encode-atac-seq-pipeline___
encode-chip-seq-pipeline     /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline
encode-chip-seq-pipeline-python2     /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-python2
imputation-challenge     /users/leepc12/miniconda3/envs/imputation-challenge
test_bowtie2             /users/leepc12/miniconda3/envs/test_bowtie2
test_nextflow            /users/leepc12/miniconda3/envs/test_nextflow
test_py2                 /users/leepc12/miniconda3/envs/test_py2
test_py3                 /users/leepc12/miniconda3/envs/test_py3
test_py36                /users/leepc12/miniconda3/envs/test_py36
```

If you get too much trouble with Conda then try with Singularity method.
Install Singularity and add `--singularity`. Or run in on Google Cloud.

**Comment by giardine** [comment]
Another picard.jar was in my path. I removed it and the workflow succeeded 
on the test data.

Thanks,
Belinda
