### ISSUE TITLE
Google changed a domain for hosting files for tutorial test samples and genome data

### ISSUE THREAD

**Issue by leepc12** [ENCODE-DCC/atac-seq-pipeline#28]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/klab_genomic_pipelines_discuss/2P0qpZZujdA/JZrhgVmsBQAJ

Users lost access to test sample fastqs and genome data. 

OLD:
https://storage.cloud.google.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/ENCSR356KRQ_fastq_subsampled.tar

NEW:
https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/ENCSR356KRQ_fastq_subsampled.tar

Both work with a web browser but the OLD one doesn't work with `wget`.

We need to replace `storage.cloud.google.com` with `storage.googleapis.com`.

**Comment by gmgitx** [comment]
Hi, if necessary in your view, could you add the json file about this sample's example here slurm document situation , since after download, just get file.fastq.gz like
```
/my_path/test_sample/ENCSR356KRQ/fastq_subsampled/rep1/pair1
ENCFF106QGY.subsampled.400.fastq.gz  ENCFF341MYG.subsampled.400.fastq.gz
```
then, next step become file.json, so how it become?
` $ INPUT=examples/local/ENCSR356KRQ_subsampled.json`

**Comment by leepc12** [comment]
input JSON (`examples/local/ENCSR356KRQ_subsampled.json` ) is included in this repo.
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/examples/local/ENCSR356KRQ_subsampled.json
