### ISSUE TITLE
Normalization of Peak Files?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/atac-seq-pipeline#284]
Just a quick question. 

I wanted to make sure that the final filtered peaks in `reproducibility_overlap` are not normalized in any way right?
They just include **raw** pile-up?

Making sure of this so that I do normalization for downstream analyses such as differential peaks analysis.

**Comment by akundaje** [comment]
The peak files do NOT include raw pile ups. They are all normalized scores,
pvalues and qvalues as provided by the peak callers. You need to extract
counts from the filtered BAM files or tagAlign files for the peaks for
downstream analyses that use counts.

-Anshul.

**Comment by YogiOnBioinformatics** [comment]
Awesome thanks so much!
Just wanted to give you a special shout-out to you Dr. @akundaje and @leepc12. 

You are the **MOST RESPONSIVE** open-source tool maintainers I have ever worked with. 
Thanks very much for your dedication to help people with your tools. 

Kind regards, 
Yogi

**Comment by akundaje** [comment]
Happy to help. Thank u for the kind words.
