### ISSUE TITLE
Biopython upgrade breaks python 2.7 compatibility 

### ISSUE THREAD

**Issue by thomas-reimonn** [ENCODE-DCC/atac-seq-pipeline#288]
## **Describe the bug**
In the dockerfile 
"RUN pip2 install --no-cache-dir metaseq==0.5.6" 
requires biopython, but biopython 1.77 (the latest) requires python >= 3.6. A workaround is to specify the older version of biopython (1.76), which supports python 2.7. 

Recommend changing to:
"# Install genomic python packages (python2)
RUN pip2 install --no-cache-dir biopython==1.76
RUN pip2 install --no-cache-dir metaseq==0.5.6"

## **OS/Platform**
- OS/Platform: Docker 2.4.0.0 running on MacOS
- Conda version:  N/A
- Pipeline version: Git Head
- Caper version: N/A

**Comment by leepc12** [comment]
Thanks for reporting this. Added `biopython==1.76` to `requirements_py2.txt`. Will be applied in the next release.

**Comment by leepc12** [comment]
Fixed
