### ISSUE TITLE
a question about reads shifting

### ISSUE THREAD

**Issue by fanying2015** [ENCODE-DCC/atac-seq-pipeline#29]
Thank you for the construction of the pipeline and all the hard work.

I'd like to confirm with one issue: Do those bam files have the reads shifted? It seems many groups shifted reads  +4/-5bp because of the insertion of adaptors by Tn5 transpose, before calling peaks with MACS2 or do footprint analysis.

Do I need to shift reads in the bam files or re-do peak calling with the shifted bam?

Thank you very much!

**Comment by leepc12** [comment]
No. In the pipeline, shifting for tn5 is done when converting BAM to BED (TAG-ALIGN). MACS2 takes in this tn5-shifted BED instead of BAM.

**Comment by fanying2015** [comment]
Thank you! I'll do shifting for bam files when doing footprint then.
