### ISSUE TITLE
bowtie2-align-s: undefined symbol

### ISSUE THREAD

**Issue by giardine** [ENCODE-DCC/atac-seq-pipeline#313]
## **Describe the bug**
I reinstalled the pipeline and now I get an error in call-align.  I am testing with data I had run through the pipeline before the reinstall so I know it is not data related.

## **OS/Platform**
- OS/Platform: RedHat 7
- Conda version: If you used Conda (`$ conda --version`). conda 4.9.2
- Pipeline version: [e.g. v1.8.0] the most recent, just did a git pull
- Caper version: [e.g. v1.2.0] 1.4.2

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
```ini
backend=local
local-hash-strat=path+modtime
local-loc-dir=
cromwell=/storage/home/bmg137/.caper/cromwell_jar/cromwell-52.jar
womtool=/storage/home/bmg137/.caper/womtool_jar/womtool-52.jar
```

## **Input JSON file**
Paste contents of your input JSON file.
```json
not important, worked before reinstall
```

## **Troubleshooting result**

If you ran `caper run` without Caper server then Caper automatically runs a troubleshooter for failed workflows. Find troubleshooting result in the bottom of Caper's screen log.

If you ran `caper submit` with a running Caper server then first find your workflow ID (1st column) with `caper list` and run `caper debug [WORKFLOW_ID]`.

Paste troubleshooting result.
```
conda activate encode-atac-seq-pipeline
which bowtie2
/storage/work/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/bowtie2
bowtie2
/storage/work/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/bowtie2-align-s: symbol lookup error: /storage/work/bmg137/miniconda3/envs/encode-atac-seq-pipeline/bin/bowtie2-align-s: undefined symbol: _ZN3tbb10interface78internal15task_arena_base19internal_initializeEv
(ERR): Description of arguments failed!
Exiting now ...
```
That is the same error I get when running the pipeline, it just takes over 2 hours to get there.

**Comment by giardine** [comment]
I tried a reinstall without using mamba and now bowtie2 works.  I haven't run the full pipeline yet but this is promising.

**Comment by giardine** [comment]
I did the full run of the pipeline and it works now.  So heads up to anyone having trouble with install try without mamba even if it is slower.

**Comment by leepc12** [comment]
Thanks for reporting `mamba` issue. I will look into this.

**Comment by leepc12** [comment]
Looks related to conflicts between Intel version of `libtbb-dev` and Conda's `nomkl` (non-Intel MKL)?
https://bugs.archlinux.org/task/64907

BTW I will fix `tbb` version in pipeline's Conda environment. But you can also try installing correct `libtbb-dev` on your machine.
