### ISSUE TITLE
Error when in installing conda dependencies.sh

### ISSUE THREAD

**Issue by tiagobrc** [ENCODE-DCC/atac-seq-pipeline#33]
Hi, When I try to install conda dependencies I get this error. Can I install the dependencies manually?
Or do you have an idea to how can I fix this? This is the only error I get 1 second after trying the shell script.

Tried in two different places with an exact same error. Also, in the documentation you say:

`bash installers/uninstall_dependencies.sh`

but uninstall_dependencies.sh is located at the conda folder, not installers folder.

Thank you.

```
bash conda/install_dependencies.sh                                             
/ru-auth/local/home/trezende/localPrograms/Miniconda/bin/conda
=== Found Conda (conda 4.5.11).
=== Installing packages for python3 env...
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/r/noarch/repodata.json>
Elapsed: 00:00.020204
CF-RAY: 45d006588c6d9200-EWR

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/r

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

```

**Comment by leepc12** [comment]
This looks like a temporary connection problem of Conda repo. I just tested the installer and it worked fine on my laptop. Can you try again and see it works?

**Comment by tiagobrc** [comment]
Haha, this is awkward, you were right. Thank you very much. All dependencies are being installed normally.
