### ISSUE TITLE
Error during MaterializingWorkflowDescriptorState

### ISSUE THREAD

**Issue by rudondamba** [ENCODE-DCC/atac-seq-pipeline#334]
## **Describe the bug**
I am getting this error 
[2021-07-21 03:21:44,03] [error] WorkflowManagerActor Workflow 5471e672-db2a-4a74-8ef7-ef571feb655c failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.mate
rialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unrecognized token on line 487, column 323:
help: 'Define if you want to start pipeline from PEAK files. Define if you have multiple biological replicates and atac.true_rep_only flag is off. PPR1 means analysis on pooled 1st pseudo repl
icates. Each biological replicate is shuf/split into two pseudos. This is a pooling of each replicate\'s 1st pseudos.'

## **OS/Platform**
- Linux
-  v1.8.0
- Caper version: [e.g. v1.2.0]

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
```ini
PASTE CAPER CONF CONTENTS HERE
```

## **Input JSON file**
Paste contents of your input JSON file.
```
{
    "atac.title" : "F20FTSUSAT0808_HUMnjbr",
    "atac.description" : "Mouse ATACseq",

    "atac.pipeline_type" : "atac",
    "atac.align_only" : false,
    "atac.true_rep_only" : false,
    "atac.genome_tsv" : "atacseqIndex/mm10.tsv",
    "atac.paired_end" : true,

    "atac.fastqs_rep4_R1" : ["xzl.mmu.C57.sperm.MiwiKIHet.adult.rep4.ATACseq.R1.fastq.gz"],
    "atac.fastqs_rep4_R2" : ["xzl.mmu.C57.sperm.MiwiKIHet.adult.rep4.ATACseq.R2.fastq.gz"],
    "atac.fastqs_rep5_R1" : ["xzl.mmu.C57.sperm.MiwiKIHet.adult.rep5.ATACseq.R1.fastq.gz"],
    "atac.fastqs_rep5_R2" : ["xzl.mmu.C57.sperm.MiwiKIHet.adult.rep5.ATACseq.R2.fastq.gz"],

    "atac.auto_detect_adapter" : true,

    "atac.smooth_win" : 73,

    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.enable_xcor" : true
}

```

**Comment by leepc12** [comment]
I think Cromwell failed to read pipeline's WDL file. Did you specify Cromwell JAR in caper's conf? What is atac-seq pipeline's version?

**Comment by rudondamba** [comment]
Its version /1.8.0_111 but i used the wdl file from the latest version. This is the script I submitted for running
```
#!/bin/bash
#SBATCH -J ATACseqCell 
#SBATCH -e Cell_%j.err
#SBATCH -o Cell_%j.out
#SBATCH --cpus-per-task=8
#SBATCH -p interactive -t 4:00:00 --mem 96000
#SBATCH --mail-type=ALL
#SBATCH --mail-user=Rudo_Ndamba@URMC.Rochester.edu

cd $SLURM_SUBMIT_DIR
module load atac-seq-pipeline/b1
activate

#Run the following commands
DIR=/software/atac-seq-pipeline/b1
INPUTDATA=Cell.json

rm -rf atacseqIndex
ln -s /scratch/xli91_lab/piPipes/common/mm10/atacseqIndex
java -jar -Dconfig.file=$DIR/backends/backend.conf $DIR/cromwell-34.jar run /software/atac-seq-pipeline/1.10.0/src/atac.wdl -i $INPUTDATA

```

**Comment by leepc12** [comment]
You used `cromwell-34.jar` without Caper. I think it's outdated and does not support WDL 1.0.
Please use Caper (Python wrapper for Cromwell).

```
$ pip install caper
$ caper run YOUR.wdl -i YOUR_INPUT.json # instead of the java -jar cromwell-34.jar command line
```

**Comment by rudondamba** [comment]
Thank you.
Additionally, do you know what to make of this error and how to fix it: RuntimeException: Failed to evaluate 'mito_chr_name_' (reason 1 of 1): Evaluating select_first([mito_chr_name, read_genome_tsv.mito_chr_name]) failed: select_first was called with 2 empty values. We needed at
 least one to be filled.
 and:
java.lang.RuntimeException: Failed to evaluate 'bowtie2_mito_idx_tar_' (reason 1 of 1): Evaluating select_first([bowtie2_mito_idx_tar, read_genome_tsv.bowtie2_mito_idx_tar]) failed: select_first was called 
with 2 empty values. We needed at least one to be filled.

**Comment by leepc12** [comment]
If you get any errors in WDL that means your are using either outdated Cromwell or outdated pipeline.
Please use the latest pipeline with the latest Caper.
