### ISSUE TITLE
local installation problem

### ISSUE THREAD

**Issue by Cristinex** [ENCODE-DCC/atac-seq-pipeline#338]
Hi, all,

I came across with a weird error.
When I run locally, it just stop without telling any errors in the terminus. However, when I went to the stderr, it was recorded that

Traceback (most recent call last):
  File "/data/home/christinec/.conda/envs/encode-atac-seq-pipeline/bin/encode_task_tss_enrich.py", line 6, in <module>
    import matplotlib as mpl
ImportError: No module named matplotlib

What is important is that this path locates in the conda of my base, but I have already installed a miniconda3 following the tutorial documents and worked conda in miniconda3. 

I successfully run the example trial. Failed on running my own data. Do you have any ideas?

Sincerely,
Cristine

**Comment by Cristinex** [comment]
Another question, is it possible to resume a failed pipeline? Since this pipeline require much computational efforts, it takes too long to go through all from the beginning...

**Comment by leepc12** [comment]
Please activate your environment and then install matplotlib manually
```bash
$ source activate encode-atac-seq-pipeline
$ conda install matplotlib
```

There is no way to resume a workflow that has run without a metadata DB (`--db file`).
Run it with a DB first `caper server --db file` or `caper run ... --db file`. A file DB is created and cache (previous outputs) data will be written on it. You will see bunch of HSQLDB files on the output directory. Next time you run the pipeline with the same command line it will resume from where it left off (it actually starts over and collect previous outputs and link (soft or hard) them on the new workflow's output directory.

**Comment by Cristinex** [comment]
For the first solution, when I tried to install, it told me requirements satisfied.
Thank you for telling me about the function of metadata ^ - ^

**Comment by Cristinex** [comment]
The installation has been fixed. The conda installation (even with mamba) sometimes take long time to solve the environment and will left something behind. More patience needed. We need to install them manually or copy them from libraries from other environments or packages. Then the issue will be closed. Thanks for leepc12's answer.

**Comment by leepc12** [comment]
There is actually a hidden Conda environment based on python2. The main environment is based on python3 and activating it will run a bash script to link binaries in that py2 env. I had to make the py2 one because that `tss_enrich` task uses a python package `metaseq` which is only available on python2.

Please check if your python2 environment exists and metaseq and matplotlib are correctly installed there.
```
$ source activate encode-atac-seq-pipeline-python2
$ which python2
$ conda list metaseq matplotlib
$ conda install matplotlib # if it's not listed on the result
```
