### ISSUE TITLE
pipeline's Conda environments for ATAC-seq and ChIP-seq

### ISSUE THREAD

**Issue by yingsun-ucsd** [ENCODE-DCC/atac-seq-pipeline#371]
I need some instructions on the pipeline's conda environment. I just set up chip-seq-pipeline2 with conda on our local server and get it run well.

I am working on atac-seq-pipeline following https://github.com/ENCODE-DCC/atac-seq-pipeline.  I have concerns about step 4:
__________________________________________________________
(Optional for Conda users) Install pipeline's Conda environments if you don't have Singularity or Docker installed on your system. We recommend to use Singularity instead of Conda. If you don't have Conda on your system, install [Miniconda3](https://docs.conda.io/en/latest/miniconda.html).
$ cd atac-seq-pipeline
uninstall old environments (<2.0.0)
$ bash scripts/uninstall_conda_env.sh
$ bash scripts/install_conda_env.sh
__________________________________________________________

1. Since I have a conda environment for chip-seq already, if I uninstall, will it affects my chip-seq pipeline?
2. In such a case, should I just run the install command to build another environment for atac-seq? Or I should work it some other way around?

Thank you so much for your time and help!

**Comment by leepc12** [comment]
1. No it doesn't affect chip's conda envs.
2. Please just run `scripts/install_conda_env.sh`. They are complete separate environments.

**Comment by yingsun-ucsd** [comment]
Got it. Thanks.

Just FYI, I had to do the same extra step as for chip-seq-pipeline2 to get it run without any error that you might also want to fix in the next release.
__________________________________
$ conda install -n encode-atac-seq-pipeline-spp --no-deps --no-update-deps -y ncurses==5.9 -c conda-forge
__________________________________

Thanks again for all your help!
