### ISSUE TITLE
Resume function in the pipeline

### ISSUE THREAD

**Issue by shanmukhasampath** [ENCODE-DCC/atac-seq-pipeline#38]
**General Question**

Hi Jin,

I am wondering is there any resume function in the script as I could not find anything close to it. The concept is that if there is a breakdown at certain task in the pipeline. The next time I run the pipeline it should not run from the beginning so that it starts from the broke down task.

**OS/Platform and dependencies**
- OS or Platform: CentOS Linux release 7.4.1708
- Cromwell/dxWDL version: Cromwell-34
- Conda version: 4.5.10

**Comment by Cristinex** [comment]
> Cromwell supports ["call-caching"](https://cromwell.readthedocs.io/en/develop/Configuring/#call-caching) and I am sure that is what you are looking for. It skips tasks that are already done based on docker hash, md5sum hash of input files and code lines in `commands { }` block. You may need to install a MySQL server and run a cromwell server with it and submit jobs via REST API.
> 
> But there are some limitations. Any change in a docker container (that is... any single update/bug-fix on the pipeline) will make you lose resumability. So you will not find it very useful.
> 
> We don't have an official tutorial or README for this. But I think the following documnets will be helpful.
> 
> * https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/tutorial_sherlock.md#running-multiple-pipelines-with-cromwell-server-mode
> * https://github.com/ENCODE-DCC/atac-seq-pipeline/tree/master/test#how-to-run-a-cromwell-server-on-gc

I think the documents maybe helpful. However, the web page link you posted is now invalid. Could you update links to the document, please?

**Comment by leepc12** [comment]
My comment on this issue was written on 2018. It's outdated.

Please take a look at these docs for SLURM and GC:
https://github.com/ENCODE-DCC/caper#running-pipelines-on-slurm-clusters
https://github.com/ENCODE-DCC/caper/tree/master/scripts/gcp_caper_server

MySQL is no longer needed for call-caching.
File-based DB (`db=file` in Caper's conf file `~/.caper/default.conf`) should work fine for a small number of workflows.
