### ISSUE TITLE
Meaning of "fold change over control" in ATAC-seq output

### ISSUE THREAD

**Issue by rcasero** [ENCODE-DCC/atac-seq-pipeline#384]
Hi,

I have a question about the ATAC-seq pipeline.

The description of this pipeline in the ENCODE ["ATAC-seq Data Standards and Processing Pipeline"](https://www.encodeproject.org/atac-seq/) page states that "alignments" are processed by the "signal generation" block to produce

* fold change over control
* signal p-value

![image](https://user-images.githubusercontent.com/1219084/172406972-659fae8e-680d-48d3-93b5-b3a0ba263ab1.png)

What does "fold change over control" mean exactly? Is this a number of counts divided by another number of counts? What's the control? In areas where the control has zero counts, how do you avoid dividing by zero? Where can this be found in the code?

This is the data presented in the ENCODE experiments datasets, e.g. [experiment ENCSR312UCH](https://www.encodeproject.org/experiments/ENCSR312UCH/) Accession [ENCFF099HUE](https://www.encodeproject.org/files/ENCFF099HUE/) if a bigWig file with output type = "fold change over control".

Thanks!

**Comment by rcasero** [comment]
Further thinking about this, my current guess is that "fold change over control" is a misnomer, and it should say something like "coverage" instead?

**Comment by akundaje** [comment]
It's the fold change of observed coverage over expected coverage (based on a Poisson null model). This is just MACS2's fold change calculation.

**Comment by akundaje** [comment]
The denominator is never zero. The expected coverage is a max of the global and local Poisson lambda. Global lambda = total reads over entire genome * smoothing window size / length of mappable genome. Which can never be 0

**Comment by rcasero** [comment]
Thanks, @akundaje , very useful.
