### ISSUE TITLE
How to deal with repeat peaks in idr.optimal_peak.narrowPeak

### ISSUE THREAD

**Issue by liu-zhiyang** [ENCODE-DCC/atac-seq-pipeline#394]
I found there were many repeat peaks in idr.optimal_peak.narrowPeak. How shoud I deal with them? Or just keep them? 
Hope you can help me.
![image](https://user-images.githubusercontent.com/43285689/184782052-26abacb0-a676-4099-867c-749900f25d19.png)

**Comment by akundaje** [comment]
Not sure what you mean by repeat peaks. Are you referring to peaks with the same chr, start and stop fields? There can be peaks with the same chr, start, stop but different peak summits (last column in the narrow peak file) and different peak scores. These are not repeats. They just represent the fact that the peak has multiple summits.

**Comment by liu-zhiyang** [comment]
> Are you referring to peaks with the same chr, start and stop fields?
Yes, that is what exactly I mean.
Thank you very much to answer my question. I think I've understood this fact.
