### ISSUE TITLE
xcor not completing on Sherlock singularity

### ISSUE THREAD

**Issue by knoedlerj** [ENCODE-DCC/atac-seq-pipeline#43]
I'm running the pipeline with Singularity on Sherlock 2.0 and the xcor job doesn't work on the test data: 

[2018-10-14 01:26:02,28] [error] WorkflowManagerActor Workflow b3ff0230-746e-42f6-bea3-9a6aafa8ceb2 failed (during ExecutingWorkflowState): Job atac.xcor:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /scratch/users/knoedler/atac-seq-pipeline/cromwell-executions/atac/b3ff0230-746e-42f6-bea3-9a6aafa8ceb2/call-xcor/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 102, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 91, in main
    ta_subsampled, args.speak, args.nth, args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 53, in xcor
    run_shell_cmd(cmd1)
  File "/software/atac-seq-pipeline/src/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process
ln: failed to access '*.cc.plot.pdf': No such file or directory
ln: failed to access '*.cc.plot.png': No such file or directory
ln: failed to access '*.cc.qc': No such file or directory
ln: failed to access '*.cc.fraglen.txt': No such file or directory

Job atac.xcor:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /scratch/users/knoedler/atac-seq-pipeline/cromwell-executions/atac/b3ff0230-746e-42f6-bea3-9a6aafa8ceb2/call-xcor/shard-1/execution/stderr.
 Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 102, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 91, in main
    ta_subsampled, args.speak, args.nth, args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 53, in xcor
    run_shell_cmd(cmd1)
  File "/software/atac-seq-pipeline/src/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process
ln: failed to access '*.cc.plot.pdf': No such file or directory
ln: failed to access '*.cc.plot.png': No such file or directory
ln: failed to access '*.cc.qc': No such file or directory
ln: failed to access '*.cc.fraglen.txt': No such file or directory

**Comment by leepc12** [comment]
Please upload a tar ball of all logs.

**Comment by knoedlerj** [comment]
Thanks! For all tasks or just the xcor?

**Comment by leepc12** [comment]
Please run this on your working directory.

```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_[ISSUE_ID].tar.gz
```

**Comment by knoedlerj** [comment]
Thanks, here it is:
[debug_34.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2480640/debug_34.tar.gz)

**Comment by leepc12** [comment]
```
PID=32489: Decompressing ChIP file
PID=32489: Loading required package: caTools
PID=32489: Error in dyn.load(file, DLLpath = DLLpath, ...) :
PID=32489:   unable to load shared object '/home/users/knoedler/R/x86_64-pc-linux-gnu-library/3.2/bitops/libs/bitops.so':
PID=32489:   libimf.so: cannot open shared object file: No such file or directory
PID=32489: Error: package 'caTools' could not be loaded
PID=32489: Execution halted
```

**Comment by knoedlerj** [comment]
I see - is this a version issue (I think default R on sherlock is 3.4)? It looks like all the files are in my directory

**Comment by knoedlerj** [comment]
Oh, caTools isn't in R version 3.2 on my partition. That might be the problem.

**Comment by leepc12** [comment]
@knoedlerj: You are using singularity so the pipeline should not use anything locally installed on your home. What is your full command line? Also please upload `workflow_opts/sherlock.json` too.

**Comment by knoedlerj** [comment]
Command line is copy-pasted from Github: 
INPUT=examples/sherlock/ENCSR356KRQ_subsampled_sherlock.json
java -jar -Dconfig.file=backends/backend.conf -Dbackend.default=slurm_singularity cromwell-34.jar run atac.wdl -i ${INPUT} -o workflow_opts/sherlock.json

(changed json to a txt file because github wouldn't let me attach as json for some reason)

[sherlock.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2480853/sherlock.json.txt)

**Comment by leepc12** [comment]
Please try with this backend file instead of `backends/backend.conf`.

[backend_singularity_home_fix.conf.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2480884/backend_singularity_home_fix.conf.txt)

**Comment by knoedlerj** [comment]
Thanks!! I'll give it a try.

**Comment by knoedlerj** [comment]
Ran everything but atacqc that time; thanks!

**Comment by leepc12** [comment]
@knoedlerj that sounds good but what kind of error did you get at ATAQC?

**Comment by knoedlerj** [comment]
Thanks, I actually fixed it - for some reason on Sherlock2 the macs2 and ataqc jobs fail to submit with a 'required node configuration not available' error with the default memory settings. I can't for the life of me figure out what's different about those jobs, but if I change the memory allocation from 20000 MB to 16000 MB it works.
