### ISSUE TITLE
Differences in qc when validating installation

### ISSUE THREAD

**Issue by bozidar-obradovic** [ENCODE-DCC/atac-seq-pipeline#430]
Hi,

I successfully installed version 2.2.2 of the ATAC-Seq pipeline and I'm trying to validate the installation by running test examples given in dev/test/test_workflow.
It finishes well, but the QC Reports aren't identical - there are differences with regards to the overlapping of pooled peaks, as well as TSS Enrichment data (the whole comparison is available [here](https://www.diffchecker.com/of1p6jJv/).

Is this something you encountered in the past and if it is, how did you manage to solve it?
If not, can you share the docker container in which you ran the workflow - my suspicion is the differences come from different versions of software packages/libraries which didn't have explicit versions mentioned in the dockerfile.

Thank you in advance!

**Comment by bozidar-obradovic** [comment]
After fixing some issues, the differences remain in the areas concerning overlap of pooled peaks (diff is [here](https://www.diffchecker.com/zlglV1Qs/))

**Comment by leepc12** [comment]
Sorry about late response.

Did you use this input JSON file for testing?
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/dev/test/test_workflow/ENCSR356KRQ_subsampled.json
Please post your input JSON file.
I will be running this on my end and let you know.

**Comment by bozidar-obradovic** [comment]
Hi, sorry for not responding.
We found where the error was and it wasn't on your end.

Thank you for your effort!
