### ISSUE TITLE
Confirming that separate conditions/treatments should be analyzed by separate pipelines

### ISSUE THREAD

**Issue by OrangeyO2** [ENCODE-DCC/atac-seq-pipeline#432]
Hello

Apologies if this question is redundant, but I just wanted to make sure I was correct.

Following up on these previous questions,
#67 #225 #258 

**_separate conditions/treatments should have separate input json files, and be analyzed separately_**, am I correct?

Therefore, an input json file should only contain fastqs from the same condition/treatment, differing only in biological/technical replicates, and if there are 3 treatments (e.g. drug A, drug B, untreated), I should run the pipeline 3 times.

Thanks in advance for your help!

**Comment by akundaje** [comment]
Yes correct

**Comment by OrangeyO2** [comment]
Thank you!
