### ISSUE TITLE
Empty Success array causes pipeline to fail

### ISSUE THREAD

**Issue by Froblinkin** [ENCODE-DCC/atac-seq-pipeline#44]
I'm running the ATAC-SEQ pipeline on a toy file with 1 pair end read (2 fastq files, both 100 lines long). I would like ATAC-SEQ to output bam files, but it keeps on crashing at a stage near to the end. 

I'm following the NIH's guide for running ATAC-SEQ, so I'm working with the SLURM scheduler using the NIH's settings (backend, Cromwell, and wdl) and a file stored by them for the hg19 genome. [https://hpc.nih.gov/apps/encode-atac-seq-pipeline.html](url) While I can run through their example, I cannot get my data to work. 

I believe this issue has come up a few times in the past, but the original posters went inactive before a solution could be settled on. See [https://github.com/ENCODE-DCC/chip-seq-pipeline2/issues/15](url) and [https://github.com/ENCODE-DCC/atac-seq-pipeline/issues/17](url). I did try loading picard, but that did not change my results

Here is where the error message appears:

[2018-10-25 18:05:25,88] [error] WorkflowManagerActor Workflow 37f13417-8676-469f-b575-aa80b5ce6c24 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'filter.mito_dup_log': Failed to find index Success(WomInteger(0)) on array:

Success([])

Here is my JSON input:
{
	"atac.pipeline_type" : "atac",
	"atac.genome_tsv" : "/fdb/encode-atac-seq-pipeline/hg19/hg19.tsv",
	"atac.fastqs_rep1_R1" : ["SRX860_1.fastq.gz"],
	"atac.fastqs_rep1_R2" : ["SRX860_2.fastq.gz"],
	"atac.paired_end" : true,
	"atac.align_only" : true
}

And here are the attached files: 
[debug_[44].tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2517010/debug_.44.tar.gz)
[SRX860_1.fastq.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2517003/SRX860_1.fastq.gz)
[SRX860_2.fastq.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2517004/SRX860_2.fastq.gz)

Any help would be appreciated.

Thanks,

Jonathan

**Comment by leepc12** [comment]
This will be fixed in the next release. Thanks!
