### ISSUE TITLE
Adapting your pipeline to run in SGE (JHPCE cluster): specify qsub shell + ataqc mem + finding picard.jar

### ISSUE THREAD

**Issue by lcolladotor** [ENCODE-DCC/atac-seq-pipeline#45]
Hi,

We were able to run your pipeline using Cromwell 34 at JHPCE http://www.jhpce.jhu.edu/ with some effort. We have some questions that we might have missed in the docs.

## Issue 1: conda env

We noticed that the qsub'ed jobs were not finding the conda env. So we edited our `~/.bashrc` file to load the conda env. However, the backend configuration file uses `/bin/sh` instead of `/bin/bash` and thus we had to edit the backend conf file: at https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/backends/backend.conf#L138.

```bash
## For forcing the activation of the conda ATAC seq env
if [[ $HOSTNAME == compute-* ]]; then
       echo "Activating the ATAC seq conda environment"
       source activate encode-atac-seq-pipeline
fi
```

While the issue with the conda environment not been activated was unexpected, is there an option we missed for specifying the shell for the qsub calls? Looks like there isn't and this is a small edit that a user can do.

## Issue 2: ataqc memory

By default the ataqc step uses max 16,000 MB and you can see that value specified in both the java options and the memory requested for SGE. That is all ok, except that for some reason we seem to need an extra 4GB beyond the max java limit in SGE at JHPCE.

Is there an option we can use to increase the max SGE mem for the ataqc step while keeping the max mem at 16,000 for the java options? (or for only controlling the java options?). It could be that we just need to fork your pipeline and make a small edit in the `atac.wdl` file.

For example, we might need to edit https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/atac.wdl#L976 to read 

```
export _JAVA_OPTIONS="-Xms256M -Xmx16000M -XX:ParallelGCThreads=1"
```

and then run the pipeline with `atac.ataqc.mem_mb` set to 21,000 Mb. (if that options is valid, since it's not mentioned in https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/input.md#resource)

## Issue 3: which picard.jar

When the pipeline crashed due to memory in ataqc we debugged things by modifying the `script.submit` script but then ran into an error with `which picard.jar`. For some reason, https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/e9c974488ef6d0a50fde917e63fb26ba98fa4a0a/src/encode_common_genomic.py#L104-L108 crashed and didn't go into the exception. We solved this again by editing the `~/.bashrc` file with:

```bash
## For using a specific picard.jar
if [[ $HOSTNAME == compute-* ]]; then
       echo "Tricks for picard"
       export PATH=/users/bbarry/.conda/envs/encode-atac-seq-pipeline/share/picard-2.10.6-0:$PATH
fi
```

I don't know if you've seen this before. It could again be an issue with the OS version at JHPCE.

Let us know if you need more info!

Best,
Leonardo and @briannabarry

(cc @andrewejaffe)

**OS/Platform and dependencies**
- OS or Platform: SGE Cluster
- Cromwell/dxWDL version: Cromwell v34 (we could try v36 but doubt our issues are cromwell-specific)
- Conda version: 4.3.22

JHPCE info: `/dcl01/lieber/ajaffe/Brianna/jaffe_lab/atac-seq-pipeline/cromwell-executions/atac/198ad417-0ccf-4a84-8cee-2707166bc53b/call-ataqc/shard-1/execution` (in case we need to revisit this later)

**Comment by leepc12** [comment]
Thanks for your feedback,

Issue1:

Did you activate conda environment before running pipelines?
Our pipeline internally runs `qsub -V` (passing all environment variables including $PATH to qsubbed jobs, so you don't actully need to edit `~/.bashrc` to load conda environment for all qsubbed jobs.

`/bin/sh` was added to the backend file due to issue #40.

What is the full command line (or shell script) you used for running pipelines?


Issue2:

I see. We will add `mem_java_mb` to the ATAQC task.

```
export _JAVA_OPTIONS="-Xms256M -Xmx${select_first([mem_java_mb,mem_mb,'16000'])}M -XX:ParallelGCThreads=1"
```

so that `mem_java_mb` will be chosen only when it's defined in the input JSON file.


Issue3: 

This is related to Issue1. Please activate conda environment before running pipelines.
`which picard.jar` fails if conda environment's `bin` is not added to `$PATH` (i.e. conda environment was not loaded before running pipelines).

**Comment by lcolladotor** [comment]
Hi,

Thanks for the reply!

## Issue 1

Thanks for the info! We did run `source activate encode-atac-seq-pipeline` before running the pipeline. I ran some tests and basically, the `qsub -V` option isn't working for us.

On a `qrsh` session, I see the following:

```bash
$ which encode_common.py
/usr/bin/which: no encode_common.py in (/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin)
10:43 test_qsub_v $ source activate encode-atac-seq-pipeline
10:43 test_qsub_v $ which encode_common.py
/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin/encode_common.py
```

Which works as expected. That is, `encode_common.py` is not found until you activate the conda environment.

With the same `qrsh` session I then ran three jobs.

First, `qsub test_qsub_v.sh` (contents below) that uses the `-V` option.

```bash
#!/bin/bash
#$ -cwd
# Specify log file names
#$ -o test_log.txt
#$ -e test_log.txt
#$ -V

which encode_common.py
```

Second, `qsub test_qsub_no_v.sh` which doesn't have the `-V` option.

```bash
#!/bin/bash
#$ -cwd
# Specify log file names
#$ -o test_activate_log.txt
#$ -e test_activate_log.txt

source activate encode-atac-seq-pipeline

which encode_common.py
```

Third, `qsub test_activate.sh` which doesn't have the `-V` option and does have the `source activate encode-atac-seq-pipeline` command before `which`.

```bash
#!/bin/bash
#$ -cwd
# Specify log file names
#$ -o test_nov_log.txt
#$ -e test_nov_log.txt

which encode_common.py
```

Only the third test was successful at JHPCE.

```bash
$ more *log*
::::::::::::::
test_activate_log.txt
::::::::::::::
Loading git
Adding LIBD modules
/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin/encode_common.py
::::::::::::::
test_log.txt
::::::::::::::
Loading git
Adding LIBD modules
which: no encode_common.py in (/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/
lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/bin:/jhpce/shared/jhp
ce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHP
CE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/scratch/temp/6225473.1.shared.q:/users/lcollado/software:/users/lcollado/m
iniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/usr/lib64/qt-3.3/bin:
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin)
::::::::::::::
test_nov_log.txt
::::::::::::::
Loading git
Adding LIBD modules
which: no encode_common.py in (/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/
lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/bin:/jhpce/shared/jhp
ce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHP
CE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/scratch/temp/6225474.1.shared.q:/usr/local/bin:/bin:
/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin)
```

@BriannaBarry, can you respond with the full command used for running the pipeline?

In any case, our workarounds for issue 1 work @leepc12.


## Issue 2

Thanks for opening an issue on creating `mem_java_mb`!

## Issue 3

We did activate the conda environment, but yes, this is related to issue 1.

Thanks,
Leo

**Comment by BriannaBarry** [comment]
## Issue 1
Our only successful run thus far was initiated with the following commands, after editing the ~/.bashrc file as @lcolladotor described in his initial issue post. This is as described in https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/tutorial_sge.md

```
INPUT=examples/local/ENCSR356KRQ_subsampled.json
java -jar -Dconfig.file=backends/backend.conf -Dbackend.default=sge cromwell-34.jar run atac.wdl -i ${INPUT} -o workflow_opts/sge.json
```

**Comment by lcolladotor** [comment]
Hi again,

## Issue 1

I got some help from other users/admins of JHPCE. For completeness, I'm sharing my replies here.

### reply 1

> But its hard to see what is going on with incomplete descriptions such as
> "We noticed that the qsub'ed jobs were not finding the conda env."

Commands like the following one were failing:

```bash
which encode_common.py
```

For example, https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/c91b50571bba1bb2502bd13082172aedf29cb72b/atac.wdl#L546 runs:

python $(which encode_trim_adapter.py)

The installation script adds several of these *.py files to the $PATH using the conda environment: the end of the installation script https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/c91b50571bba1bb2502bd13082172aedf29cb72b/conda/install_dependencies.sh#L80-L83 calls a second script that adds the python scripts to the bin folder of the conda environment (thus enabling the "which" commands"). That is: https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/c91b50571bba1bb2502bd13082172aedf29cb72b/conda/update_conda_env.sh#L5 plus
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/c91b50571bba1bb2502bd13082172aedf29cb72b/conda/update_conda_env.sh#L26-L33

### reply 2

> Likely, if you added a “printenv” command to your script and reran your tests, you would see a difference that may point to where the discrepancy is coming from.

I did exactly this and shared all the log and `sh` files at https://gist.github.com/lcolladotor/3efc1ff4c3c768658961b580332a69f6. 

For the one case that it works, I ran `printenv` before and after `source activate encode-atac-seq-pipeline`: https://gist.github.com/lcolladotor/3efc1ff4c3c768658961b580332a69f6#file-test_qsub_v_activate-sh. I can see that in all 3 tests, `SGE_O_PATH` does include `/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin` which is where `encode_common.py` is located. However, only the test that works has that path in the `PATH` environment variable. 

So maybe this issue would be resolved if `PATH` prepended `SGE_O_PATH`. But I'm not sure.

Here are parts of the logs that mention the conda environment by name:

```bash
$ grep encode-atac-seq-pipeline *log*
test_activate_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_activate_log.txt:PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/scratch/temp/6225767.1.shared.q:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_activate_log.txt:CONDA_PREFIX=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline
test_activate_log.txt:JAVA_HOME=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline
test_activate_log.txt:CONDA_DEFAULT_ENV=encode-atac-seq-pipeline
test_activate_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_activate_log.txt:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin/encode_common.py
test_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_nov_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
```

and then those that mention that specific `bin` directory:

```bash
$ grep encode-atac-seq-pipeline/bin *log*
test_activate_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_activate_log.txt:PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/scratch/temp/6225767.1.shared.q:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_activate_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_activate_log.txt:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin/encode_common.py
test_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
test_nov_log.txt:SGE_O_PATH=/jhpce/shared/jhpce/core/conda/miniconda-3/envs/encode-atac-seq-pipeline/bin:/jhpce/shared/jhpce/core/git/2.17.0/bin:/users/lcollado/software:/users/lcollado/miniconda3/bin:/users/lcollado/software/rmate/bin:/users/lcollado/software/localruby/bin:/users/lcollado/software/git-lfs-1.5.4:/users/lcollado/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5/R/3.5/bin:/jhpce/shared/jhpce/core/conda/miniconda-3/bin:/cm/shared/apps/sge/2011.11p1/bin/linux-x64:/jhpce/shared/jhpce/core/JHPCE_tools/1.0/bin:/jhpce/shared/jhpce/core/stata/15:/jhpce/shared/jhpce/core/matlab/R2017b/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/jhpce/shared/jhpce/stata/13:/opt/dell/srvadmin/bin
16:08 test_qsub_v
```

First mention of the `encode-atac-seq-pipeline/bin` folder in the test that works:

https://gist.github.com/lcolladotor/3efc1ff4c3c768658961b580332a69f6#file-test_activate_log-txt-L94

beginning of the second `printenv` call

https://gist.github.com/lcolladotor/3efc1ff4c3c768658961b580332a69f6#file-test_activate_log-txt-L106

after `source activate encode-atac-seq-pipeline` now `PATH` contains the correct bin folder: https://gist.github.com/lcolladotor/3efc1ff4c3c768658961b580332a69f6#file-test_activate_log-txt-L144

Best,
Leo

**Comment by leepc12** [comment]
Thanks for your work on this problem. We appreciate it.
`qsub -V` is the problem and it didn't work on your SGE.

Please run the following and check your SGE version and also check if `-V` exists in the help context.
```
$ qsub -help
```

Can you run the following and see if it works?
```
$ source activate encode-atac-seq-pipeline
$ echo "which encode_common.py" | qsub -cwd -o test_log.txt -e test_log.txt -V
```

**Comment by leepc12** [comment]
@lcolladotor : Yes, I think so. This is actually why singularity is recommended for running our pipelines with cluster engines (SGE, SLURM). Until this issue is fixed, please stick to your workaround.

**Comment by lcolladotor** [comment]
Hi @leepc12,

I met J. Seth Strattan at [Biological Data Science](https://meetings.cshl.edu/meetings.aspx?meet=DATA&year=18) and he heavily recommended that we switch to using Singularity instead of Conda. At https://www.sylabs.io/docs/ I see that there are several versions, including a new "major" version (3.0) compared to the minimum one required by your pipeline (2.5.2). Should we install version 3.0 or 2.6? Sometimes major version bumps break some old code, that's why I'm asking (I'm completely new to Singularity).

Best,
Leo

**Comment by leepc12** [comment]
Singularity should not give errors when trying to bind directories that are already bound. I think singularity started to give warnings instead of errors since 2.5.2. But I am not sure.

Please run the following to build a singularity container for our pipeline first.
```
$ SINGULARITY_CACHEDIR=~/.singularity SINGULARITY_PULLFOLDER=~/.singularity singularity pull -F docker://quay.io/encode-dcc/atac-seq-pipeline:v1.1.1
```
And run this Hello World example to check if singularity gives you a warning (or error)
```
$ singularity exec --bind $HOME ~/.singularity/atac-seq-pipeline-v1.1.1.simg echo Hello World
```
If it shows a warning, you can go ahead with your current singularity version.
```
leepc12@kadru:~$ singularity exec --bind $HOME ~/.singularity/atac-seq-pipeline-v1.1.1.simg echo Hello World
WARNING: Not mounting requested bind point (already mounted in container): /users/leepc12/
Hello World
leepc12@kadru:~$
```
Otherwise, you should upgrade it to >=`2.5.2`. BWT I am using `2.5.2-dist`.

**Comment by lcolladotor** [comment]
Thank you for the info! We'll let you know if we have any questions.

Best,
Leo
