### ISSUE TITLE
Test run fails

### ISSUE THREAD

**Issue by jwtobias** [ENCODE-DCC/atac-seq-pipeline#51]
In a local installation with conda the test run (as described in the tutorial) fails.

**OS/Platform and dependencies**
$ uname -a
Linux node061.hpc.local 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

cromwell-34

$ conda -V
conda 4.5.11

[ATACseq_pipeline_error_issueID_51.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2550610/ATACseq_pipeline_error_issueID_51.txt)
[debug_issueID_51.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2550611/debug_issueID_51.tar.gz)

**Comment by leepc12** [comment]
Please remove your locally installed `cutadapt` from your `$PATH`. You may need to edit your `~/.bashrc`.

**Comment by jwtobias** [comment]
This solves the error. I've removed my copy of cutadapt and the test run now proceeds beyond this point.
