### ISSUE TITLE
Can't complete test run

### ISSUE THREAD

**Issue by jwtobias** [ENCODE-DCC/atac-seq-pipeline#52]
[ENCSR356KRQ_subsampled_issue52.json.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2555963/ENCSR356KRQ_subsampled_issue52.json.zip)
[debug_issue52.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2555964/debug_issue52.tar.gz)
[testRun_env_issue52.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2555965/testRun_env_issue52.txt)
[testError_issue52.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2555966/testError_issue52.txt)

Can't complete a test run on a local installation. Although I know that singularity or docker is preferred, that is not possible on this machine.

In addition to the information below I've attached error logs, my input .json file and my environment (after activating encode-atac-seq-pipeline).

$ uname -a
Linux node061.hpc.local 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
$ conda -V
conda 4.5.11

cromwell-34

**Comment by leepc12** [comment]
Your locally install R conflicts with the pipeline.

Please remove your locally installed R from $PATH in your startup script (`~/.bashrc`) or do not `module load` any R.

**Comment by leepc12** [comment]
Please run the following for debugging.
```
$ source activate encode-atac-seq-pipeline
$ which R
$ conda list | grep spp
```

**Comment by jwtobias** [comment]
That's odd, while I have had R 3.5.0 installed in the past, I thought I hid all traces. Here are the responses to the commands above:

$ source activate encode-atac-seq-pipeline

(encode-atac-seq-pipeline) $ which R
~/software/miniconda3/envs/encode-atac-seq-pipeline/bin/R

(encode-atac-seq-pipeline) $ conda list | grep spp
r-spp                     1.13                   r3.2.2_0    bioconda

**Comment by leepc12** [comment]
Did you get any error while installing `conda/install_dependencies.sh`?

**Comment by jwtobias** [comment]
Not that I saw.

**Comment by jwtobias** [comment]
If it's helpful, I uninstalled/reinstalled the environment, activated, and went to the the appropriate directory and reran what I believe is the failing command. Attached are logs of the uninstall/reinstall and the screen output of the redone Rscript command.
[conda uninstall reinstall.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2562371/conda.uninstall.reinstall.txt)
[failing Rscript command output .txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2562372/failing.Rscript.command.output.txt)

**Comment by leepc12** [comment]
Please this for debugging. 
```
$ source activate encode-atac-seq-pipeline
$ Rscript <(echo "installed.packages()") | grep spp
$ Rscript <(echo "installed.packages()")
```
BTW you can disable `xcor` by activating a flag `"atac.disable_xcor" : true,` in your input JSON.

**Comment by jwtobias** [comment]
Results below and attached. It looks like $R_HOME and $R_LIBS are not set.
[troubleShootOutput.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2563176/troubleShootOutput.txt)


[jtobias@node062 ~]$ source activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) [jtobias@node062 ~]$ which conda
~/software/miniconda3/bin/conda
(encode-atac-seq-pipeline) [jtobias@node062 ~]$ which R
~/software/miniconda3/envs/encode-atac-seq-pipeline/bin/R
(encode-atac-seq-pipeline) [jtobias@node062 ~]$ echo $R_HOME

(encode-atac-seq-pipeline) [jtobias@node062 ~]$ echo $R_LIBS

(encode-atac-seq-pipeline) [jtobias@node062 ~]$

**Comment by leepc12** [comment]
It's weird. Everything looks okay. Let's try to re-install `spp`.
```
$ source activate encode-atac-seq-pipeline
$ conda uninstall spp -y
$ conda install phantompeakqualtools -c bioconda -y
```

**Comment by leepc12** [comment]
Please run these too.
```
$ Rscript -e ".libPaths()"
$ Rscript -e "Sys.getenv('R_LIBS_USER')"
```

**Comment by leepc12** [comment]
Before testing, please add between `command {` and `python $(which encode_xcor.py) \` for further debugging.
```
	command {

		#PLEASE ADD THESE LINES TO atac.wdl
		which Rscript
		which conda
		echo $R_HOME
		echo $R_LIBS

		python $(which encode_xcor.py) \
			${ta} \
			${if paired_end then "--paired-end" else ""} \
			${"--subsample " + select_first([subsample,25000000])} \
			--speak=0 \
			${"--nth " + select_first([cpu,2])}
	}
```

**Comment by jwtobias** [comment]
Ok, in response to your comment about reinstalling spp, before you sent the others, I uninstalled spp using:
$ source activate encode-atac-seq-pipeline
$ conda uninstall spp -y
It didn't seem to find spp to uninstall. Nonetheless I ran:
$ conda install phantompeakqualtools -c bioconda -yconda install phantompeakqualtools -c bioconda -y

Before seeing your two additional comments, I reran the test installation and it ran SUCCESSFULLY.

Here are the results for your Rscript commands:
[jtobias@consign starOut]$ source activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) [jtobias@consign starOut]$ Rscript -e ".libPaths()"
[1] "/home/jtobias/software/miniconda3/envs/encode-atac-seq-pipeline/lib/R/library"
(encode-atac-seq-pipeline) [jtobias@consign starOut]$ Rscript -e "Sys.getenv('R_LIBS_USER')"
[1] "~/R/x86_64-pc-linux-gnu-library/3.2"

The second one seems to be pointing to a non-existent directory.

Should I still rerun the test with the additional lines in atac.wdl?

Just to complicate things further, I began to install the deprecated bds pipeline as a backup approach, but I've not yet tried to run it. It's possible, though, that this installation somehow changed my environment.

**Comment by leepc12** [comment]
Could you run these too? This should be the final one.
```
$ source deactivate
$ which Rscript
```

**Comment by jwtobias** [comment]
[jtobias@node065 ~]$ which Rscript
/usr/bin/Rscript

**Comment by leepc12** [comment]
Okay, It looks like Conda's R conflicted with a globally installed R on your system. This will be fixed in the next release.

Until then, for every pipeline run, please define two environment variables after activating the Conda environment and then run pipelines (`java -jar ...`).

```
$ source activate encode-atac-seq-pipeline

$ export R_HOME=/home/jtobias/software/miniconda3/envs/encode-atac-seq-pipeline/lib/R
$ export R_LIBS=/home/jtobias/software/miniconda3/envs/encode-atac-seq-pipeline/lib/R/library

$ java -jar -Dconfig.file=backend/backend.conf ............... # your pipeline command line
```

**Comment by leepc12** [comment]
Please let me know if this works.

**Comment by jwtobias** [comment]
Yes, the test run is working. I made the changes you suggested about the R environment variables and had another successful run. It has been running for me, however, since I uninstalled / re-installed spp per your suggestion:
$ source activate encode-atac-seq-pipeline
$ conda uninstall spp -y
$ conda install phantompeakqualtools -c bioconda -y

**Comment by leepc12** [comment]
@jwtobias: Thanks, closing this.
