### ISSUE TITLE
Pipeline fails using test data

### ISSUE THREAD

**Issue by kirstyjamieson** [ENCODE-DCC/atac-seq-pipeline#55]
Hi Jin,
The atac-seq pipeline fails at BackgroundConfigAsyncJobExecutionActor.  I'm also getting a warning that "Localization via hard link has failed".  Attached is my script and the output.  I'm using coda version 4.5.11 and the .json file you provide.

Thanks,
Kirsty

[run.sh.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2609530/run.sh.txt)
[run.sh.o489151.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2609531/run.sh.o489151.txt)

**Comment by leepc12** [comment]
Did you follow the instruction (step 3 and 4) on https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/tutorial_sge.md? Pipeline failed to find genome database for a test sample.
Also reduce `-Xmx16384M` to 1GB or 2GB. It's too big.

**Comment by kirstyjamieson** [comment]
Yes, I had downloaded the genome database and test sample data.  I checked the directories and discovered missing files and folders after the run failed.  Somehow running the pipeline caused this.  I downloaded everything again and reran and it worked.  Not sure if this is a problem on my cluster or a bug with the pipeline.  I'll let you know if it happens again.

**Comment by leepc12** [comment]
@kirstyjamieson: I see. BTW you can simply ignore the warning `Localization via hard link has failed`. If that fails then it automatically switches to soft link or physical copy.
