### ISSUE TITLE
nodup bam

### ISSUE THREAD

**Issue by kirstyjamieson** [ENCODE-DCC/atac-seq-pipeline#59]
Hi Jin,
Could you provide an example .json file for starting with nodup bam instead of fastq?

Thanks,
Kirsty

**Comment by leepc12** [comment]
Remove any FASTQ definition (`"atac.fastqs*"`) from your input JSON and add
```
    "atac.nodup_bams" : [ "rep1.bam", "rep2.bam" ],
```

**Comment by kirstyjamieson** [comment]
I'm getting an error: 

[error] WorkflowManagerActor Workflow a7b66b90-77f3-47b9-afa6-d874bd8e21ab failed (during ExecutingWorkflowState): Job atac.spr:2:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.


{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "test_genome_database/hg38_local.tsv",
    "atac.nodup_bams" : [ "test_sample/induced/rep1/KJ064_R1_TRIM.trim.nodup.bam", "test_sample/induced/rep2/KJ065_R1_TRIM.trim.nodup.bam", "test_sample/induced/rep3/KJ066_R1_TRIM.trim.nodup.bam"],

    "atac.paired_end" : true,
    "atac.multimapping" : 4,

    "atac.auto_detect_adapter" : true,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.enable_xcor" : true,

    "atac.title" : "induced",
    "atac.description" : "ATAC-seq on induced RPEs",

    "atac.trim_adapter.cpu" : 1,
    "atac.trim_adapter.mem_mb" : 4000,
    "atac.trim_adapter.time_hr" : 1,
    "atac.bowtie2_cpu" : 1,
    "atac.bowtie2_mem_mb" : 4000,
    "atac.bowtie2_time_hr" : 1,
    "atac.filter_cpu" : 1,
    "atac.filter_mem_mb" : 4000,
    "atac.filter_time_hr" : 1,
    "atac.macs2_mem_mb" : 4000,
    "atac.macs2_time_hr" : 1,
    "atac.ataqc.mem_mb" : 4000,
    "atac.ataqc.time_hr" : 1
}

[run.sh.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2621983/run.sh.txt)
[run.sh.o489151.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2621984/run.sh.o489151.txt)

**Comment by leepc12** [comment]
```
test_genome_database/hg38_local.tsv doesn't exist
```
Did you download genome database for test samples?

**Comment by kirstyjamieson** [comment]
Thanks.  I also realized I sent the old run.sh.  This is the current one.

#!/bin/bash
#$ -l arch=linux-x64
#$ -l h_rt=48:0:0
#$ -l mem_free=8G
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -r y

export _JAVA_OPTIONS="-Xms256M -Xmx16384M -XX:ParallelGCThreads=1"
export PATH="/netapp/home/kirsty.jamieson/miniconda3/bin:$PATH"
LIB=/scrapp/kirsty.jamieson/atac-seq-pipeline

source activate encode-atac-seq-pipeline
INPUT=$LIB/examples/local/ENCSR356KRQ_subsampled.json
java -jar -Dconfig.file=$LIB/backends/backend.conf $LIB/cromwell-34.jar run atac.wdl -i ${INPUT}

**Comment by leepc12** [comment]
Please attach a tar ball of all logs for debugging. When you created this issue, you should see an instruction to make a tar ball.

Is there a particular reason that two memory settings differ (`mem_free=8G` and `-Xmx16384M`)?

**Comment by kirstyjamieson** [comment]
No good reason, I'll remove -Xmx16384M in the future.

[debug_[nodup_bam_#55].tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2622319/debug_.nodup_bam_.55.tar.gz)

**Comment by leepc12** [comment]
Your TAG-ALIGN looks trivially small.
```
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen   51 Nov 27 15:31 KJ064_R1_TRIM.trim.nodup.tn5.tagAlign.gz
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen 4060 Nov 27 15:15 script
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen  405 Nov 27 15:15 script.background
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen  163 Nov 27 15:15 script.submit
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen    0 Nov 27 15:15 stderr
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen    0 Nov 27 15:15 stderr.background
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen 2102 Nov 27 15:31 stdout
PID=10830: -rw-r--r-- 1 kirsty.jamieson shen    5 Nov 27 15:15 stdout.background
```
Something is wrong with your BAM inputs?

**Comment by kirstyjamieson** [comment]
I don't think the bam file is the issue.  It was generated from your previous pipeline and gave a reasonable-sized tag-align.

-rw-r--r-- 1 kirsty.jamieson shen 7026944483 Sep 22 12:51 KJ064_R1_TRIM.trim.bam
-rw-r--r-- 1 kirsty.jamieson shen    2793488 Sep 22 12:54 KJ064_R1_TRIM.trim.bam.bai
-rw-r--r-- 1 kirsty.jamieson shen 2319815474 Sep 22 11:37 KJ064_R1_TRIM.trim.fastq.gz
-rw-r--r-- 1 kirsty.jamieson shen 1504625562 Sep 22 13:49 KJ064_R1_TRIM.trim.nodup.bam
-rw-r--r-- 1 kirsty.jamieson shen    6809488 Sep 22 13:50 KJ064_R1_TRIM.trim.nodup.bam.bai
-rw-r--r-- 1 kirsty.jamieson shen  254422820 Sep 22 14:05 KJ064_R1_TRIM.trim.nodup.tagAlign.gz
-rw-r--r-- 1 kirsty.jamieson shen  237655009 Sep 22 14:10 KJ064_R1_TRIM.trim.nodup.tn5.no_chrM.25M.tagAlign.gz
-rw-r--r-- 1 kirsty.jamieson shen  254694043 Sep 22 14:07 KJ064_R1_TRIM.trim.nodup.tn5.tagAlign.gz

**Comment by leepc12** [comment]
Can you upload an input JSON for that previous pipeline run (which starts from FASTQs)?
Is this sample paired end?

**Comment by kirstyjamieson** [comment]
Could you send me a json file that you used for a successful run starting from bam?

**Comment by leepc12** [comment]
@kirstyjamieson: Here is an example input JSON file which starts from `nodup_bams`.
```
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/mnt/data/pipeline_genome_data/hg38_chr19_chrM/hg38_chr19_chrM_klab.tsv",
    "atac.nodup_bams" : [
        "./cromwell-executions/atac/c33c7037-5873-4772-aef2-e748a27b6fd4/call-filter/shard-0/execution/ENCFF341MYG.subsampled.400.trim.merged.nodup.bam",
        "./cromwell-executions/atac/c33c7037-5873-4772-aef2-e748a27b6fd4/call-filter/shard-1/execution/ENCFF641SFZ.subsampled.400.trim.merged.nodup.bam"
    ],
    "atac.qc_report.qc_json_ref" : "/users/leepc12/code/atac-seq-pipeline/test/test_workflow/ref_output/ENCSR356KRQ_subsampled_chr19_only_qc.json",

    "atac.paired_end" : true,
    "atac.align_only" : true,
    "atac.multimapping" : 4,

    "atac.auto_detect_adapter" : true,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.enable_xcor" : true,

    "atac.title" : "ENCSR356KRQ",
    "atac.description" : "ATAC-seq on primary keratinocytes in day 0.0 of differentiation"
}
```

I tested pipelines starting from FASTQs and NODUP_BAMs. Both worked fine. Got the same BED outputs (`*.tagAlign.gz`).
```
$ find -name *.tagAlign.gz | grep -v inputs | grep -v glob | xargs ls -l
-rw-r--r-- 2 leepc12 users 175596 Nov 29 13:02 ./cromwell-executions/atac/c33c7037-5873-4772-aef2-e748a27b6fd4/call-bam2ta/shard-0/execution/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.tagAlign.gz
-rw-r--r-- 2 leepc12 users 225168 Nov 29 13:02 ./cromwell-executions/atac/c33c7037-5873-4772-aef2-e748a27b6fd4/call-bam2ta/shard-1/execution/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.tagAlign.gz
-rw-r--r-- 2 leepc12 users 175596 Nov 29 13:37 ./cromwell-executions/atac/e8d64aa0-6394-409c-a171-1d3e64d6dffa/call-bam2ta/shard-0/execution/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.tagAlign.gz
-rw-r--r-- 2 leepc12 users 225168 Nov 29 13:37 ./cromwell-executions/atac/e8d64aa0-6394-409c-a171-1d3e64d6dffa/call-bam2ta/shard-1/execution/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.tagAlign.gz
```

**Comment by kirstyjamieson** [comment]
I took the nodup bams generated from the successful run when I started at your subsampled fastq and that worked.  I get mixed results when I start with my own tag-align files.  For one pair, it succeeded and for another pair it failed at the very end with:

"SingleWorkflowRunnerActor received Failure message: connection exception: closed java.sql.SQLNonTransientConnectionException: connection exception: closed."

I did manage to get idr peaks before it failed.  

I also tried 3 replicates with tag-aligns and got a different failure, much earlier on:

"WorkflowManagerActor Workflow 72c2bf95-1c83-49e4-9e6f-e48151ac76bb failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs"

So the pipeline seems to work well with subsampled files but fails with my much larger files.

**Comment by leepc12** [comment]
Let's stick to a single failure case (starting from your own large nodup_bam files).

You got this good-sized NODUP_BAM and TAG-ALIGN when you started a pipeline from FASTQ
```
-rw-r--r-- 1 kirsty.jamieson shen 1504625562 Sep 22 13:49 KJ064_R1_TRIM.trim.nodup.bam
-rw-r--r-- 1 kirsty.jamieson shen 254422820 Sep 22 14:05 KJ064_R1_TRIM.trim.nodup.tagAlign.gz
```
But you failed to get the same TAG-ALIGN when you started from NODUP_BAM.

Please upload your input JSON files for those two cases.

**Comment by kirstyjamieson** [comment]
Those files were generated with the previous pipeline.

**Comment by leepc12** [comment]
I have processed >100 large samples from ENCODE and they all worked fine.
It looks like `bam2ta` task failed due to resource limit.

Please increase memory in your job submission shell script first.
```
#$ -l mem_free=24G
```

Also remove all resource settings from your input JSON file. Those resources are too small for your large samples.
```
"atac.trim_adapter.cpu" : 1,
"atac.trim_adapter.mem_mb" : 4000,
"atac.trim_adapter.time_hr" : 1,
"atac.bowtie2_cpu" : 1,
"atac.bowtie2_mem_mb" : 4000,
"atac.bowtie2_time_hr" : 1,
"atac.filter_cpu" : 1,
"atac.filter_mem_mb" : 4000,
"atac.filter_time_hr" : 1,
"atac.macs2_mem_mb" : 4000,
"atac.macs2_time_hr" : 1,
"atac.ataqc.mem_mb" : 4000,
"atac.ataqc.time_hr" : 1
```
Next time please use a template `examples/template_pe.json` (https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/examples/template_pe.json). This template has all default parameters.

**Comment by kirstyjamieson** [comment]
I tried increasing memory and used the default parameters from the template.  I am still getting mixed results.

**Comment by leepc12** [comment]
@kirstyjamieson: Please pick one failed sample and upload error logs, tar balls, input JSON for it.

**Comment by kirstyjamieson** [comment]
[run_induced_nodupbam.sh.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2649994/run_induced_nodupbam.sh.txt)
[run_induced_nodupbam.sh.o525095.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2649996/run_induced_nodupbam.sh.o525095.txt)
[debug_[#59_12_5_18].tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2649997/debug_.59_12_5_18.tar.gz)

induced_nodupbam.json

```
{
    "atac.nodup_bams" : [
        "test_sample/induced/rep1/KJ064_R1_TRIM.trim.nodup.bam",
        "test_sample/induced/rep2/KJ065_R1_TRIM.trim.nodup.bam",
	"test_sample/induced/rep3/KJ066_R1_TRIM.trim.nodup.bam"
    ],

    "atac.title" : "Induced RPEs",
    "atac.description" : "3 replicates for induced RPEs starting from nodup bam.",

    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "genome/hg38/hg38.tsv",
    "atac.paired_end" : true,

    "atac.align_only" : false,
    "atac.true_rep_only" : false,

    "atac.cutadapt_min_trim_len" : 5,
    "atac.cutadapt_err_rate" : 0.1,

    "atac.multimapping" : 0,

    "atac.bowtie2_score_min" : "",

    "atac.dup_marker" : "picard",
    "atac.mapq_thresh" : 30,
    "atac.no_dup_removal" : false,

    "atac.regex_filter_reads" : "chrM",
    "atac.subsample_reads" : 0,

    "atac.enable_xcor" : false,
    "atac.xcor_subsample_reads" : 25000000,

    "atac.keep_irregular_chr_in_bfilt_peak" : false,        

    "atac.cap_num_peak" : 300000,
    "atac.pval_thresh" : 0.01,
    "atac.smooth_win" : 150,

    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.1,

    "atac.disable_ataqc" : false,

    "atac.trim_adapter_cpu" : 2,
    "atac.trim_adapter_mem_mb" : 12000,
    "atac.trim_adapter_time_hr" : 24,
    "atac.trim_adapter_disks" : "local-disk 100 HDD",

    "atac.bowtie2_cpu" : 4,
    "atac.bowtie2_mem_mb" : 20000,
    "atac.bowtie2_time_hr" : 48,
    "atac.bowtie2_disks" : "local-disk 100 HDD",

    "atac.filter_cpu" : 2,
    "atac.filter_mem_mb" : 20000,
    "atac.filter_time_hr" : 24,
    "atac.filter_disks" : "local-disk 100 HDD",

    "atac.bam2ta_cpu" : 2,
    "atac.bam2ta_mem_mb" : 10000,
    "atac.bam2ta_time_hr" : 6,
    "atac.bam2ta_disks" : "local-disk 100 HDD",

    "atac.spr_mem_mb" : 16000,

    "atac.xcor_cpu" : 2,
    "atac.xcor_mem_mb" : 16000,
    "atac.xcor_time_hr" : 6,
    "atac.xcor_disks" : "local-disk 100 HDD",

    "atac.macs2_mem_mb" : 16000,
    "atac.macs2_time_hr" : 24,
    "atac.macs2_disks" : "local-disk 100 HDD",

    "atac.ataqc_mem_mb" : 16000,
    "atac.ataqc_mem_java_mb" : 16000,
    "atac.ataqc_time_hr" : 24,
    "atac.ataqc_disks" : "local-disk 100 HDD"
}
```

**Comment by leepc12** [comment]
Pipeline failed to convert your BAMs into BEDs.

Let's do some line-by-line debugging.
```
YOUR_WORK_DIR=~/temp_dir

mkdir -p $YOUR_WORK_DIR && cd $YOUR_WORK_DIR

source activate encode-atac-seq-pipeline

sambamba sort -n /scrapp/kirsty.jamieson/atac-seq-pipeline/cromwell-executions/atac/6155fd91-835b-4644-b8d5-c4a8642a3263/call-bam2ta/shard-0/inputs/-1239304996/KJ064_R1_TRIM.trim.nodup.bam -o KJ064_R1_TRIM.trim.nodup.nmsrt.bam -t 2

LC_COLLATE=C bedtools bamtobed -bedpe -mate1 -i KJ064_R1_TRIM.trim.nodup.nmsrt.bam | gzip -nc > KJ064_R1_TRIM.trim.nodup.bedpe.gz

zcat -f KJ064_R1_TRIM.trim.nodup.bedpe.gz | awk 'BEGIN{OFS="\t"}{printf "%s\t%s\t%s\tN\t1000\t%s\n%s\t%s\t%s\tN\t1000\t%s\n",$1,$2,$3,$9,$4,$5,$6,$10}' | grep -P -v 'chrM' | gzip -nc > KJ064_R1_TRIM.trim.nodup.tagAlign.gz

zcat -f KJ064_R1_TRIM.trim.nodup.tagAlign.gz | awk 'BEGIN {OFS = "\t"}{ if ($6 == "+") {$2 = $2 + 4} else if ($6 == "-") {$3 = $3 - 5} print $0}' | gzip -nc > KJ064_R1_TRIM.trim.nodup.tn5.tagAlign.gz

ls -l
```

Can you also share your BAM files (`test_sample/induced/rep1/KJ064_R1_TRIM.trim.nodup.bam`, ...) with me via Dropbox (leepc12 at gmail dot com) or Google Drive (leepc12 at gmail dot com)? I would like to replicate this error on my computer.

**Comment by kirstyjamieson** [comment]
Yeah, I can't get to the beds.  I shared the files on google drive.

```
#!/bin/bash
#$ -l arch=linux-x64
#$ -l h_rt=48:0:0
#$ -l mem_free=24G
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -r y

export TMPDIR="/scrapp/kirsty.jamieson/tmp/"
export PATH="/netapp/home/kirsty.jamieson/miniconda3/bin:$PATH"
LIB=/scrapp/kirsty.jamieson/atac-seq-pipeline

source activate encode-atac-seq-pipeline

sambamba sort -n /scrapp/kirsty.jamieson/atac-seq-pipeline/cromwell-executions/atac/6155fd91-835b-4644-b8d5-c4a8642a3263/call-bam2ta/shard-0/inputs/-1239304996/KJ064_R1_TRIM.trim.nodup.bam -o KJ064_R1_TRIM.trim.nodup.nmsrt.bam -t 2

LC_COLLATE=C bedtools bamtobed -bedpe -mate1 -i KJ064_R1_TRIM.trim.nodup.nmsrt.bam | gzip -nc > KJ064_R1_TRIM.trim.nodup.bedpe.gz

zcat -f KJ064_R1_TRIM.trim.nodup.bedpe.gz | awk 'BEGIN{OFS="\t"}{printf "%s\t%s\t%s\tN\t1000\t%s\n%s\t%s\t%s\tN\t1000\t%s\n",$1,$2,$3,$9,$4,$5,$6,$10}' | grep -P -v 'chrM' | gzip -nc > KJ064_R1_TRIM.trim.nodup.tagAlign.gz

zcat -f KJ064_R1_TRIM.trim.nodup.tagAlign.gz | awk 'BEGIN {OFS = "\t"}{ if ($6 == "+") {$2 = $2 + 4} else if ($6 == "-") {$3 = $3 - 5} print $0}' | gzip -nc > KJ064_R1_TRIM.trim.nodup.tn5.tagAlign.gz

ls -l
```

Output
```
-rw-r--r-- 1 kirsty.jamieson shen       1103 Dec  5 13:07 debug.sh
-rw-r--r-- 1 kirsty.jamieson shen         89 Dec  5 13:10 debug.sh.o525406
-rw-r--r-- 1 kirsty.jamieson shen         86 Dec  5 13:28 KJ064_R1_TRIM.trim.nodup.bedpe.gz
-rw-r--r-- 1 kirsty.jamieson shen 1719191526 Dec  5 13:24 KJ064_R1_TRIM.trim.nodup.nmsrt.bam
-rw-r--r-- 1 kirsty.jamieson shen         51 Dec  5 13:28 KJ064_R1_TRIM.trim.nodup.tagAlign.gz
-rw-r--r-- 1 kirsty.jamieson shen         51 Dec  5 13:28 KJ064_R1_TRIM.trim.nodup.tn5.tagAlign.gz
```

**Comment by kirstyjamieson** [comment]
Yes, you are right!  I had a typo in my script from the original pipeline where I generated the bam, so it only recognized the first read of the pair.  Thank you for your help!
