### ISSUE TITLE
Error running test data on SLURM cluster

### ISSUE THREAD

**Issue by erin-a-clark** [ENCODE-DCC/atac-seq-pipeline#60]
Hi Jin,
I'm a little new to programming, so I hope you will bear with me.

I installed the pipeline on our cluster following the SLURM instructions, and downloaded the test data and genome. I think everything worked fine.
`$ ls atac-seq-pipeline/
atac.wdl   conda                cromwell-workflow-logs  ENCSR356KRQ_fastq_subsampled.tar  Jenkinsfile  src                   test_genome_database_hg38_atac.tar
backends   cromwell-34.jar      docker_image            examples                          LICENSE      test                  test_sample
bash_logs  cromwell-executions  docs                    genome                            README.md    test_genome_database  workflow_opts`

I didn't fully understand step 5, but I think I filled in the right info.
`$ cat workflow_opts/slurm.json 
{
    "default_runtime_attributes" : {
        "slurm_partition" : "neuro-largemem",
        "slurm_account" : "neuro",
        "singularity_container" : "~/.singularity/atac-seq-pipeline-v1.1.1.simg"
    }
}`

However, when I tried to run the pipeline on test data it initiates but errors out.
`[2018-11-28 17:42:19,32] [error] WorkflowManagerActor Workflow 09488c8c-8169-4359-9a30-44eb45387723 failed (during ExecutingWorkflowState): Job atac.trim_adapter:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/eaclark/software/atac-seq-pipeline/cromwell-executions/atac/09488c8c-8169-4359-9a30-44eb45387723/call-trim_adapter/shard-0/execution/stderr.
 ImportError: No module named site
ln: failed to access ‘merge_fastqs_R?_*.fastq.gz’: No such file or directory`

I'm not sure what might be wrong that it can't import the module, so I'm hoping you can give me some advice? 
Thank you!
[debug_[eirn.a.clark].tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2627138/debug_.eirn.a.clark.tar.gz)

**Comment by leepc12** [comment]
What was your full command line (`java -jar`) to run a pipeline?

Also please attach a full log from that command line. `[2018-11-28 17:42:19,32] [error] WorkflowManagerActor Workflow 09488c8c-8169-4359-9a30-44eb45387723 ` This is not enough for debugging.

**Comment by leepc12** [comment]
Please run this first.
```
echo $PYTHONHOME $PYTHONHOME 
```

Please remove definition (`export`) for PYTHONHOME and PYTHONHOME from your shell startup script (`~/.bashrc` or `~/.bash_profile`) and re-login.

**Comment by erin-a-clark** [comment]
the full command line was...
`java -jar -Dconfig.file=backends/backend.conf -Dbackend.default=slurm cromwell-34.jar run atac.wdl -i ${INPUT} -o workflow_opts/slurm.json`
...I copied it straight from the instructions.

I ran echo $PYTHONHOME $PYTHONPATH, but I don't see any PYTHONHOME or PYTHONPATH defined in my bash files.

```
$ cat ~/.bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'
```

```
$ cat ~/.bash_profile
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
WORK=/work/eaclark
```

I've also attached the full output from the terminal.
[outputlog2_issue60.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2634407/outputlog2_issue60.txt)

**Comment by erin-a-clark** [comment]
I run
`source activate encode-atac-seq-pipeline`
each time before I try the pipeline. That activates the Conda environment, right?

**Comment by leepc12** [comment]
Please try importing `site` in `python`.
```
$ python
>>> import site
```
If this doesn't work, then pipeline cannot work either.

**Comment by leepc12** [comment]
Please try that again after activating conda env.
```
$ source activate encode-atac-seq-pipeline
$ which python
$ python
>>> import site
```

**Comment by leepc12** [comment]
Please do not use moduled global Anaconda. Instead, install Miniconda3 on your home directory and try again.
https://conda.io/miniconda.html

**Comment by leepc12** [comment]
Sorry there is a typo in the WDL file. This will be fixed in the next release v1.1.4.
Or you can edit line 1055 of your `atac.wdl` file (`hammock_gz`->`hammock.gz`) and try again.
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/atac.wdl#L1055

```wdl
Array[File] conservative_peak_hammock = glob("conservative_peak.*.hammock.gz*")
```

**Comment by erin-a-clark** [comment]
Hi Jin,

I fixed the wdl file, but now I'm getting a new error (not sure if I should start a new issue?) that seems to be related to the filter step given the error below. Tar ball is also attached.
```
> [2018-12-17 13:22:20,93] [error] WorkflowManagerActor Workflow 96fe2586-0b39-45aa-b663-c4c3adf200cc failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
> Bad output 'filter.flagstat_qc': Failed to find index Success(WomInteger(0)) on array:
> 
> Success([])
> 0
> Bad output 'filter.dup_qc': Failed to find index Success(WomInteger(0)) on array:
> Success([])
> 0
> Bad output 'filter.pbc_qc': Failed to find index Success(WomInteger(0)) on array:
> Success([])
> 0
> Bad output 'filter.mito_dup_log': Failed to find index Success(WomInteger(0)) on array:
> Success([])
> 0
```

[debug_ISSUE60_12172018.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2687417/debug_ISSUE60_12172018.tar.gz)

Thanks!

**Comment by leepc12** [comment]
Check your disk space.
```
$ cat ./call-filter/shard-1/execution/stderr
Traceback (most recent call last):
  File "/home/eaclark/.conda/envs/encode-atac-seq-pipeline/bin/encode_filter.py", line 394, in <module>
    main()
  File "/home/eaclark/.conda/envs/encode-atac-seq-pipeline/bin/encode_filter.py", line 333, in main
    dupmark_bam, args.nth, args.out_dir)
  File "/home/eaclark/.conda/envs/encode-atac-seq-pipeline/bin/encode_filter.py", line 227, in rm_dup_pe
    run_shell_cmd(cmd1)
  File "/home/eaclark/.conda/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 263, in run_shell_cmd
    pid, pgid, cmd, ret))
Exception: Killed PID=12836, PGID=12836
CMD=samtools view -@ 1 -F 1804 -f 2 -b ENCFF641SFZ.subsampled.400.trim.merged.dupmark.bam > ENCFF641SFZ.subsampled.400.trim.merged.nodup.bam
STDOUT=[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[main_samview] truncated file.
```

**Comment by erin-a-clark** [comment]
Whoops! Ok, now it's working. Thank you for your help!
