### ISSUE TITLE
Multiple samples with replicates

### ISSUE THREAD

**Issue by berguner** [ENCODE-DCC/atac-seq-pipeline#67]
Hello,

How can we configure/define the fastq arrays for multiple samples with technical replicates? As far as I can understand we can only define a single sample with multiple replicates if we use 1-dimensional arrays. Is this true?

**Comment by leepc12** [comment]
No, 1-dimensional array can take in multiple technical replicates. Those tech reps will be merged together after adapter-trimming tasks. A B C will be merged.
```
{
    "atac.fastqs_rep1_R1" : [ A, B, C ],
}
```

**Comment by berguner** [comment]
I understand that fastq files in a 1-dimensional array will be merged. I was referring to the separate rep1, rep2, ... arrays. For example, we have 2 treatments and a control; treat1, treat2, crtrl, and for each treatment we have 5 samples; sample1, sample2 ... and for each sample we have 3 technical replicates (separate sample preps); rep1, rep2 rep3. How can I define the fastq arrays for this project?

**Comment by leepc12** [comment]
Please try with 2 pipelines with 5 replicates for each pipeline and 3 tech reps (to be merged) for each bio rep.

**Comment by berguner** [comment]
Thank you, I will try it that way.

**Comment by tiagobrc** [comment]
Does that mean that I have to run this pipeline for every pair of comparison?

I am asking this cuz I am confused about the design I need to run this. 
I have 4 cell types (KO and WT) in duplicates.

Am I supposed to run:

**Comment by leepc12** [comment]
Run two separate pipelines for cell1 and cell2. For cell1,

atac.fastqs_rep1_R1 = [WT.Cell1_Samp1_R1.fastq.gz]
atac.fastqs_rep1_R2 = [WT.Cell1_Samp1_R2.fastq.gz]
atac.fastqs_rep2_R1 = [WT.Cell1_Samp2_R1.fastq.gz]
atac.fastqs_rep2_R2 = [WT.Cell1_Samp2_R2.fastq.gz]

**Comment by Baharehh** [comment]
Sorry Jin I had one more question which you addressed it here beautifully but I just want to male sure:
I have 2 experimental conditions: Cre/dCre and 3 samples.
can you please check the below to see if the array seems fine?
-if its fine then seem like in your array,  "rep" is indeed the experimental or biological condition?! and you recommend no more than 4 rep for each run is a good idea?

**atac.fastqs_rep1_R1 = [Cre1_R1.fastq.gz, Cre2_R1.fastq.gz,Cre3_R1.fastq.gz]
atac.fastqs_rep1_R2 = [Cre1_R2.fastq.gz, Cre2_R2.fastq.gz,Cre3_R2.fastq.gz]
atac.fastqs_rep1_R1 = [dCre1_R1.fastq.gz,d Cre2_R1.fastq.gz,dCre3_R1.fastq.gz]
atac.fastqs_rep1_R2 = [dCre1_R2.fastq.gz,dCre2_R2.fastq.gz,dCre3_R2.fastq.gz]**
