### ISSUE TITLE
directory question

### ISSUE THREAD

**Issue by erin-a-clark** [ENCODE-DCC/atac-seq-pipeline#72]
Hi Jin,

Thank you for your help so far! I've run into a little issue that may be easy to fix or just not an option. So far I've been successful in running the pipeline on the test data. I noticed that I have to run it from within the atac-seq-pipeline directory and the input data seems to need to be contained in that directory or a subdirectory as well. I was told by our cluster admin that I should install the pipeline on my $HOME directory but store my large input fastq files and submit my sbatch jobs on my $WORK directory. I've tried a few different things, but I always get errors about the pipeline not finding a directory because it has appended the current working directory to the path I gave it in the json.  

For example, my input data is currently in work/eaclark/fastq. The pipeline is in home/eaclark/atac-seq-pipeline. If I submit the job from within atac-seq-pipeline I get an error because it tried to find the input file in "/home/eaclark/atac-seq-pipeline/work/eaclark/fastq/sample.fastq.gz". So, it took the path I gave in the json which was "work/eaclark/fastq/sample.fastq.gz" and added the current working directory "/home/eaclark/atac-seq-pipeline" in front suggesting to me that it will always look for files in the current directory or subdirectory. I tried it the other way around, ie submit the job from $WORK, but then I get and error that it can't find pipeline files.

It there a way to run the pipeline the way my cluster admin wants? Or is that not an option, and I'll either have to move the input files to home/eaclark/atac-seq-pipeline, or install the pipeline on $WORK. 

I hope my question makes sense.

Thanks!
Erin

**Comment by leepc12** [comment]
The key is to use an absolute path. For example, Your FASTQs definition in your `input.json` file seems to be like this `work/eaclark/fastq/sample.fastq.gz`. You need to edit it to 
 an absolute path like `/somewhere/work/eaclark/fastq/sample.fastq.gz`, which starts from `/` (root).

If you use absolute paths in your input JSON file, you will be just okay. Also for the `java -jar` command line.
```
java -jar -Dconfig.file=/path/to/backends/backend.conf /path/to/cromwell-34.jar /path/to/atac.wdl -i /path/to/your/input.json ...
```
In the input JSON, all FASTQs paths and `genome_tsv` must be absolute (full) paths.
