### ISSUE TITLE
Error in read genome tsv module

### ISSUE THREAD

**Issue by dcdxy** [ENCODE-DCC/atac-seq-pipeline#75]
When running the pipeline on my samples, the following error occurs at the `read_genome_tsv` step:

```
Bad output 'read_genome_tsv.genome': java.io.IOException: Could not read from ~/atac-seq-pipeline/cromwell-executions/atac/8ffa8456-f560-45ae-b478-8a32c14b8e90/call-read_genome_tsv/
execution/tmp.tsv: File ~/atac-seq-pipeline/cromwell-executions/atac/8ffa8456-f560-45ae-b478-8a32c14b8e90/call-read_genome_tsv/execution/tmp.tsv is larger than 128000 Bytes. Maximum
 read limits can be adjusted in the configuration under system.input-read-limits.
```
I'm using `mm10_no_alt_analysis_set_ENCODE.fasta.gz` as my reference genome, which is 830M and seems to be causing the error?

[This discussion](https://github.com/broadinstitute/cromwell/issues/2768) suggests increasing limits in the call to Java (using `java -Dsystem.input-read-limits.lines=500000 -jar /cromwell-34.jar`). Is that the recommended solution in this case as well?

**OS/Platform and dependencies**
- OS or Platform: SGE cluster
- Cromwell/dxWDL version: `cromwell-34.jar`
- Conda version: `conda 4.3.30`

Please find logs here: 
[debug_75.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2756892/debug_75.tar.gz)

**Comment by leepc12** [comment]
You should not use `mm10_no_alt_analysis_set_ENCODE.fasta.gz` as `atac.genome_tsv` in your input JSON. Instead. find `mm10_*.tsv` on your genome database installation directory and use it for `atac.genome_tsv`.

**Comment by dcdxy** [comment]
Realized my mistake after posting! Sorry!
