### ISSUE TITLE
Processed bed files from Corces MR et al., 2017 paper

### ISSUE THREAD

**Issue by satyanarayan-rao** [ENCODE-DCC/atac-seq-pipeline#79]
Hi, 

I am guessing (please confirm so) that [Corces MR](https://www.nature.com/articles/nmeth.4396) et al., 2017 paper used _this_ pipeline for their ATAC-seq data processing. I am wondering if they re-processed previously published data ([GM12878](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE47753&format=file&file=GSE47753%5FGM12878%5FATACseq%5F50k%5FAllReps%5FZINBA%5Fpp08%2Ebed%2Egz) and [CD4+](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE47753&format=file&file=GSE47753%5FCD4%2B%5FATACseq%5FAllDays%5FAllReps%5FZINBA%5Fpp08%2Ebed%2Egz)) from [Buenrostro JD](https://www.nature.com/articles/nmeth.2688) et al., 2013 paper using this pipeline. Please let me know if it has been deposited with another accession number. 

Again, it will save much of my time and compute power if I can get to know where the processed bed/bigBed files are deposited for [Corces MR](https://www.nature.com/articles/nmeth.4396) et al., 2017 paper.

Your help is very much appreciated! 

Sincerely, 
Satya

**Comment by akundaje** [comment]
No they did not use this pipeline. So you would have to reprocess it (which I recommend doing).

**Comment by satyanarayan-rao** [comment]
Thanks a lot, @akundaje for your suggestion!

Thanks,
Satya
