### ISSUE TITLE
Enabling atac.multimapping inflates read counts in QC reports

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#80]
When I run the pipeline with atac.multimapping > 1, the following read count statistics are inflated in the QC report:

- flaqstat_qc: total
- flagstat_qc: mapped
- ataqc: read count from sequencer
- ataqc: read count successfully aligned
- ataqc: read count after filtering for mapping quality
- ataqc: read count after removing duplicate reads
- ataqc: read count after removing mitochondrial reads (final read count) - this does correspond to the number of reads in the filtered BAM file, but it misrepresents the number of reads removed due to MT

Can you please adjust the code to output statistics for just the primary reads at all of these steps? The inflated counts are very difficult to interpret.

**Comment by leepc12** [comment]
Sorry for late response, we will look into this problem and will let u know.

**Comment by nicolerg** [comment]
Hi @leepc12, has this been fixed?

**Comment by leepc12** [comment]
Sorry about late response. we will be working on this next week and make a fix. We will let you know.

**Comment by nicolerg** [comment]
Can you please look into this? The fix should only be a matter of filtering down to primary alignments before reporting `samtools view -c`.

**Comment by leepc12** [comment]
@vervacity : Could you take a look at this issue?
