### ISSUE TITLE
MT reads in filtered BAM file?

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#81]
Are there supposed to be mitochondrial reads in the filtered BAM file? One of the ATAQC metrics is "Read count after removing mitochondrial reads (final read count)," which does correspond to the number of reads in the filtered BAM file, but I don't see a command within `call-filter` that explicitly removes MT reads, and there remains a small fraction of MT reads in the filtered BAM (~1-6%).

**Comment by akundaje** [comment]
We currently don't explicitly filter the chrM reads from the final filtered BAM. We remove in the final BAM -. tagAlign stage so they dont go into downstream steps. But its probably good to be consistent. So I think we should modify the filtering step to remove chrM reads from the final filtered BAM file as well.

**Comment by leepc12** [comment]
@akundaje: okay. this will be fixed in the next release (v1.1.7).

**Comment by strattan** [comment]
@nicolerg thank you for this.  No matter what we should be clear in the metadata about when we do or do not count MT reads.

It would be OK to apply this change to ATAC and reprocess all existing ENCODE ATAC experiments from fastqs (there are only 90 with released mappings anyway).  But that would make ChIP and ATAC bams different, and introduce some code divergence between the sister pipelines.

If we were to apply the change to ChIP, too, I'm worried about the ~6000 existing ChIP experiments with MT reads in their filtered bams.  While it's confusing to have MT reads in the bams and then have them not used, it might be more confusing to have ENCODE2 and ENCODE3 bams with MT reads and ENCODE4 bams without them.  Introducing a new output_type would, in principle, disambiguate, but that property is already heavily overloaded.

We could implement this and leave the MT filtering step in bam2ta, which would be a no-op for bams with MT already filtered, but would allow the pipeline to consume existing bams and work OK.  So we could make the pipeline work with old and new data that way.  But the inconsistency with existing ENCODE and Roadmap data seems troubling.  Not to mention the other projects (IHEC) who have adopted our pipeline.  Changing the bams is pretty fundamental.

We could make this change to ChIP the next time we remap (to new assembly, or something like that).

Leaving the ATAC reprocessing issue aside, is it worth making ChIP and ATAC different to address the issue of bams having MT reads that are not used?

**Comment by akundaje** [comment]
Good point @strattan . After thinking about this a bit more I am convinced we should keep things as is. 
(1) Keep chrM in the final filtered BAM files for ChIP-seq and ATAC-seq/DNase-seq.
(2) For ATAC and DNase remove chrM reads before calling peaks i.e. the tagAligns.

Rationale:
1. ChIP-seq signal on chrM is real i.e. we can absolutely detect legitimate binding events on chrM with ChIP-seq. See for example http://gbe.oxfordjournals.org/content/early/2014/09/22/gbe.evu210.abstract
So we definitely do NOT want to filter chrM reads from the ChIP-seq BAM files.

2. With ATAC-seq and DNase, Tn5/DNase completely chews up chrM so there isnt any legitimate signal to call peaks on chrM. Also the huge copy number of chrM can mess with peak calling and signal normalization. So we want to filter these out before peak calling and signal generation as we currently do. HOWEVER, TF footprints can be found in chrM read profiles (see https://genome.cshlp.org/content/28/8/1158). So we should NOT be filtering out chrM reads from the final filtered BAM files either as the BAM files are used for many purposes including footprint detection.

@leepc12 @strattan So we should keep the protocol as it is. But document it clearly.

@strattan Thanks for having me take a second look and think about this more.

**Comment by leepc12** [comment]
MT reads will be removed in filtered/deduped BAM in the next release (1.5.0) so that it's consistent with TAG-ALIGN converted from it.
