### ISSUE TITLE
Inconsistant behavior of pipeline-runs (not sure if it's a bug)

### ISSUE THREAD

**Issue by ravipatel4** [ENCODE-DCC/atac-seq-pipeline#84]
Hello,

I ran the atac-seq-pipeline four time with same JSON file and same command line, since I wanted to test the output consistency. I am mainly interested in IDR analysis on already filtered BAM files. I find that the pipeline runs successfully sometimes and fails with different errors other times. Following are my commands and attached are corresponding STDERRs and a debug tar ball. Please let me know if I am doing anything wrong.

OS: CentOS Linux release 7.4.1708 (Core)
Resources: 32 cores; 128GB RAM
Cromwell: cromwell-34.jar
Conda version: 4.5.11

#Command 1: ran successfully with non-empty output
nohup java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run atac.wdl -i my.json >& my.log &
#Command 2: terminated with error type 1
nohup java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run atac.wdl -i my.json &> my_reran.log
#Command 3: terminated with error type 2
nohup java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run atac.wdl -i my.json &>my_reran2.log
#Command 4: ran successfully with non-empty output
nohup java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run atac.wdl -i my.json &>my_reran3.log

Please let me know if you need any further information. Thank you for your help in advance.

Best,
Ravi

[debug.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2862429/debug.tar.gz)
[stderrs.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2862430/stderrs.txt)

**Comment by leepc12** [comment]
Found an error in one of your logs (`./cromwell-executions/atac/c7d3a7ae-f129-4424-bc3d-63aa5679431d/call-overlap/shard-0/execution/stdout`)
```
[2019-02-13 14:55:13,545 INFO] run_shell_cmd: PID=35957, CMD=intersectBed  -wo -a Adult-Il1218-1.R1.Adult-Il1218-1.R2.filtered.tn5.pooled.pval0.01.300K.narrowPeak.tmp_pooled -b Adult-Il1218-1.R1.Adult-Il1218-1.R2.filtered.tn5.pval0.01.300K.narrowPeak.tmp1 | awk 'BEGIN{FS="\t";OFS="\t"} {s1=$3-$2; s2=$13-$12; if (($21/s1 >= 0.5) || ($21/s2 >= 0.5)) {print $0}}' | cut -f 1-10 | sort | uniq | intersectBed  -wo -a stdin -b Adult-Il1218-2.R1.Adult-Il1218-2.R2.filtered.tn5.pval0.01.300K.narrowPeak.tmp2 | awk 'BEGIN{FS="\t";OFS="\t"} {s1=$3-$2; s2=$13-$12; if (($21/s1 >= 0.5) || ($21/s2 >= 0.5)) {print $0}}' | cut -f 1-10 | sort | uniq | gzip -nc > rep1-rep2.overlap.narrowPeak.gz
PID=35957: /programs/miniconda3/envs/encode-atac-seq-pipeline/bin/intersectBed: line 2: /programs/miniconda3/envs/encode-atac-seq-pipeline/bin/bedtools: Input/output error
PID=35957: uniq: write error: Broken pipe
```
It looks like `overlap` task failed due to some unknown reason on your file system (maybe on `/programs/`? is it on a fast/stable storage?) but the pipeline couldn't catch this error code.

The second problem (catching an error code) is a bug and will be fixed in the next release but still wonder why the first problem (`Input/output error`) occurred during the pipeline run. This explains why some of your pipeline runs randomly failed. Please uninstall conda and its dependencies on `/programs/` and reinstall them somewhere on your home directory `/home/$USER/` and try again.

**Comment by ravipatel4** [comment]
Hi Jin,

Thank you for the message. I think you were right about limited resources. I didn't realize that each run was using more than 48GB of virtual memory. I was running 3-4 runs in parallel. Although I have 128GB RAM, maybe the server (managed by our bioinformatic department) was killing some of them randomly since they were using lot of resources(?). But when I run them in sequential order, they run successfully. 
But also our /program/ directory is located on a different machine than where my data is, and maybe that had some effect on the unstable behavior of the pipeline on our server. 

Thank you for your help.
