### ISSUE TITLE
json mem and cpu settings not followed

### ISSUE THREAD

**Issue by lefty556** [ENCODE-DCC/atac-seq-pipeline#87]
Hi,

If I run the examples/local/ENCSR356KRQ_subsampled.json pipeline, I've found that the cpu and memory settings are not getting set on my cluster when I customize those values.  It appears to just be using the default values for trim_adapter and bowtie2, for example, per:
https://encode-dcc.github.io/wdl-pipelines/input_json_atac.html

For example, if I change to these values, it still only runs with 4 cpus for bowtie, even though 8 are set.

"atac.trim_adapter.cpu" : 5,
    "atac.trim_adapter.mem_mb" : 8000,
    "atac.trim_adapter.time_hr" : 1,
    "atac.bowtie2_cpu" : 8,
"atac.bowtie2_mem_mb" : 8000,

I tried changing the . to a _ and then it seemed to work, and then the cpus requested matched my json:

    "atac.trim_adapter_cpu" : 6,
    "atac.trim_adapter_mem_mb" : 11000,
    "atac.trim_adapter_time_hr" : 8,
    "atac.bowtie2_cpu" : 8,
    "atac.bowtie2_mem_mb" : 20000,

Is the documentation and example json files correct on the format for those?

OS:  Centos Linux 7.5
atac-seq version: 1.1.6
cluster scheduler:  PBS based

**Comment by leepc12** [comment]
That documentation page has been deprecated. We will remove that soon not to confuse users.

`"atac.trim_adapter.cpu" : 5` has changed to `"atac.trim_adapter_cpu" : 5`.

Please take a look at new documentation [here](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/input.md).

**Comment by lefty556** [comment]
Thanks.  Just a heads up some of the /example json files are still using the old format and not the new format as specified in the new documentation for cpu and mem.  
For example:
examples/local/ENCSR356KRQ_subsampled.json
examples/scg/ENCSR356KRQ_subsampled_chr19_only_scg.json

Thanks!

**Comment by leepc12** [comment]
@lefty556 Thanks for reporting this. This will be fixed in the next release.
