### ISSUE TITLE
failure to read 2 columns in genome tsv

### ISSUE THREAD

**Issue by aschulmann** [ENCODE-DCC/atac-seq-pipeline#88]
When I run the local version of the pipeline, my genome tsv file does not seem to be properly read.
The error log I get is:
```
Bad output 'read_genome_tsv.genome': TSV must be 2 columns to convert to a Map
```
My tsv file seems to be in order (prebuilt mm10 downloaded from ENCODE).
I would highly appreciate your help in understanding this error message as the file does have two columns:
[mm10.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2907334/mm10.txt)
The character encoding is ASCII. The Linux version of our cluster is Scientific Linux release 7.3 (Nitrogen).
Thanks!

**Comment by leepc12** [comment]
I tested your `mm10.txt` with the following tester WDL script and it works fine.
`read_genome_tsv` task is used in the pipeline.
```
workflow test {
        call read_genome_tsv { input:genome_tsv = "mm10.txt" }
}

task read_genome_tsv {
        File genome_tsv
        command {
                cat ${genome_tsv} > 'tmp.tsv'
        }
        output {
                Map[String,String] genome = read_map('tmp.tsv')
        }
        runtime {
                cpu : 1
                memory : "4000 MB"
                time : 1
                disks : "local-disk 50 HDD"
        }
}
```

```
$ java -jar ~/cromwell-34.jar run test.wdl
```
Can you test this WDL script on other OS/platforms? If that doesn't work we may need to report this to [cromwell's git repo](https://github.com/broadinstitute/cromwell/issues).

**Comment by aschulmann** [comment]
The test.wdl works on my system, so I'm not sure what made the atac.wdl fail?

**Comment by aschulmann** [comment]
Looks like the problem is with the configuration file. (I was using the one in backends/backend.conf) Which configs should I use for running the pipeline either on a local system or with a LSF job scheduler?

**Comment by aschulmann** [comment]
Problem solved. It was due to something wrong in the config file. Thanks
