### ISSUE TITLE
Run test sample: samtools error

### ISSUE THREAD

**Issue by madaojjc** [ENCODE-DCC/atac-seq-pipeline#90]
I installed atac-seq-pipeline successfully by conda, and used "source activate encode-atac-seq-pipelinenut", but when I tried to run the test data, the samtools seemed to be wrong.

Here is the content of stderr for potential additional information: /media/shen/disk3/biosoft/encode-atac-seq-pipeline/atac-seq-pipeline/cromwell-executions/atac/87bcb49f-38f6-4943-9357-5e2de6ac56f1/call-bowtie2/shard-1/execution/stderr.

Traceback (most recent call last):
  File "/home/shen/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bowtie2.py", line 207, in <module>
    main()
  File "/home/shen/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bowtie2.py", line 169, in main
    args.out_dir)
  File "/home/shen/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_bowtie2.py", line 116, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/shen/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 263, in run_shell_cmd
    pid, pgid, cmd, ret))
Exception: Killed PID=38790, PGID=38790
CMD=bowtie2 -k 4  -X2000 --mm --local --threads 30 -x GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta -1 /media/shen/disk3/biosoft/encode-atac-seq-pipeline/atac-seq-pipeline/cromwell-executions/atac/87bcb49f-38f6-4943-9357-5e2de6ac56f1/call-bowtie2/shard-1/inputs/-1868768962/merge_fastqs_R1_ENCFF641SFZ.subsampled.400.trim.merged.fastq.gz -2 /media/shen/disk3/biosoft/encode-atac-seq-pipeline/atac-seq-pipeline/cromwell-executions/atac/87bcb49f-38f6-4943-9357-5e2de6ac56f1/call-bowtie2/shard-1/inputs/-1868768962/merge_fastqs_R2_ENCFF031ARQ.subsampled.400.trim.merged.fastq.gz 2>ENCFF641SFZ.subsampled.400.trim.merged.align.log | samtools view -Su /dev/stdin | samtools sort - ENCFF641SFZ.subsampled.400.trim.merged
STDOUT=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
[main_samview] failed to write the SAM header
[E::bgzf_close] File write failed
samtools view: error closing standard output: -1

**Comment by madaojjc** [comment]
samtools --version
samtools 1.9
Using htslib 1.9

**Comment by hmaryam** [comment]
I have the same problem. have you figured out a way to solve it?

**Comment by madaojjc** [comment]
No, I haven't......






At 2019-05-10 18:43:34, "hmaryam" <notifications@github.com> wrote:


I have the same problem. have you figured out a way to solve it?

**Comment by hmaryam** [comment]
I solved my problem. 
In my case, i realized that the problem with my perl. noting that bowtie2 that is used for the alignment is a perl program, that made sense.
Running the following command, I got the error "can't locate strict.pm:"
$perl -V 

I would say, you also run this command and first make sure that you have the permission. solving this problem, I could run the pipeline .

**Comment by madaojjc** [comment]
got it ！  I will try it ，THANKS A LOT！！






At 2019-05-16 04:17:58, "hmaryam" <notifications@github.com> wrote:


I solved my problem.
In my case, i realized that the problem with my perl. noting that bowtie2 that is used for the alignment is a perl program, that made sense.
Running the following command, I got the error "can't locate strict.pm:"
$perl -V

I would say, you also run this command and first make sure that you have the permission. solving this problem, I could run the pipeline .

**Comment by jbergenstrahle** [comment]
Hi, having the exact same error. However, doesn't seem to be any problem with $perl. Did you solve your issue @madaojjc ?

**Comment by madaojjc** [comment]
No, I havn't sovled this issue...  I am using R package ATACseqQC, Bowtie, MACS14/Genrich to analysis ATAC-seq now..






At 2019-07-08 16:47:13, "Joseph Bergenstråhle" <notifications@github.com> wrote:


Hi, having the exact same error. However, doesn't seem to be any problem with $perl. Did you solve your issue @madaojjc ?

**Comment by leepc12** [comment]
It looks like your samtools is too new. samtools should be 1.2. Check if you have samtools installed in your main Conda env.
```
# do this without activating pipeline's Conda environment
$ conda activate
$ which samtools
$ samtools version
```

**Comment by jbergenstrahle** [comment]
You were correct @leepc12, I had 1.9. Changed to 1.2. Now this seems to fix the first problem, but still results in error during the same step, just that now I get no clue at all from STDERR unfortunately:

```
 Traceback (most recent call last):
  File "/home/joseph.b/atac-seq-pipeline/src/encode_bowtie2.py", line 214, in <module>
    main()
  File "/home/joseph.b/atac-seq-pipeline/src/encode_bowtie2.py", line 176, in main
    args.out_dir)
  File "/home/joseph.b/atac-seq-pipeline/src/encode_bowtie2.py", line 120, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/joseph.b/atac-seq-pipeline/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=119820, PGID=119820, RC=127
STDERR=
STDOUT=
```

**Comment by leepc12** [comment]
Did you activate conda env? Please also check bowtie2 version It should be 2.2.6.

**Comment by madaojjc** [comment]
Got it ! THANKS!  Actually, I am using R package ATACseqQC, Bowtie, MACS14/Genrich to analysis ATAC-seq now ......







At 2019-07-08 23:34:37, "Jin Lee" <notifications@github.com> wrote:

Did you activate conda env? Please also check bowtie2 version It should be 2.2.6.

**Comment by madaojjc** [comment]
Got it ! THANKS!  Actually, I am using R package ATACseqQC, Bowtie, MACS14/Genrich to analysis ATAC-seq now ......






At 2019-07-08 22:34:01, "Joseph Bergenstråhle" <notifications@github.com> wrote:


You were correct @leepc12, I had 1.9. Changed to 1.2. Now this seems to fix the first problem, but still results in error during the same step, just that now I get no clue at all from STDERR unfortunately:

 Traceback (most recent call last):
  File "/home/joseph.b/atac-seq-pipeline/src/encode_bowtie2.py", line 214, in <module>
    main()
  File "/home/joseph.b/atac-seq-pipeline/src/encode_bowtie2.py", line 176, in main
    args.out_dir)
  File "/home/joseph.b/atac-seq-pipeline/src/encode_bowtie2.py", line 120, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/joseph.b/atac-seq-pipeline/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=119820, PGID=119820, RC=127
STDERR=
STDOUT=

**Comment by leepc12** [comment]
Error 127 is "command not found". looks like another conda activation issue. Please check if you have conda after activating environmnet.

```
source activate encode-atac-seq-pipeline
which bowtie2
```

BTW. To fix all samtools-related Conda issues, samtools in the pipeline will be updated to 1.7 in the next release.

BTW2. Please try with Caper and take advantage of its auto-troubleshooting feature.

**Comment by jbergenstrahle** [comment]
@leepc12 after running into several issues with Conda I changed to singularity and the test case was directly successful! 
However, running with my real samples I stumble upon 

`"message": ":\nStream terminated without completing IO operation.\n\tEntityStreamSizeException: actual entity size (Some(4166225920)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream."
`

This seems to be at the bowtie2 step. I know that you've stated that this step is sensitive regarding computational needs. I'm running on a sever, so shouldn't have that much of an issue with this. Is it these values that I should change i the .json?
`
atac.bowtie2_cpu 
atac.bowtie2_mem_mb 
atac.bowtie2_time_hr
`
I've tried to up the mem values a lot, but running into the same problem. Do you have any suggestion or if I'm looking at the wrong place?

Sorry if this ran into OT on this thread.

**Comment by leepc12** [comment]
You are running with Caper?

**Comment by madaojjc** [comment]
No..






At 2019-07-13 05:34:17, "Jin Lee" <notifications@github.com> wrote:


You are running with Caper?

**Comment by jbergenstrahle** [comment]
> You are running with Caper?

Yes!

**Comment by leepc12** [comment]
@jbergenstrahle Please upload your input JSON file for your real sample and also post your full Caper command line here.

@madaojjc There will be a new release for the pipeline by end of this week. This version will have a compatibility with samtools 1.2 and higher. So you can keep your samtools 1.9. It's very hard to debug if you don't use Caper. Can we try Caper and see if it fixes your problem?

**Comment by jbergenstrahle** [comment]
sure!

`caper run atac.wdl -i testRun.json --deepcopy --use-singularity
`
[testRun.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3394039/testRun.zip)

**Comment by leepc12** [comment]
@jbergenstrahle looking at your input JSON file. Pipeline can take up to 10 replicates. I think you have too many replicates for one pipeline. Why don't you run pipelines individually for each replicate? Or if some of those replicates are technical replicates for a biological replicate then you can merge them into one replicate.

```
    "atac.fastqs_rep1_R1" : [ "/home/joseph.b/Enric/fastq/P6978_2063_S103_L006_R1_001.fastq.gz", "/home/joseph.b/Enric/fastq/P6978_2064_S104_L006_R1_001.fastq.gz"],
    "atac.fastqs_rep1_R2" : [ "/home/joseph.b/Enric/fastq/P6978_2063_S103_L006_R2_001.fastq.gz", "/home/joseph.b/Enric/fastq/P6978_2064_S104_L006_R2_001.fastq.gz"],
```

Can you try running with only one replicate?

**Comment by jbergenstrahle** [comment]
@leepc12 running into the same error with only one replicate actually. Not sure if it's any helpful but I've uploaded the complete log:

[log.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3397012/log.txt)

There are several warnings before the errors, I'm not sure if these are problematic or not, or if you can get any clue there?

**Comment by leepc12** [comment]
I haven't seen this error.  Can you try with `-n` (running without file DB)?
```
$ caper run atac.wdl ... -n
```

**Comment by jbergenstrahle** [comment]
not sure if I understand you correctly, just same command by with -n at the end? this is the immediate output:

`Traceback (most recent call last):
  File "/home/joseph.b/miniconda3/bin/caper", line 13, in <module>
    main()
  File "/home/joseph.b/miniconda3/lib/python3.7/site-packages/caper/caper.py", line 1125, in main
    c.run()
  File "/home/joseph.b/miniconda3/lib/python3.7/site-packages/caper/caper.py", line 201, in run
    backend_file = self.__create_backend_conf_file(tmp_dir)
  File "/home/joseph.b/miniconda3/lib/python3.7/site-packages/caper/caper.py", line 746, in __create_backend_conf_file
    backend_str = self.__get_backend_conf_str()
  File "/home/joseph.b/miniconda3/lib/python3.7/site-packages/caper/caper.py", line 846, in __get_backend_conf_str
    db_timeout=self._db_timeout))
  File "/home/joseph.b/miniconda3/lib/python3.7/site-packages/caper/caper_backend.py", line 98, in __init__
    self['database']['db']['connectionTimeout'] = db_timeout
KeyError: 'db'`

**Comment by leepc12** [comment]
That `db` error is fixed now. Please try with Caper 0.3.15
```
pip install caper==0.3.15  # or pip3 install
```

**Comment by jbergenstrahle** [comment]
ok! The -n flag works now without db error. However, the result is the same as running without n unfortunately.

**Comment by leepc12** [comment]
Can you guys install container utilities like docker or singularity and they with them? Or try on `gcp` (google cloud platform). I think you are having troubles in a Conda dependency hell.

**Comment by leepc12** [comment]
Closing this due to long inactivity
