### ISSUE TITLE
Thorough guide/tutorial

### ISSUE THREAD

**Issue by CodeInTheSkies** [ENCODE-DCC/atac-seq-pipeline#91]
Hello there,

Is there a more thorough guide that describes how to run the pipeline in a step-by-step manner, and also understand the various output plots made by the pipeline?  The only description document I could find is this:

https://www.encodeproject.org/documents/c008d7bd-5d60-4a23-a833-67c5dfab006a/@@download/attachment/ATACSeqPipeline.pdf

I would appreciate a pointer to another guide or documentation file if it exists. 

Many thanks.

**Comment by leepc12** [comment]
That is a full spec doc. Please take a look at README on this repo. There is a tutorial for each platform.

**Comment by leepc12** [comment]
Closing this due to long inactivity
