### ISSUE TITLE
Why does encode_trim_adapter.py require gzipped fastqs?

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/atac-seq-pipeline#93]
**Describe the bug**
[cutadapt](https://cutadapt.readthedocs.io/en/stable/guide.html#basic-usage) supports both fastq and fastq.gz so why does this pipeline only support fastq.gz? Would it be possible to add support for regular old fastq? 

**OS/Platform and dependencies**
- Debian 8.11
- Cromwell 34 in server mode.
- local backend, trying to run this pipeline via docker: workflowOptions: 
```
    "default_runtime_attributes" : {
        "docker" : "quay.io/encode-dcc/atac-seq-pipeline:v1.1.6",
```

**Attach error logs**
```
 Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_trim_adapter.py", line 269, in <module>
  ....
IOError: Not a gzipped file
```

**Comment by leepc12** [comment]
[This will be fixed](https://github.com/ENCODE-DCC/atac-seq-pipeline/pull/85/commits/c8b7d79559f25f1fd7e8ccdd7b239a55a7ac08cf) in the next release (v1.1.7).

**Comment by zfrenchee** [comment]
@leepc12 do you have a target release date or estimate for v1.1.7 ? (thanks!)

**Comment by leepc12** [comment]
@zfrenchee : It will be released today.
