### ISSUE TITLE
Bad output 'macs2_pr1.npeak'

### ISSUE THREAD

**Issue by clemenshug** [ENCODE-DCC/atac-seq-pipeline#95]
I am running the pipeline on some published datasets using the default .json file and Slurm/conda submission script as a template. The example dataset ran without problems.

The pipeline fails with cromwell reporting multiple errors like this:
```
Bad output 'macs2.npeak': Failed to find index Success(WomInteger(0)) on array:
Success([])
```

The full logs of chromwell, the submission script and sample json file are attached here: [job_data_issue_ 95.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2963953/job_data_issue_.95.tar.gz)

I looked at the similar issue #17, but in my case `find -name *.tagAlign.gz | xargs ls -l` doesn't show any empty TAG-ALIGN files.

Thanks for your help!

**OS/Platform and dependencies**
- OS or Platform: HMS o2 cluster `Linux version 3.10.0-327.3.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Dec 9 14:09:15 UTC 2015`
- Cromwell/dxWDL version: `cromwell-34.jar`
- Conda version: `conda 4.6.7`

```
$ find -name stderr -not -empty | xargs tail -n +1
```
Did not find any non-empty logs.

```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_[ISSUE_ID].tar.gz
```
[debug_issue_95.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2963954/debug_issue_95.tar.gz)

**Comment by leepc12** [comment]
MACS2 unfiltered narrow peak (`macs2.npeak`) is successfully generated on macs2 directory in a task level but the pipeline couldn't find it.

What is your pipeline version? Did you update conda env by `conda/update_conda.env.sh` after updating (git pull, git clone) the pipeline?

**Comment by clemenshug** [comment]
Originally I used 5f1a591. Now I updated to 56c7086, re-ran `conda/update_conda.env.sh` and resumed the previous run. Unfortunately, I ran into the same issue again.

Is there a way to find out where the pipeline was looking for the files? I tried to find something relevant in the cromwell output with `LOG_LEVEL=DEBUG`, but I'm not quite sure what to look for. I attached it here.

[slurm-37119232.out.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2992700/slurm-37119232.out.gz)

**Comment by leepc12** [comment]
Can you try again on a different storage if possible? It's very hard to figure out. I took a very close look at log files and all MACS2 tasks are done successfully but pipeline failed to glob it. BTW, LOG_LEVEL=DEBUG is too detailed. Please use LOG_LEVEL=INFO.

**Comment by leepc12** [comment]
Closing this due to long inactivity
