### ISSUE TITLE
[DOC]: How to pass through runtime-attributes from WDL to backend

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/atac-seq-pipeline#97]
When I run this workflow, I get this warning from cromwell: 

```
slurm [UUID(91b3f4ed)]: Key/s [cpu, memory, time, disks] is/are not supported by backend. Unsupported attributes will not be part of job executions.
```

I believe what's causing this message is that I have a [SLURM backend to cromwell](https://cromwell.readthedocs.io/en/develop/backends/SLURM/) configured with runtime attributes, e.g. 
```
    runtime-attributes = """
    Int runtime_minutes = 600
    Int cpus = 2
    Int requested_memory_mb_per_core = 8000
    """
```

But this ATAC pipeline has attributes of this sort defined in the WDL independently for each task, e.g.

https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/ab1ef63c93e25b06751d54901014b0ca444ec1f5/atac.wdl#L118-L121

which get passed as 

https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/ab1ef63c93e25b06751d54901014b0ca444ec1f5/atac.wdl#L436-L439

I haven't set up any way to "pass through" these WDL parameters to my SLURM backend. Would it be possible to document how to configure a backend to use the parameters from the WDL? I might not be looking hard enough, but haven't found examples/docs in this repo. 

Many thanks.

**Comment by leepc12** [comment]
You should use our backend file (`backends/backend.conf`). Cromwell's example SLURM backend does not work with our pipeline.

Those resource parameters got passed into a task are again passed to the SLURM backend defined in our backend file.

You can actually ignore these warnings.

**Comment by zfrenchee** [comment]
I'm using this repo's backend file, but cromwell is giving me the warning message (for each job in the pipeline): 

```
slurm [UUID(91b3f4ed)]: Key/s [cpu, memory, time, disks] is/are not supported by backend. Unsupported attributes will not be part of job executions.
```

Is there a way to verify that these warning messages are wrong as you suggest, i.e. that the correct cpu, memory, time, and disks are allocated to the individual jobs in this pipeline?

**Comment by leepc12** [comment]
Those resource parameters are used differently for each platform. For example, `disks` is a parameter required for cloud platforms (DNAnexus, GCP: Google Cloud Platform) only to determine the type of an elastic disk attached to an instance. `cpu` and `memory` are used to determine an instance type on cloud platforms. But they are used for specifying number of cores (threads) / max memory in `qsub`/`sbatch` for cluster engines like SGE/SLURM on HPCs. 

If a specified backend (platform) does not need any of these resource parameter it shows such warning and just ignore them.

**Comment by zfrenchee** [comment]
I've verified from the `/metadata` API endpoint on cromwell that different jobs are being assigned different levels of memory, so I can ignore the warnings. Thanks @leepc12 !
