### ISSUE TITLE
Better error message when python file isn't found

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/atac-seq-pipeline#98]
**Describe the bug**
When I go to run this workflow, Cromwell seems to generate a file called `cromwell-executions/atac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/execution/script` to run the trim_adapter step. That script contains a line: 

```
python $(which encode_trim_adapter.py) \
    /pool/data/cromwell-aals/cromwell-executions/atac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/execution/write_tsv_739e9e4f20e685e6870d57321b5cfe99.tmp \
     \
    --adapters /pool/data/cromwell-aals/cromwell-executions/atac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/execution/write_tsv_d41d8cd98f00b204e9800998ecf8427e.tmp \
    --paired-end \
    --auto-detect-adapter \
    --cutadapt-param ' -e 0.1 -m 5' \
    --nth 2
)
```

Which is failing for me when I try to run this pipeline with [singularity](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/workflow_opts/singularity.json) instead of [docker](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/workflow_opts/docker.json). (docker works)

The error is: 

```
  File "/pool/data/cromwell-aals/cromwell-executions/atac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/execution/write_tsv_739e9e4f20e685e6870d57321b5cfe99.tmp", line 1
    /pool/data/cromwell-aals/cromwell-executions/atac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/inputs/-1757892320/ALS-0BUU_diMN32_rep1_1.fastq    /pool/data/cromwell-aals/cromwell-executions/a
tac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/inputs/-1757892320/ALS-0BUU_diMN32_rep1_2.fastq
    ^
SyntaxError: invalid syntax
```

Which I now believe is resulting because `$(which encode_trim_adapter.py)` is returning empty string, so python is looking in the next file in the command, in my case

```
/pool/data/cromwell-aals/cromwell-executions/atac/b4f302b9-cf6e-41f7-acc6-d39691ec450f/call-trim_adapter/shard-0/execution/write_tsv_739e9e4f20e685e6870d57321b5cfe99.tmp 
```

which Is just a tsv which contains the filepaths to my single pair of fastqs, i.e. not valid python.

### Questions

1. Would it be possible to add better error messages, in case `$(which encode_trim_adapter.py)` returns empty string? 

~2. Why does switching from docker to singularity result in the scripts no longer being accessible? Are they included in the docker container but not the singularity container?~ was just a config issue.

**OS/Platform and dependencies**
- Debian 8.11
- cromwell-34.jar
- singularity version 3.1.0-52.g3e3c113
- atac-seq-pipeline 1.1.17

**Comment by leepc12** [comment]
`encode_trim_adapter.py` lives inside the container (singularity/docker).

Check if your singularity image has it
```
$ singularity exec ~/.singularity/atac-seq-pipeline-v1.1.7.simg which encode_trim_adapter.py
/software/atac-seq-pipeline/src/encode_trim_adapter.py
```

It looks like you didn't specify the backend in the command line?
```
java -jar -Dconfig.file=backends/backend.conf -Dbackend.default=singularity ...
```

Singularity works a bit differently because cromwell does not support natively. You need to bind your data directories manually in a workflow JSON file (`workflow_opts/singularity.json`). You can find instruction for this on the tutorial page for local/singularity.

**Comment by zfrenchee** [comment]
> It looks like you didn't specify the backend in the command line?

I am specifying the configuration file when starting the server. This turned out just to be an issue of where cromwell expected to find the singularity image. 

I still think it could be nice to, as a step in this pipeline, make sure the scripts are available, and report a more obvious error message if the scripts (and the image they reside in) aren't found. Or feel free to close this issue.

**Comment by leepc12** [comment]
@zfrenchee : Thanks for your suggestion. Sure, we are planning to develop a pipeline wrapper python script that fully inspects user's inputs (input JSON, workflow opts JSON, backend.conf, type of backend, ...) and then runs a pipeline with them.
